-- object: wireless_alerts_ledger_trg
-- folder: triggers
-- depends_on: wireless_alerts, wireless_alerts_ledger
-- source: sql/oracle.sql lines 607-631

CREATE OR REPLACE TRIGGER WIRELESS_ALERTS_LEDGER_TRG
AFTER INSERT OR UPDATE ON WIRELESS_ALERTS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(16);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSE
        v_action := 'UPDATE';
    END IF;

    INSERT INTO WIRELESS_ALERTS_LEDGER (
        ALERT_PK, ALERT_TYPE, BATCH_ID, ROW_SEQUENCE, ALERT_DATE, DETECTED_AT,
        SENSOR_ID, LOCATION_ID, INTERFACE, CHANNEL, PRIMARY_MAC, SECONDARY_MAC,
        SSID, SIGNAL_DBM, BYTES, DETAILS_JSON, RAW_JSON, ACKNOWLEDGED, LEDGER_ACTION
    ) VALUES (
        :NEW.ALERT_PK, :NEW.ALERT_TYPE, :NEW.BATCH_ID, :NEW.ROW_SEQUENCE, :NEW.ALERT_DATE,
        :NEW.DETECTED_AT,
        :NEW.SENSOR_ID, :NEW.LOCATION_ID, :NEW.INTERFACE, :NEW.CHANNEL,
        :NEW.PRIMARY_MAC, :NEW.SECONDARY_MAC, :NEW.SSID, :NEW.SIGNAL_DBM, :NEW.BYTES,
        :NEW.DETAILS_JSON, :NEW.RAW_JSON, :NEW.ACKNOWLEDGED, v_action
    );
END;
/
