-- object: devices
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 30-46

CREATE TABLE DEVICES (
    DEVICE_ID         RAW(16) DEFAULT SYS_GUID(),
    WG_PUBKEY         VARCHAR2(64),
    CLAIM_TOKEN_HASH  VARCHAR2(128),
    DISPLAY_NAME      VARCHAR2(128),
    USERNAME          VARCHAR2(128),
    HOSTNAME          VARCHAR2(253),
    OS_HINT           VARCHAR2(64),
    MAC_HINT          VARCHAR2(17),
    FIRST_SEEN        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    LAST_SEEN         TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    NOTES             VARCHAR2(512),
    CONSTRAINT DEVICES_PK PRIMARY KEY (DEVICE_ID) RELY
);
CREATE INDEX DEVICES_WG_PUBKEY_IDX ON DEVICES (WG_PUBKEY);
CREATE INDEX DEVICES_USERNAME_IDX ON DEVICES (USERNAME, LAST_SEEN DESC);
CREATE UNIQUE INDEX DEVICES_CLAIM_TOKEN_UQ ON DEVICES (CLAIM_TOKEN_HASH);
