-- object: proxy_events
-- folder: tables
-- depends_on: devices
-- source: sql/oracle.sql lines 48-86

CREATE TABLE PROXY_EVENTS (
    ID                   NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID             VARCHAR2(36) NOT NULL,
    ROW_SEQUENCE         NUMBER(10,0) NOT NULL,
    EVENT_TIME           TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    EVENT_TIMESTAMP_UTC  TIMESTAMP(3) DEFAULT CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP(3)) NOT NULL,
    EVENT_TYPE           VARCHAR2(32) NOT NULL,
    HOST                 VARCHAR2(253) NOT NULL,
    PEER_IP              VARCHAR2(45),
    WG_PUBKEY            VARCHAR2(64),
    DEVICE_ID            RAW(16),
    IDENTITY_SOURCE      VARCHAR2(16) DEFAULT 'unknown',
    PEER_HOSTNAME        VARCHAR2(253),
    CLIENT_UA            VARCHAR2(512),
    BYTES_UP             NUMBER(20) DEFAULT 0,
    BYTES_DOWN           NUMBER(20) DEFAULT 0,
    STATUS_CODE          NUMBER(5),
    BLOCKED              NUMBER(1) DEFAULT 0 CHECK (BLOCKED IN (0,1)),
    OBFUSCATION_PROFILE  VARCHAR2(32),
    CORRELATION_ID       RAW(16),
    PARENT_EVENT_ID      NUMBER,
    EVENT_SEQUENCE       NUMBER(10,0),
    DURATION_MS          NUMBER(12,0),
    REASON               VARCHAR2(64),
    RAW_JSON             JSON,
    CONSTRAINT PROXY_EVENTS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (EVENT_TIMESTAMP_UTC)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_EVENTS_INIT VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00')
);
CREATE UNIQUE INDEX PROXY_EVENTS_BATCH_ROW_IDX ON PROXY_EVENTS (BATCH_ID, ROW_SEQUENCE);
CREATE INDEX PROXY_EVENTS_EVENT_UTC_IDX ON PROXY_EVENTS (EVENT_TIMESTAMP_UTC) LOCAL;
CREATE INDEX PROXY_EVENTS_TIME_IDX ON PROXY_EVENTS (EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_HOST_IDX ON PROXY_EVENTS (HOST, EVENT_TIME) LOCAL;
CREATE INDEX PROXY_EVENTS_BLOCKED_IDX ON PROXY_EVENTS (BLOCKED, EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_DEVICE_TIME_IDX ON PROXY_EVENTS (DEVICE_ID, EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_WG_PUBKEY_TIME_IDX ON PROXY_EVENTS (WG_PUBKEY, EVENT_TIME DESC) LOCAL;
