-- object: proxy_blocked_host_rollups
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 88-111

CREATE TABLE PROXY_BLOCKED_HOST_ROLLUPS (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    HOST               VARCHAR2(253) NOT NULL,
    BLOCKED_ATTEMPTS   NUMBER(20) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES      NUMBER(20) DEFAULT 0 NOT NULL,
    FREQUENCY_HZ       NUMBER(10,4) DEFAULT 0 NOT NULL,
    VERDICT            VARCHAR2(32) NOT NULL,
    CATEGORY           VARCHAR2(64),
    RISK_SCORE         NUMBER(10,4) DEFAULT 0,
    TARPIT_HELD_MS     NUMBER(20) DEFAULT 0,
    IAT_MS             NUMBER(20),
    CONSECUTIVE_BLOCKS NUMBER(10) DEFAULT 0,
    LAST_VERDICT       VARCHAR2(32),
    TLS_VER            VARCHAR2(16),
    ALPN               VARCHAR2(64),
    JA3_LITE           VARCHAR2(512),
    RESOLVED_IP        VARCHAR2(45),
    ASN_ORG            VARCHAR2(128),
    UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    FIRST_SEEN         TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CONSTRAINT PROXY_BLOCKED_HOST_ROLLUPS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PROXY_BLOCKED_HOST_UQ ON PROXY_BLOCKED_HOST_ROLLUPS (HOST);
CREATE INDEX PROXY_BLOCKED_UPDATED_IDX ON PROXY_BLOCKED_HOST_ROLLUPS (UPDATED_AT DESC);
