-- object: proxy_payload_audit
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 113-136

CREATE BLOCKCHAIN TABLE PROXY_PAYLOAD_AUDIT (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CORRELATION_ID     RAW(16) NOT NULL,
    HOST               VARCHAR2(253) NOT NULL,
    DIRECTION          VARCHAR2(4) NOT NULL CHECK (DIRECTION IN ('UP','DOWN')),
    CAPTURED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    BYTE_OFFSET        NUMBER(10,0) DEFAULT 0 NOT NULL,
    PAYLOAD_OBJECT_KEY VARCHAR2(512),
    CONTENT_TYPE       VARCHAR2(128),
    HTTP_METHOD        VARCHAR2(16),
    HTTP_STATUS        NUMBER(5,0),
    HTTP_PATH          VARCHAR2(1024),
    IS_ENCRYPTED       NUMBER(1,0) DEFAULT 0 NOT NULL,
    TRUNCATED          NUMBER(1,0) DEFAULT 0 NOT NULL,
    PEER_IP            VARCHAR2(45),
    NOTES              VARCHAR2(512),
    CONSTRAINT PROXY_PAYLOAD_AUDIT_PK PRIMARY KEY (ID)
)
NO DROP UNTIL 16 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;
CREATE INDEX PROXY_PAYLOAD_CORR_IDX ON PROXY_PAYLOAD_AUDIT(CORRELATION_ID);
CREATE UNIQUE INDEX PROXY_PAYLOAD_AUDIT_UQ ON PROXY_PAYLOAD_AUDIT(CORRELATION_ID, HOST, DIRECTION, CAPTURED_AT, BYTE_OFFSET);
CREATE INDEX PROXY_PAYLOAD_HOST_IDX ON PROXY_PAYLOAD_AUDIT(HOST, CAPTURED_AT);
