-- object: proxy_tls_fingerprints
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 138-148

CREATE TABLE PROXY_TLS_FINGERPRINTS (
    JA3_LITE         VARCHAR2(512),
    FIRST_SEEN       TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    LAST_SEEN        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    SEEN_COUNT       NUMBER(10,0) DEFAULT 1 NOT NULL,
    TLS_VER          VARCHAR2(16),
    ALPN             VARCHAR2(64),
    CIPHER_COUNT     NUMBER(3,0),
    VERDICT_HINT     VARCHAR2(32),
    CONSTRAINT PROXY_TLS_FINGERPRINTS_PK PRIMARY KEY (JA3_LITE)
);
