-- object: proxy_connection_sessions
-- folder: tables
-- depends_on: devices
-- source: sql/oracle.sql lines 150-193

CREATE TABLE PROXY_CONNECTION_SESSIONS (
    SESSION_ID       RAW(16) DEFAULT SYS_GUID(),
    CORRELATION_ID   RAW(16),
    HOST             VARCHAR2(253) NOT NULL,
    PEER_IP          VARCHAR2(45),
    WG_PUBKEY        VARCHAR2(64),
    DEVICE_ID        RAW(16),
    IDENTITY_SOURCE  VARCHAR2(16) DEFAULT 'unknown',
    PEER_HOSTNAME    VARCHAR2(253),
    CLIENT_UA        VARCHAR2(512),
    TUNNEL_KIND      VARCHAR2(16) NOT NULL,
    OPENED_AT        TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    OPENED_DATE      DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(OPENED_AT) AS DATE)) VIRTUAL,
    CLOSED_AT        TIMESTAMP,
    DURATION_MS      NUMBER(12,0),
    BYTES_UP         NUMBER(18,0) DEFAULT 0,
    BYTES_DOWN       NUMBER(18,0) DEFAULT 0,
    BLOCKED          NUMBER(1,0) DEFAULT 0 NOT NULL,
    TARPITTED        NUMBER(1,0) DEFAULT 0 NOT NULL,
    TARPIT_HELD_MS   NUMBER(10,0),
    VERDICT          VARCHAR2(32),
    CATEGORY         VARCHAR2(64),
    OBFUSCATION_PROFILE VARCHAR2(32),
    TLS_VER          VARCHAR2(16),
    ALPN             VARCHAR2(64),
    JA3_LITE         VARCHAR2(512),
    RESOLVED_IP      VARCHAR2(45),
    ASN_ORG          VARCHAR2(128),
    REASON           VARCHAR2(64),
    CREATED_AT       TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_CONNECTION_SESSIONS_PK PRIMARY KEY (SESSION_ID)
        USING INDEX (CREATE UNIQUE INDEX PROXY_CONN_SESS_PK_REV ON PROXY_CONNECTION_SESSIONS (SESSION_ID) REVERSE)
)
PARTITION BY RANGE (OPENED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_CONNECTION_SESSIONS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_CONN_HOST_IDX ON PROXY_CONNECTION_SESSIONS(HOST, OPENED_AT) LOCAL;
CREATE INDEX PROXY_CONN_PEER_IDX ON PROXY_CONNECTION_SESSIONS(PEER_IP, OPENED_AT) LOCAL;
CREATE INDEX PROXY_CONN_CORR_IDX ON PROXY_CONNECTION_SESSIONS(CORRELATION_ID) LOCAL;
CREATE INDEX PROXY_CONN_DEVICE_IDX ON PROXY_CONNECTION_SESSIONS(DEVICE_ID, OPENED_AT DESC) LOCAL;
CREATE INDEX PROXY_CONN_WG_PUBKEY_IDX ON PROXY_CONNECTION_SESSIONS(WG_PUBKEY, OPENED_AT DESC) LOCAL;
