-- object: proxy_connection_session_close_dlq
-- folder: tables
-- depends_on: proxy_connection_sessions
-- source: sql/oracle.sql lines 195-227

CREATE TABLE PROXY_CONNECTION_SESSION_CLOSE_DLQ (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT       TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CAPTURED_DATE     DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    SESSION_ID        RAW(16) NOT NULL,
    REASON            VARCHAR2(64) NOT NULL,
    DURATION_MS       NUMBER(12,0),
    BYTES_UP          NUMBER(18,0),
    BYTES_DOWN        NUMBER(18,0),
    BLOCKED           NUMBER(1,0),
    TARPITTED         NUMBER(1,0),
    TARPIT_HELD_MS    NUMBER(10,0),
    VERDICT           VARCHAR2(32),
    CATEGORY          VARCHAR2(64),
    OBFUSCATION_PROFILE VARCHAR2(32),
    TLS_VER           VARCHAR2(16),
    ALPN              VARCHAR2(64),
    JA3_LITE          VARCHAR2(512),
    RESOLVED_IP       VARCHAR2(45),
    ASN_ORG           VARCHAR2(128),
    WG_PUBKEY         VARCHAR2(64),
    DEVICE_ID         RAW(16),
    IDENTITY_SOURCE   VARCHAR2(16),
    PEER_HOSTNAME     VARCHAR2(253),
    RAW_JSON          JSON,
    CONSTRAINT PROXY_CONNECTION_SESSION_CLOSE_DLQ_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_CONNECTION_SESSION_CLOSE_DLQ_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_CONN_CLOSE_DLQ_SESSION_IDX ON PROXY_CONNECTION_SESSION_CLOSE_DLQ(SESSION_ID, CAPTURED_AT DESC) LOCAL;
