-- object: proxy_wg_events
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 229-250

CREATE TABLE PROXY_WG_EVENTS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    EVENT_TIME    TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    EVENT_UTC_DATE     DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(EVENT_TIME) AS DATE)) VIRTUAL,
    EVENT_TYPE    VARCHAR2(32) NOT NULL,
    INTERFACE     VARCHAR2(16) NOT NULL,
    PEER_PUBKEY   VARCHAR2(64) NOT NULL,
    ENDPOINT_IP   VARCHAR2(45),
    ENDPOINT_PORT NUMBER(5),
    RX_BYTES      NUMBER(20) DEFAULT 0,
    TX_BYTES      NUMBER(20) DEFAULT 0,
    LATENCY_MS    NUMBER(10,3),
    RAW_JSON      JSON,
    CONSTRAINT PROXY_WG_EVENTS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (EVENT_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_WG_EVENTS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_WG_EVENTS_TIME_IDX ON PROXY_WG_EVENTS (EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_WG_EVENTS_PEER_IDX ON PROXY_WG_EVENTS (PEER_PUBKEY, EVENT_TIME DESC) LOCAL;
