-- object: proxy_wg_peer_samples
-- folder: tables
-- depends_on: devices
-- source: sql/oracle.sql lines 252-276

CREATE TABLE PROXY_WG_PEER_SAMPLES (
    SAMPLE_ID         NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SAMPLED_AT        TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    SAMPLED_DATE      DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(SAMPLED_AT) AS DATE)) VIRTUAL,
    INTERFACE         VARCHAR2(16) NOT NULL,
    WG_PUBKEY         VARCHAR2(64) NOT NULL,
    DEVICE_ID         RAW(16),
    PEER_IP           VARCHAR2(45),
    PEER_HOSTNAME     VARCHAR2(253),
    LAST_HANDSHAKE_AT TIMESTAMP,
    RX_BYTES_TOTAL    NUMBER(20,0) DEFAULT 0 NOT NULL,
    TX_BYTES_TOTAL    NUMBER(20,0) DEFAULT 0 NOT NULL,
    RX_BYTES_DELTA    NUMBER(20,0) DEFAULT 0 NOT NULL,
    TX_BYTES_DELTA    NUMBER(20,0) DEFAULT 0 NOT NULL,
    SESSIONS_ACTIVE   NUMBER(10,0) DEFAULT 0 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_WG_PEER_SAMPLES_PK PRIMARY KEY (SAMPLE_ID)
)
PARTITION BY RANGE (SAMPLED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_WG_PEER_SAMPLES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_WG_PEER_SAMPLES_WG_PUBKEY_IDX ON PROXY_WG_PEER_SAMPLES (WG_PUBKEY, SAMPLED_AT DESC) LOCAL;
CREATE INDEX PROXY_WG_PEER_SAMPLES_DEVICE_ID_IDX ON PROXY_WG_PEER_SAMPLES (DEVICE_ID, SAMPLED_AT DESC) LOCAL;
