-- object: proxy_bandwidth_samples
-- folder: tables
-- depends_on: devices
-- source: sql/oracle.sql lines 278-301

CREATE TABLE PROXY_BANDWIDTH_SAMPLES (
    SAMPLE_ID               NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SAMPLED_AT              TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    SAMPLED_DATE            DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(SAMPLED_AT) AS DATE)) VIRTUAL,
    WG_PUBKEY               VARCHAR2(64) NOT NULL,
    DEVICE_ID               RAW(16),
    BYTES_UP_DELTA          NUMBER(20,0) DEFAULT 0 NOT NULL,
    BYTES_DOWN_DELTA        NUMBER(20,0) DEFAULT 0 NOT NULL,
    SESSIONS_ACTIVE         NUMBER(10,0) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    ALLOWED_BYTES_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    BLOCKED_COUNT_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    ALLOWED_COUNT_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES_IS_APPROX NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_BANDWIDTH_SAMPLES_PK PRIMARY KEY (SAMPLE_ID)
)
PARTITION BY RANGE (SAMPLED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_BANDWIDTH_SAMPLES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_BANDWIDTH_SAMPLES_WG_PUBKEY_IDX ON PROXY_BANDWIDTH_SAMPLES (WG_PUBKEY, SAMPLED_AT DESC) LOCAL;
CREATE INDEX PROXY_BANDWIDTH_SAMPLES_DEVICE_ID_IDX ON PROXY_BANDWIDTH_SAMPLES (DEVICE_ID, SAMPLED_AT DESC) LOCAL;
