-- object: proxy_db_query_log
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 303-322

CREATE TABLE PROXY_DB_QUERY_LOG (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT   TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CAPTURED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    SESSION_ID    VARCHAR2(64),
    CLIENT_IP     VARCHAR2(45),
    DB_USER       VARCHAR2(128),
    SQL_TEXT      CLOB NOT NULL,
    ELAPSED_MS    NUMBER(12,3),
    ROWS_EXAMINED NUMBER(20),
    ROWS_RETURNED NUMBER(20),
    PLAN_HASH     VARCHAR2(64),
    RAW_JSON      JSON,
    CONSTRAINT PROXY_DB_QUERY_LOG_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_DB_QUERY_LOG_INIT VALUES LESS THAN (DATE '2026-01-01')
);
