-- object: proxy_blocklist_audit
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 324-335

CREATE BLOCKCHAIN TABLE PROXY_BLOCKLIST_AUDIT (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    HOST          VARCHAR2(253) NOT NULL,
    ACTION        VARCHAR2(32) NOT NULL,
    REASON        VARCHAR2(256),
    CAPTURED_AT   TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    RAW_JSON      JSON,
    CONSTRAINT PROXY_BLOCKLIST_AUDIT_PK PRIMARY KEY (ID)
)
NO DROP UNTIL 16 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;
