-- object: proxy_shipper_heartbeats
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 337-343

CREATE TABLE PROXY_SHIPPER_HEARTBEATS (
    SHIPPER_NAME VARCHAR2(64),
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    STATUS       VARCHAR2(32) NOT NULL,
    DETAILS_JSON JSON,
    CONSTRAINT PROXY_SHIPPER_HEARTBEATS_PK PRIMARY KEY (SHIPPER_NAME)
);
