-- object: proxy_data_retention_policies
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 345-354

CREATE TABLE PROXY_DATA_RETENTION_POLICIES (
    TABLE_NAME            VARCHAR2(128),
    RETAIN_DAYS           NUMBER(8,0) NOT NULL,
    PARTITION_KEY_COLUMN  VARCHAR2(128) NOT NULL,
    ENABLED               NUMBER(1,0) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    LAST_RETENTION_AT     TIMESTAMP WITH TIME ZONE,
    LAST_RETENTION_DETAIL VARCHAR2(512),
    UPDATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CONSTRAINT PROXY_DATA_RETENTION_POLICIES_PK PRIMARY KEY (TABLE_NAME)
);
