-- object: proxy_dlq_errors
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 385-399

CREATE TABLE PROXY_DLQ_ERRORS (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT    TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CAPTURED_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    PROCEDURE_NAME VARCHAR2(64) NOT NULL,
    ERROR_CODE     NUMBER,
    ERROR_MSG      VARCHAR2(512),
    ROW_DATA       CLOB,
    CONSTRAINT PROXY_DLQ_ERRORS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_DLQ_ERRORS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
