-- object: wireless_sensors
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 401-413

CREATE TABLE WIRELESS_SENSORS (
    SENSOR_PK     NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID     VARCHAR2(64) NOT NULL,
    LOCATION_ID   VARCHAR2(128) NOT NULL,
    INTERFACE     VARCHAR2(32) NOT NULL,
    REG_DOMAIN    VARCHAR2(8),
    FIRST_SEEN_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_SENSORS_PK PRIMARY KEY (SENSOR_PK),
    CONSTRAINT WIRELESS_SENSORS_ID_UQ UNIQUE (SENSOR_ID)
);
CREATE INDEX WIRELESS_SENSORS_LOCATION_IDX ON WIRELESS_SENSORS (LOCATION_ID);
