-- object: wireless_known_networks
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 415-426

CREATE TABLE WIRELESS_KNOWN_NETWORKS (
    NETWORK_PK  NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    LOCATION_ID VARCHAR2(128) NOT NULL,
    BSSID       VARCHAR2(17) NOT NULL,
    SSID        VARCHAR2(256),
    AUTHORIZED  NUMBER(1,0) DEFAULT 1 NOT NULL CHECK (AUTHORIZED IN (0,1)),
    VALID_FROM  TIMESTAMP WITH TIME ZONE NOT NULL,
    VALID_TO    TIMESTAMP WITH TIME ZONE,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_KNOWN_NETWORKS_PK PRIMARY KEY (NETWORK_PK)
);
CREATE UNIQUE INDEX WIRELESS_KNOWN_NETWORKS_ACTIVE_UQ
    ON WIRELESS_KNOWN_NETWORKS (LOCATION_ID, BSSID, CASE WHEN VALID_TO IS NULL THEN 1 END);
