-- object: wireless_audit_frames
-- folder: tables
-- depends_on: wireless_sensors, wireless_channels
-- source: sql/oracle.sql lines 446-495

CREATE TABLE WIRELESS_AUDIT_FRAMES (
    FRAME_PK             NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID             VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE         NUMBER(10,0) NOT NULL,
    EVENT_TYPE           VARCHAR2(64) NOT NULL,
    OBSERVED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    OBSERVED_UTC_DATE    DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(OBSERVED_AT) AS DATE)) VIRTUAL,
    SENSOR_ID            VARCHAR2(64) NOT NULL,
    LOCATION_ID          VARCHAR2(128) NOT NULL,
    INTERFACE            VARCHAR2(32) NOT NULL,
    CHANNEL              NUMBER(3,0) NOT NULL,
    BAND                 VARCHAR2(8) NOT NULL,
    FRAME_TYPE           VARCHAR2(32),
    FRAME_SUBTYPE        VARCHAR2(32) NOT NULL,
    BSSID                VARCHAR2(17),
    SOURCE_MAC           VARCHAR2(17),
    DESTINATION_MAC      VARCHAR2(17),
    TRANSMITTER_MAC      VARCHAR2(17),
    RECEIVER_MAC         VARCHAR2(17),
    DESTINATION_BSSID    VARCHAR2(17),
    SSID                 VARCHAR2(256),
    SIGNAL_DBM           NUMBER(4,0),
    SEQUENCE_NUMBER      NUMBER(6,0),
    RAW_LEN              NUMBER(6,0) NOT NULL,
    IS_RETRY             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_RETRY IN (0,1)),
    IS_MORE_DATA         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_MORE_DATA IN (0,1)),
    IS_POWER_SAVE        NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_POWER_SAVE IN (0,1)),
    IS_PROTECTED         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_PROTECTED IN (0,1)),
    IS_TO_DS             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_TO_DS IN (0,1)),
    IS_FROM_DS           NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_FROM_DS IN (0,1)),
    IS_HANDSHAKE         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_HANDSHAKE IN (0,1)),
    SECURITY_FLAGS       NUMBER(12,0) DEFAULT 0 NOT NULL,
    DEVICE_ID            VARCHAR2(128),
    USERNAME             VARCHAR2(256),
    IDENTITY_SOURCE      VARCHAR2(64) DEFAULT 'unknown' NOT NULL,
    TAGS                 VARCHAR2(2000),
    ANOMALY_REASONS      VARCHAR2(1000),
    RAW_JSON             JSON,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_AUDIT_FRAMES_PK PRIMARY KEY (FRAME_PK),
    CONSTRAINT WIRELESS_AUDIT_FRAMES_BATCH_UQ UNIQUE (BATCH_ID, ROW_SEQUENCE),
    CONSTRAINT WIRELESS_AUDIT_FRAMES_CHANNELS_FK FOREIGN KEY (CHANNEL, BAND) REFERENCES WIRELESS_CHANNELS(CHANNEL, BAND) RELY DISABLE NOVALIDATE
)
PARTITION BY RANGE (OBSERVED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_AUDIT_FRAMES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX WIRELESS_FRAMES_SENSOR_TIME_IDX ON WIRELESS_AUDIT_FRAMES (SENSOR_ID, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_LOCATION_TIME_IDX ON WIRELESS_AUDIT_FRAMES (LOCATION_ID, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_SOURCE_MAC_IDX ON WIRELESS_AUDIT_FRAMES (SOURCE_MAC, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_BSSID_IDX ON WIRELESS_AUDIT_FRAMES (BSSID, OBSERVED_AT) LOCAL;
