-- object: wireless_bandwidth_windows
-- folder: tables
-- depends_on: wireless_sensors, wireless_channels
-- source: sql/oracle.sql lines 497-539

CREATE TABLE WIRELESS_BANDWIDTH_WINDOWS (
    BW_PK                  NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID               VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE           NUMBER(10,0) NOT NULL,
    SCHEMA_VERSION         NUMBER(3,0) DEFAULT 1 NOT NULL,
    WINDOW_START           TIMESTAMP WITH TIME ZONE NOT NULL,
    WINDOW_START_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(WINDOW_START) AS DATE)) VIRTUAL,
    WINDOW_END             TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID              VARCHAR2(64) NOT NULL,
    LOCATION_ID            VARCHAR2(128) NOT NULL,
    INTERFACE              VARCHAR2(32) NOT NULL,
    CHANNEL                NUMBER(3,0) NOT NULL,
    BAND                   VARCHAR2(8) NOT NULL,
    SOURCE_MAC             VARCHAR2(17) NOT NULL,
    DESTINATION_BSSID      VARCHAR2(17) NOT NULL,
    SSID                   VARCHAR2(256),
    BYTES                  NUMBER(20,0) DEFAULT 0 NOT NULL,
    FRAME_COUNT            NUMBER(12,0) DEFAULT 0 NOT NULL,
    RETRY_COUNT            NUMBER(12,0) DEFAULT 0 NOT NULL,
    MORE_DATA_COUNT        NUMBER(12,0) DEFAULT 0 NOT NULL,
    POWER_SAVE_COUNT       NUMBER(12,0) DEFAULT 0 NOT NULL,
    STRONGEST_SIGNAL_DBM   NUMBER(4,0),
    HIST_UNDER_100         NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_100_500           NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_500_1000          NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_1000_1500         NUMBER(12,0) DEFAULT 0 NOT NULL,
    INTER_ARRIVAL_P50_MS   NUMBER(10,0),
    EXTERNAL_BSSID         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (EXTERNAL_BSSID IN (0,1)),
    THRESHOLD_EXCEEDED     NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (THRESHOLD_EXCEEDED IN (0,1)),
    WALL_CLOCK_DELTA_MS    NUMBER(12,0),
    WINDOW_IS_PARTIAL      NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (WINDOW_IS_PARTIAL IN (0,1)),
    PUBLISHED_AT           TIMESTAMP WITH TIME ZONE,
    CREATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_BW_WINDOWS_PK PRIMARY KEY (BW_PK),
    CONSTRAINT WIRELESS_BW_WINDOWS_BATCH_UQ UNIQUE (BATCH_ID, ROW_SEQUENCE),
    CONSTRAINT WIRELESS_BW_WINDOWS_RANGE_CK CHECK (WINDOW_END >= WINDOW_START),
    CONSTRAINT WIRELESS_BW_WINDOWS_CHANNELS_FK FOREIGN KEY (CHANNEL, BAND) REFERENCES WIRELESS_CHANNELS(CHANNEL, BAND) RELY DISABLE NOVALIDATE
)
PARTITION BY RANGE (WINDOW_START_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_BANDWIDTH_WINDOWS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX WIRELESS_BW_SENSOR_TIME_IDX ON WIRELESS_BANDWIDTH_WINDOWS (SENSOR_ID, WINDOW_START) LOCAL;
CREATE INDEX WIRELESS_BW_THRESHOLD_IDX ON WIRELESS_BANDWIDTH_WINDOWS (THRESHOLD_EXCEEDED, WINDOW_START) LOCAL;
CREATE INDEX WIRELESS_BW_SOURCE_MAC_IDX ON WIRELESS_BANDWIDTH_WINDOWS (SOURCE_MAC, WINDOW_START) LOCAL;
