-- object: wireless_alerts
-- folder: tables
-- depends_on: wireless_sensors
-- source: sql/oracle.sql lines 541-576

CREATE TABLE WIRELESS_ALERTS (
    ALERT_PK        NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    ALERT_TYPE      VARCHAR2(64) NOT NULL,
    BATCH_ID        VARCHAR2(128),
    ROW_SEQUENCE    NUMBER(10,0),
    ALERT_DATE      DATE,
    DETECTED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    DETECTED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(DETECTED_AT) AS DATE)) VIRTUAL,
    SENSOR_ID       VARCHAR2(64) NOT NULL,
    LOCATION_ID     VARCHAR2(128) NOT NULL,
    INTERFACE       VARCHAR2(32),
    CHANNEL         NUMBER(3,0),
    PRIMARY_MAC     VARCHAR2(17),
    SECONDARY_MAC   VARCHAR2(17),
    SSID            VARCHAR2(256),
    SIGNAL_DBM      NUMBER(4,0),
    BYTES           NUMBER(20,0),
    DETAILS_JSON    JSON,
    RAW_JSON        JSON,
    ACKNOWLEDGED    NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY VARCHAR2(128),
    ACKNOWLEDGED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_ALERTS_PK PRIMARY KEY (ALERT_PK),
    CONSTRAINT WIRELESS_ALERTS_BATCH_ID_SENTINEL_CK CHECK (BATCH_ID IS NULL OR BATCH_ID <> '__NULL_BATCH_ID__'),
    CONSTRAINT WIRELESS_ALERTS_ROW_SEQUENCE_CK CHECK (ROW_SEQUENCE IS NULL OR ROW_SEQUENCE >= 0)
)
PARTITION BY RANGE (DETECTED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_ALERTS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE UNIQUE INDEX WIRELESS_ALERTS_BATCH_UQ
    ON WIRELESS_ALERTS (ALERT_TYPE, NVL(BATCH_ID, '__NULL_BATCH_ID__'), NVL(ROW_SEQUENCE, -1));
CREATE INDEX WIRELESS_ALERTS_TYPE_TIME_IDX ON WIRELESS_ALERTS (ALERT_TYPE, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_ALERTS_SENSOR_TIME_IDX ON WIRELESS_ALERTS (SENSOR_ID, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_ALERTS_UNACK_IDX ON WIRELESS_ALERTS (ACKNOWLEDGED, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_BW_ALERT_DAY_IDX ON WIRELESS_ALERTS (ALERT_TYPE, SENSOR_ID, PRIMARY_MAC, SECONDARY_MAC, ALERT_DATE) LOCAL;
