-- object: wireless_alerts_ledger
-- folder: tables
-- depends_on: wireless_alerts
-- source: sql/oracle.sql lines 578-605

CREATE BLOCKCHAIN TABLE WIRELESS_ALERTS_LEDGER (
    LEDGER_ID      NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    ALERT_PK       NUMBER NOT NULL,
    ALERT_TYPE     VARCHAR2(64) NOT NULL,
    BATCH_ID       VARCHAR2(128),
    ROW_SEQUENCE   NUMBER(10,0),
    ALERT_DATE     DATE,
    DETECTED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID      VARCHAR2(64) NOT NULL,
    LOCATION_ID    VARCHAR2(128) NOT NULL,
    INTERFACE      VARCHAR2(32),
    CHANNEL        NUMBER(3,0),
    PRIMARY_MAC    VARCHAR2(17),
    SECONDARY_MAC  VARCHAR2(17),
    SSID           VARCHAR2(256),
    SIGNAL_DBM     NUMBER(4,0),
    BYTES          NUMBER(20,0),
    DETAILS_JSON   JSON,
    RAW_JSON       JSON,
    ACKNOWLEDGED   NUMBER(1,0) NOT NULL,
    LEDGER_ACTION  VARCHAR2(16) NOT NULL,
    CAPTURED_AT    TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CONSTRAINT WIRELESS_ALERTS_LEDGER_PK PRIMARY KEY (LEDGER_ID)
)
NO DROP UNTIL 16 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;
CREATE INDEX WIRELESS_ALERTS_LEDGER_ALERT_IDX ON WIRELESS_ALERTS_LEDGER (ALERT_PK, CAPTURED_AT);
