-- object: wireless_client_inventory
-- folder: tables
-- depends_on: wireless_sensors
-- source: sql/oracle.sql lines 633-653

CREATE TABLE WIRELESS_CLIENT_INVENTORY (
    INVENTORY_PK    NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID       VARCHAR2(64) NOT NULL,
    LOCATION_ID     VARCHAR2(128) NOT NULL,
    SNAPSHOT_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    CLIENT_MAC      VARCHAR2(17) NOT NULL,
    BSSID           VARCHAR2(17),
    SSID            VARCHAR2(256),
    DEVICE_ID       VARCHAR2(128),
    USERNAME        VARCHAR2(256),
    IDENTITY_SOURCE VARCHAR2(64),
    LAST_SEEN       TIMESTAMP WITH TIME ZONE NOT NULL,
    FIRST_SEEN      TIMESTAMP WITH TIME ZONE NOT NULL,
    SIGNAL_DBM      NUMBER(4,0),
    IS_AUTHORIZED   NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_AUTHORIZED IN (0,1)),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_CLIENT_INVENTORY_PK PRIMARY KEY (INVENTORY_PK)
);
CREATE UNIQUE INDEX WIRELESS_CLIENT_INV_UQ ON WIRELESS_CLIENT_INVENTORY (SENSOR_ID, SYS_EXTRACT_UTC(SNAPSHOT_AT), CLIENT_MAC);
CREATE INDEX WIRELESS_INV_SENSOR_SNAP_IDX ON WIRELESS_CLIENT_INVENTORY (SENSOR_ID, SNAPSHOT_AT);
CREATE INDEX WIRELESS_INV_CLIENT_MAC_IDX ON WIRELESS_CLIENT_INVENTORY (CLIENT_MAC, SNAPSHOT_AT);
