-- object: wireless_probe_requests
-- folder: tables
-- depends_on: -
-- source: sql/oracle.sql lines 655-669

CREATE TABLE WIRELESS_PROBE_REQUESTS (
    PROBE_PK    NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID    VARCHAR2(128) NOT NULL,
    CLIENT_MAC  VARCHAR2(17) NOT NULL,
    SSID        VARCHAR2(256) NOT NULL,
    KNOWN_BSSID VARCHAR2(17),
    FIRST_SEEN  TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN   TIMESTAMP WITH TIME ZONE NOT NULL,
    PROBE_COUNT NUMBER(10,0) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_PROBE_REQUESTS_PK PRIMARY KEY (PROBE_PK),
    CONSTRAINT WIRELESS_PROBE_BATCH_UQ UNIQUE (BATCH_ID, CLIENT_MAC, SSID)
);
CREATE INDEX WIRELESS_PROBES_CLIENT_MAC_IDX ON WIRELESS_PROBE_REQUESTS (CLIENT_MAC, LAST_SEEN);
CREATE INDEX WIRELESS_PROBES_SSID_IDX ON WIRELESS_PROBE_REQUESTS (SSID, LAST_SEEN);
