-- object: wireless_audit_windows
-- folder: tables
-- depends_on: wireless_sensors
-- source: sql/oracle.sql lines 671-684

CREATE TABLE WIRELESS_AUDIT_WINDOWS (
    WINDOW_CFG_PK NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID     VARCHAR2(64) NOT NULL,
    LOCATION_ID   VARCHAR2(128) NOT NULL,
    TIMEZONE      VARCHAR2(64),
    ACTIVE_DAYS   VARCHAR2(64),
    START_TIME    VARCHAR2(8),
    END_TIME      VARCHAR2(8),
    APPLIED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    SUPERSEDED_AT TIMESTAMP WITH TIME ZONE,
    PUSH_SOURCE   VARCHAR2(32) DEFAULT 'env' NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_AUDIT_WINDOWS_PK PRIMARY KEY (WINDOW_CFG_PK)
);
CREATE UNIQUE INDEX WIRELESS_AUDIT_WINDOWS_ACTIVE_UQ
    ON WIRELESS_AUDIT_WINDOWS (SENSOR_ID, LOCATION_ID, CASE WHEN SUPERSEDED_AT IS NULL THEN 1 END);
