-- object: wireless_sensor_health
-- folder: tables
-- depends_on: wireless_sensors
-- source: sql/oracle.sql lines 686-712

CREATE TABLE WIRELESS_SENSOR_HEALTH (
    HEALTH_PK          NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID          VARCHAR2(64) NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    REPORTED_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    REPORTED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(REPORTED_AT) AS DATE)) VIRTUAL,
    PACKETS_SEEN       NUMBER(20,0) DEFAULT 0 NOT NULL,
    DECODED_FRAMES     NUMBER(20,0) DEFAULT 0 NOT NULL,
    UNSUPPORTED_FRAMES NUMBER(20,0) DEFAULT 0 NOT NULL,
    PIPELINE_ERRORS    NUMBER(12,0) DEFAULT 0 NOT NULL,
    CAPTURE_ERRORS     NUMBER(12,0) DEFAULT 0 NOT NULL,
    AUDIT_WINDOW_DROPS NUMBER(20,0) DEFAULT 0 NOT NULL,
    MAC_LOOKUP_FAILURES NUMBER(12,0) DEFAULT 0 NOT NULL,
    CHANNEL_HOP_COUNT  NUMBER(12,0) DEFAULT 0 NOT NULL,
    LAG_TOTAL_MS       NUMBER(20,0),
    LAG_COUNT          NUMBER(12,0),
    AVG_LAG_MS         NUMBER(12,2) GENERATED ALWAYS AS (CASE WHEN LAG_COUNT > 0 THEN LAG_TOTAL_MS / LAG_COUNT ELSE NULL END) VIRTUAL,
    BW_WINDOW_LAG_MS   NUMBER(12,0),
    MEMORY_BACKLOG_LEN NUMBER(10,0),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_SENSOR_HEALTH_PK PRIMARY KEY (HEALTH_PK)
)
PARTITION BY RANGE (REPORTED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_SENSOR_HEALTH_INIT VALUES LESS THAN (DATE '2026-01-01')
);
