// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/atheros/search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchKind int32

const (
	SearchKind_SEARCH_KIND_UNSPECIFIED SearchKind = 0
	SearchKind_SEARCH_KIND_EVENT       SearchKind = 1
	SearchKind_SEARCH_KIND_BEHAVIOUR   SearchKind = 2
	SearchKind_SEARCH_KIND_SEQUENCE    SearchKind = 3
	SearchKind_SEARCH_KIND_DEVICE      SearchKind = 4
	SearchKind_SEARCH_KIND_CROSS       SearchKind = 5
)

// Enum value maps for SearchKind.
var (
	SearchKind_name = map[int32]string{
		0: "SEARCH_KIND_UNSPECIFIED",
		1: "SEARCH_KIND_EVENT",
		2: "SEARCH_KIND_BEHAVIOUR",
		3: "SEARCH_KIND_SEQUENCE",
		4: "SEARCH_KIND_DEVICE",
		5: "SEARCH_KIND_CROSS",
	}
	SearchKind_value = map[string]int32{
		"SEARCH_KIND_UNSPECIFIED": 0,
		"SEARCH_KIND_EVENT":       1,
		"SEARCH_KIND_BEHAVIOUR":   2,
		"SEARCH_KIND_SEQUENCE":    3,
		"SEARCH_KIND_DEVICE":      4,
		"SEARCH_KIND_CROSS":       5,
	}
)

func (x SearchKind) Enum() *SearchKind {
	p := new(SearchKind)
	*p = x
	return p
}

func (x SearchKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atheros_search_v1_search_proto_enumTypes[0].Descriptor()
}

func (SearchKind) Type() protoreflect.EnumType {
	return &file_proto_atheros_search_v1_search_proto_enumTypes[0]
}

func (x SearchKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchKind.Descriptor instead.
func (SearchKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{0}
}

type SearchMode int32

const (
	SearchMode_SEARCH_MODE_UNSPECIFIED SearchMode = 0
	SearchMode_SEARCH_MODE_DENSE       SearchMode = 1
	SearchMode_SEARCH_MODE_SPARSE      SearchMode = 2
	SearchMode_SEARCH_MODE_HYBRID      SearchMode = 3
)

// Enum value maps for SearchMode.
var (
	SearchMode_name = map[int32]string{
		0: "SEARCH_MODE_UNSPECIFIED",
		1: "SEARCH_MODE_DENSE",
		2: "SEARCH_MODE_SPARSE",
		3: "SEARCH_MODE_HYBRID",
	}
	SearchMode_value = map[string]int32{
		"SEARCH_MODE_UNSPECIFIED": 0,
		"SEARCH_MODE_DENSE":       1,
		"SEARCH_MODE_SPARSE":      2,
		"SEARCH_MODE_HYBRID":      3,
	}
)

func (x SearchMode) Enum() *SearchMode {
	p := new(SearchMode)
	*p = x
	return p
}

func (x SearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atheros_search_v1_search_proto_enumTypes[1].Descriptor()
}

func (SearchMode) Type() protoreflect.EnumType {
	return &file_proto_atheros_search_v1_search_proto_enumTypes[1]
}

func (x SearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMode.Descriptor instead.
func (SearchMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{1}
}

type SearchFilters struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LocationIds       []string               `protobuf:"bytes,1,rep,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	SensorIds         []string               `protobuf:"bytes,2,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Ssid              string                 `protobuf:"bytes,3,opt,name=ssid,proto3" json:"ssid,omitempty"`
	SourceMac         string                 `protobuf:"bytes,4,opt,name=source_mac,json=sourceMac,proto3" json:"source_mac,omitempty"`
	FrameSubtypes     []string               `protobuf:"bytes,5,rep,name=frame_subtypes,json=frameSubtypes,proto3" json:"frame_subtypes,omitempty"`
	ObservedAfter     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_after,json=observedAfter,proto3" json:"observed_after,omitempty"`
	ObservedBefore    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_before,json=observedBefore,proto3" json:"observed_before,omitempty"`
	ThreatOnly        bool                   `protobuf:"varint,8,opt,name=threat_only,json=threatOnly,proto3" json:"threat_only,omitempty"`
	HandshakeOnly     bool                   `protobuf:"varint,9,opt,name=handshake_only,json=handshakeOnly,proto3" json:"handshake_only,omitempty"`
	SecurityFlagsMask int32                  `protobuf:"varint,10,opt,name=security_flags_mask,json=securityFlagsMask,proto3" json:"security_flags_mask,omitempty"`
	Tags              []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchFilters) Reset() {
	*x = SearchFilters{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilters) ProtoMessage() {}

func (x *SearchFilters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilters.ProtoReflect.Descriptor instead.
func (*SearchFilters) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchFilters) GetLocationIds() []string {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *SearchFilters) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *SearchFilters) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *SearchFilters) GetSourceMac() string {
	if x != nil {
		return x.SourceMac
	}
	return ""
}

func (x *SearchFilters) GetFrameSubtypes() []string {
	if x != nil {
		return x.FrameSubtypes
	}
	return nil
}

func (x *SearchFilters) GetObservedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAfter
	}
	return nil
}

func (x *SearchFilters) GetObservedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedBefore
	}
	return nil
}

func (x *SearchFilters) GetThreatOnly() bool {
	if x != nil {
		return x.ThreatOnly
	}
	return false
}

func (x *SearchFilters) GetHandshakeOnly() bool {
	if x != nil {
		return x.HandshakeOnly
	}
	return false
}

func (x *SearchFilters) GetSecurityFlagsMask() int32 {
	if x != nil {
		return x.SecurityFlagsMask
	}
	return 0
}

func (x *SearchFilters) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Kind          SearchKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=atheros.search.v1.SearchKind" json:"kind,omitempty"`
	Mode          SearchMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=atheros.search.v1.SearchMode" json:"mode,omitempty"`
	Filters       *SearchFilters         `protobuf:"bytes,4,opt,name=filters,proto3" json:"filters,omitempty"`
	TopK          int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MinSimilarity float32                `protobuf:"fixed32,6,opt,name=min_similarity,json=minSimilarity,proto3" json:"min_similarity,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetKind() SearchKind {
	if x != nil {
		return x.Kind
	}
	return SearchKind_SEARCH_KIND_UNSPECIFIED
}

func (x *SearchRequest) GetMode() SearchMode {
	if x != nil {
		return x.Mode
	}
	return SearchMode_SEARCH_MODE_UNSPECIFIED
}

func (x *SearchRequest) GetFilters() *SearchFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMinSimilarity() float32 {
	if x != nil {
		return x.MinSimilarity
	}
	return 0
}

func (x *SearchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SearchResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryId           int64                  `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Results           []*SearchResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	ModeUsed          SearchMode             `protobuf:"varint,3,opt,name=mode_used,json=modeUsed,proto3,enum=atheros.search.v1.SearchMode" json:"mode_used,omitempty"`
	FallbackReason    string                 `protobuf:"bytes,4,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"`
	DenseResultCount  int32                  `protobuf:"varint,5,opt,name=dense_result_count,json=denseResultCount,proto3" json:"dense_result_count,omitempty"`
	SparseResultCount int32                  `protobuf:"varint,6,opt,name=sparse_result_count,json=sparseResultCount,proto3" json:"sparse_result_count,omitempty"`
	FusedResultCount  int32                  `protobuf:"varint,7,opt,name=fused_result_count,json=fusedResultCount,proto3" json:"fused_result_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetModeUsed() SearchMode {
	if x != nil {
		return x.ModeUsed
	}
	return SearchMode_SEARCH_MODE_UNSPECIFIED
}

func (x *SearchResponse) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

func (x *SearchResponse) GetDenseResultCount() int32 {
	if x != nil {
		return x.DenseResultCount
	}
	return 0
}

func (x *SearchResponse) GetSparseResultCount() int32 {
	if x != nil {
		return x.SparseResultCount
	}
	return 0
}

func (x *SearchResponse) GetFusedResultCount() int32 {
	if x != nil {
		return x.FusedResultCount
	}
	return 0
}

type SearchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceKey        string                 `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	SourceTable      string                 `protobuf:"bytes,2,opt,name=source_table,json=sourceTable,proto3" json:"source_table,omitempty"`
	SourceMac        string                 `protobuf:"bytes,3,opt,name=source_mac,json=sourceMac,proto3" json:"source_mac,omitempty"`
	LocationId       string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	SensorId         string                 `protobuf:"bytes,5,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ObservedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Score            float32                `protobuf:"fixed32,7,opt,name=score,proto3" json:"score,omitempty"`
	CosineSimilarity float32                `protobuf:"fixed32,8,opt,name=cosine_similarity,json=cosineSimilarity,proto3" json:"cosine_similarity,omitempty"`
	KeywordRank      float32                `protobuf:"fixed32,9,opt,name=keyword_rank,json=keywordRank,proto3" json:"keyword_rank,omitempty"`
	ThreatBoost      float32                `protobuf:"fixed32,10,opt,name=threat_boost,json=threatBoost,proto3" json:"threat_boost,omitempty"`
	Highlights       map[string]string      `protobuf:"bytes,11,rep,name=highlights,proto3" json:"highlights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags             []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	SourceKind       string                 `protobuf:"bytes,13,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	Bssid            string                 `protobuf:"bytes,14,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Ssid             string                 `protobuf:"bytes,15,opt,name=ssid,proto3" json:"ssid,omitempty"`
	FrameSubtype     string                 `protobuf:"bytes,16,opt,name=frame_subtype,json=frameSubtype,proto3" json:"frame_subtype,omitempty"`
	SequenceLogProb  float64                `protobuf:"fixed64,17,opt,name=sequence_log_prob,json=sequenceLogProb,proto3" json:"sequence_log_prob,omitempty"`
	BoostReasons     []string               `protobuf:"bytes,18,rep,name=boost_reasons,json=boostReasons,proto3" json:"boost_reasons,omitempty"`
	DetailJson       string                 `protobuf:"bytes,19,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *SearchResult) GetSourceTable() string {
	if x != nil {
		return x.SourceTable
	}
	return ""
}

func (x *SearchResult) GetSourceMac() string {
	if x != nil {
		return x.SourceMac
	}
	return ""
}

func (x *SearchResult) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *SearchResult) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SearchResult) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetCosineSimilarity() float32 {
	if x != nil {
		return x.CosineSimilarity
	}
	return 0
}

func (x *SearchResult) GetKeywordRank() float32 {
	if x != nil {
		return x.KeywordRank
	}
	return 0
}

func (x *SearchResult) GetThreatBoost() float32 {
	if x != nil {
		return x.ThreatBoost
	}
	return 0
}

func (x *SearchResult) GetHighlights() map[string]string {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *SearchResult) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchResult) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *SearchResult) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *SearchResult) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *SearchResult) GetFrameSubtype() string {
	if x != nil {
		return x.FrameSubtype
	}
	return ""
}

func (x *SearchResult) GetSequenceLogProb() float64 {
	if x != nil {
		return x.SequenceLogProb
	}
	return 0
}

func (x *SearchResult) GetBoostReasons() []string {
	if x != nil {
		return x.BoostReasons
	}
	return nil
}

func (x *SearchResult) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

type ExplainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SourceKey     string                 `protobuf:"bytes,2,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Kind          SearchKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=atheros.search.v1.SearchKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExplainRequest) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *ExplainRequest) GetKind() SearchKind {
	if x != nil {
		return x.Kind
	}
	return SearchKind_SEARCH_KIND_UNSPECIFIED
}

type ExplainResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceKey       string                 `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	DenseScore      float32                `protobuf:"fixed32,2,opt,name=dense_score,json=denseScore,proto3" json:"dense_score,omitempty"`
	SparseScore     float32                `protobuf:"fixed32,3,opt,name=sparse_score,json=sparseScore,proto3" json:"sparse_score,omitempty"`
	FusedScore      float32                `protobuf:"fixed32,4,opt,name=fused_score,json=fusedScore,proto3" json:"fused_score,omitempty"`
	ThreatBoost     float32                `protobuf:"fixed32,5,opt,name=threat_boost,json=threatBoost,proto3" json:"threat_boost,omitempty"`
	BoostReasons    []string               `protobuf:"bytes,6,rep,name=boost_reasons,json=boostReasons,proto3" json:"boost_reasons,omitempty"`
	SequenceLogProb float64                `protobuf:"fixed64,7,opt,name=sequence_log_prob,json=sequenceLogProb,proto3" json:"sequence_log_prob,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *ExplainResponse) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *ExplainResponse) GetDenseScore() float32 {
	if x != nil {
		return x.DenseScore
	}
	return 0
}

func (x *ExplainResponse) GetSparseScore() float32 {
	if x != nil {
		return x.SparseScore
	}
	return 0
}

func (x *ExplainResponse) GetFusedScore() float32 {
	if x != nil {
		return x.FusedScore
	}
	return 0
}

func (x *ExplainResponse) GetThreatBoost() float32 {
	if x != nil {
		return x.ThreatBoost
	}
	return 0
}

func (x *ExplainResponse) GetBoostReasons() []string {
	if x != nil {
		return x.BoostReasons
	}
	return nil
}

func (x *ExplainResponse) GetSequenceLogProb() float64 {
	if x != nil {
		return x.SequenceLogProb
	}
	return 0
}

type SuggestFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFiltersRequest) Reset() {
	*x = SuggestFiltersRequest{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFiltersRequest) ProtoMessage() {}

func (x *SuggestFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFiltersRequest.ProtoReflect.Descriptor instead.
func (*SuggestFiltersRequest) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestFiltersRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type SuggestFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssids         []string               `protobuf:"bytes,1,rep,name=ssids,proto3" json:"ssids,omitempty"`
	LocationIds   []string               `protobuf:"bytes,2,rep,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	SensorIds     []string               `protobuf:"bytes,3,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	FrameSubtypes []string               `protobuf:"bytes,4,rep,name=frame_subtypes,json=frameSubtypes,proto3" json:"frame_subtypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFiltersResponse) Reset() {
	*x = SuggestFiltersResponse{}
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFiltersResponse) ProtoMessage() {}

func (x *SuggestFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atheros_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFiltersResponse.ProtoReflect.Descriptor instead.
func (*SuggestFiltersResponse) Descriptor() ([]byte, []int) {
	return file_proto_atheros_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestFiltersResponse) GetSsids() []string {
	if x != nil {
		return x.Ssids
	}
	return nil
}

func (x *SuggestFiltersResponse) GetLocationIds() []string {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *SuggestFiltersResponse) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *SuggestFiltersResponse) GetFrameSubtypes() []string {
	if x != nil {
		return x.FrameSubtypes
	}
	return nil
}

var File_proto_atheros_search_v1_search_proto protoreflect.FileDescriptor

const file_proto_atheros_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"$proto/atheros/search/v1/search.proto\x12\x11atheros.search.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x03\n" +
	"\rSearchFilters\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\tR\vlocationIds\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x02 \x03(\tR\tsensorIds\x12\x12\n" +
	"\x04ssid\x18\x03 \x01(\tR\x04ssid\x12\x1d\n" +
	"\n" +
	"source_mac\x18\x04 \x01(\tR\tsourceMac\x12%\n" +
	"\x0eframe_subtypes\x18\x05 \x03(\tR\rframeSubtypes\x12A\n" +
	"\x0eobserved_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\robservedAfter\x12C\n" +
	"\x0fobserved_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eobservedBefore\x12\x1f\n" +
	"\vthreat_only\x18\b \x01(\bR\n" +
	"threatOnly\x12%\n" +
	"\x0ehandshake_only\x18\t \x01(\bR\rhandshakeOnly\x12.\n" +
	"\x13security_flags_mask\x18\n" +
	" \x01(\x05R\x11securityFlagsMask\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\"\xa2\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.atheros.search.v1.SearchKindR\x04kind\x121\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1d.atheros.search.v1.SearchModeR\x04mode\x12:\n" +
	"\afilters\x18\x04 \x01(\v2 .atheros.search.v1.SearchFiltersR\afilters\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12%\n" +
	"\x0emin_similarity\x18\x06 \x01(\x02R\rminSimilarity\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\xd7\x02\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\x03R\aqueryId\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.atheros.search.v1.SearchResultR\aresults\x12:\n" +
	"\tmode_used\x18\x03 \x01(\x0e2\x1d.atheros.search.v1.SearchModeR\bmodeUsed\x12'\n" +
	"\x0ffallback_reason\x18\x04 \x01(\tR\x0efallbackReason\x12,\n" +
	"\x12dense_result_count\x18\x05 \x01(\x05R\x10denseResultCount\x12.\n" +
	"\x13sparse_result_count\x18\x06 \x01(\x05R\x11sparseResultCount\x12,\n" +
	"\x12fused_result_count\x18\a \x01(\x05R\x10fusedResultCount\"\xf9\x05\n" +
	"\fSearchResult\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x01(\tR\tsourceKey\x12!\n" +
	"\fsource_table\x18\x02 \x01(\tR\vsourceTable\x12\x1d\n" +
	"\n" +
	"source_mac\x18\x03 \x01(\tR\tsourceMac\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tsensor_id\x18\x05 \x01(\tR\bsensorId\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x14\n" +
	"\x05score\x18\a \x01(\x02R\x05score\x12+\n" +
	"\x11cosine_similarity\x18\b \x01(\x02R\x10cosineSimilarity\x12!\n" +
	"\fkeyword_rank\x18\t \x01(\x02R\vkeywordRank\x12!\n" +
	"\fthreat_boost\x18\n" +
	" \x01(\x02R\vthreatBoost\x12O\n" +
	"\n" +
	"highlights\x18\v \x03(\v2/.atheros.search.v1.SearchResult.HighlightsEntryR\n" +
	"highlights\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1f\n" +
	"\vsource_kind\x18\r \x01(\tR\n" +
	"sourceKind\x12\x14\n" +
	"\x05bssid\x18\x0e \x01(\tR\x05bssid\x12\x12\n" +
	"\x04ssid\x18\x0f \x01(\tR\x04ssid\x12#\n" +
	"\rframe_subtype\x18\x10 \x01(\tR\fframeSubtype\x12*\n" +
	"\x11sequence_log_prob\x18\x11 \x01(\x01R\x0fsequenceLogProb\x12#\n" +
	"\rboost_reasons\x18\x12 \x03(\tR\fboostReasons\x12\x1f\n" +
	"\vdetail_json\x18\x13 \x01(\tR\n" +
	"detailJson\x1a=\n" +
	"\x0fHighlightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0eExplainRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"source_key\x18\x02 \x01(\tR\tsourceKey\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.atheros.search.v1.SearchKindR\x04kind\"\x89\x02\n" +
	"\x0fExplainResponse\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x01(\tR\tsourceKey\x12\x1f\n" +
	"\vdense_score\x18\x02 \x01(\x02R\n" +
	"denseScore\x12!\n" +
	"\fsparse_score\x18\x03 \x01(\x02R\vsparseScore\x12\x1f\n" +
	"\vfused_score\x18\x04 \x01(\x02R\n" +
	"fusedScore\x12!\n" +
	"\fthreat_boost\x18\x05 \x01(\x02R\vthreatBoost\x12#\n" +
	"\rboost_reasons\x18\x06 \x03(\tR\fboostReasons\x12*\n" +
	"\x11sequence_log_prob\x18\a \x01(\x01R\x0fsequenceLogProb\"/\n" +
	"\x15SuggestFiltersRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\x97\x01\n" +
	"\x16SuggestFiltersResponse\x12\x14\n" +
	"\x05ssids\x18\x01 \x03(\tR\x05ssids\x12!\n" +
	"\flocation_ids\x18\x02 \x03(\tR\vlocationIds\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x03 \x03(\tR\tsensorIds\x12%\n" +
	"\x0eframe_subtypes\x18\x04 \x03(\tR\rframeSubtypes*\xa4\x01\n" +
	"\n" +
	"SearchKind\x12\x1b\n" +
	"\x17SEARCH_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEARCH_KIND_EVENT\x10\x01\x12\x19\n" +
	"\x15SEARCH_KIND_BEHAVIOUR\x10\x02\x12\x18\n" +
	"\x14SEARCH_KIND_SEQUENCE\x10\x03\x12\x16\n" +
	"\x12SEARCH_KIND_DEVICE\x10\x04\x12\x15\n" +
	"\x11SEARCH_KIND_CROSS\x10\x05*p\n" +
	"\n" +
	"SearchMode\x12\x1b\n" +
	"\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEARCH_MODE_DENSE\x10\x01\x12\x16\n" +
	"\x12SEARCH_MODE_SPARSE\x10\x02\x12\x16\n" +
	"\x12SEARCH_MODE_HYBRID\x10\x032\xec\x02\n" +
	"\rSearchService\x12M\n" +
	"\x06Search\x12 .atheros.search.v1.SearchRequest\x1a!.atheros.search.v1.SearchResponse\x12S\n" +
	"\fSearchStream\x12 .atheros.search.v1.SearchRequest\x1a\x1f.atheros.search.v1.SearchResult0\x01\x12P\n" +
	"\aExplain\x12!.atheros.search.v1.ExplainRequest\x1a\".atheros.search.v1.ExplainResponse\x12e\n" +
	"\x0eSuggestFilters\x12(.atheros.search.v1.SuggestFiltersRequest\x1a).atheros.search.v1.SuggestFiltersResponseBXZVgithub.com/zlovtnik/ssl-proxy/services/atheros-search/proto/atheros/search/v1;searchv1b\x06proto3"

var (
	file_proto_atheros_search_v1_search_proto_rawDescOnce sync.Once
	file_proto_atheros_search_v1_search_proto_rawDescData []byte
)

func file_proto_atheros_search_v1_search_proto_rawDescGZIP() []byte {
	file_proto_atheros_search_v1_search_proto_rawDescOnce.Do(func() {
		file_proto_atheros_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atheros_search_v1_search_proto_rawDesc), len(file_proto_atheros_search_v1_search_proto_rawDesc)))
	})
	return file_proto_atheros_search_v1_search_proto_rawDescData
}

var file_proto_atheros_search_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_atheros_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_atheros_search_v1_search_proto_goTypes = []any{
	(SearchKind)(0),                // 0: atheros.search.v1.SearchKind
	(SearchMode)(0),                // 1: atheros.search.v1.SearchMode
	(*SearchFilters)(nil),          // 2: atheros.search.v1.SearchFilters
	(*SearchRequest)(nil),          // 3: atheros.search.v1.SearchRequest
	(*SearchResponse)(nil),         // 4: atheros.search.v1.SearchResponse
	(*SearchResult)(nil),           // 5: atheros.search.v1.SearchResult
	(*ExplainRequest)(nil),         // 6: atheros.search.v1.ExplainRequest
	(*ExplainResponse)(nil),        // 7: atheros.search.v1.ExplainResponse
	(*SuggestFiltersRequest)(nil),  // 8: atheros.search.v1.SuggestFiltersRequest
	(*SuggestFiltersResponse)(nil), // 9: atheros.search.v1.SuggestFiltersResponse
	nil,                            // 10: atheros.search.v1.SearchResult.HighlightsEntry
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_proto_atheros_search_v1_search_proto_depIdxs = []int32{
	11, // 0: atheros.search.v1.SearchFilters.observed_after:type_name -> google.protobuf.Timestamp
	11, // 1: atheros.search.v1.SearchFilters.observed_before:type_name -> google.protobuf.Timestamp
	0,  // 2: atheros.search.v1.SearchRequest.kind:type_name -> atheros.search.v1.SearchKind
	1,  // 3: atheros.search.v1.SearchRequest.mode:type_name -> atheros.search.v1.SearchMode
	2,  // 4: atheros.search.v1.SearchRequest.filters:type_name -> atheros.search.v1.SearchFilters
	5,  // 5: atheros.search.v1.SearchResponse.results:type_name -> atheros.search.v1.SearchResult
	1,  // 6: atheros.search.v1.SearchResponse.mode_used:type_name -> atheros.search.v1.SearchMode
	11, // 7: atheros.search.v1.SearchResult.observed_at:type_name -> google.protobuf.Timestamp
	10, // 8: atheros.search.v1.SearchResult.highlights:type_name -> atheros.search.v1.SearchResult.HighlightsEntry
	0,  // 9: atheros.search.v1.ExplainRequest.kind:type_name -> atheros.search.v1.SearchKind
	3,  // 10: atheros.search.v1.SearchService.Search:input_type -> atheros.search.v1.SearchRequest
	3,  // 11: atheros.search.v1.SearchService.SearchStream:input_type -> atheros.search.v1.SearchRequest
	6,  // 12: atheros.search.v1.SearchService.Explain:input_type -> atheros.search.v1.ExplainRequest
	8,  // 13: atheros.search.v1.SearchService.SuggestFilters:input_type -> atheros.search.v1.SuggestFiltersRequest
	4,  // 14: atheros.search.v1.SearchService.Search:output_type -> atheros.search.v1.SearchResponse
	5,  // 15: atheros.search.v1.SearchService.SearchStream:output_type -> atheros.search.v1.SearchResult
	7,  // 16: atheros.search.v1.SearchService.Explain:output_type -> atheros.search.v1.ExplainResponse
	9,  // 17: atheros.search.v1.SearchService.SuggestFilters:output_type -> atheros.search.v1.SuggestFiltersResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_atheros_search_v1_search_proto_init() }
func file_proto_atheros_search_v1_search_proto_init() {
	if File_proto_atheros_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atheros_search_v1_search_proto_rawDesc), len(file_proto_atheros_search_v1_search_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atheros_search_v1_search_proto_goTypes,
		DependencyIndexes: file_proto_atheros_search_v1_search_proto_depIdxs,
		EnumInfos:         file_proto_atheros_search_v1_search_proto_enumTypes,
		MessageInfos:      file_proto_atheros_search_v1_search_proto_msgTypes,
	}.Build()
	File_proto_atheros_search_v1_search_proto = out.File
	file_proto_atheros_search_v1_search_proto_goTypes = nil
	file_proto_atheros_search_v1_search_proto_depIdxs = nil
}
