apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-atheros-search
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: atheros-search
          env:
            - name: ATHSEARCH_JWT_JWKS_URI
              value: "https://gateway.rclabs.uk/realms/middleware/protocol/openid-connect/certs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-atheros-search-ui
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: ui
