apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-telemetry-grafana
  namespace: ssl-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: null
      protocol: TCP
