apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-telemetry-grafana-lan
  namespace: ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: telemetry-grafana
    app.kubernetes.io/managed-by: kustomize
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: telemetry-grafana
  ports:
    - name: https
      port: 8443
      targetPort: https
      nodePort: 30000
      protocol: TCP
