apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-proxy-platform-config
  namespace: ssl-proxy
data:
  ENVIRONMENT: prod
  IDENTITY_HOSTNAME: gateway.rclabs.uk
  IDENTITY_PUBLIC_ORIGIN: https://gateway.rclabs.uk
  IDENTITY_KEYCLOAK_ISSUER: https://gateway.rclabs.uk/realms/middleware
  SCHEMA_MIGRATOR_CORS_ORIGIN: https://migrator.rclabs.uk
  ATHEROS_SEARCH_CORS_ORIGIN: https://search.rclabs.uk
