apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-java-coordinator
  namespace: ssl-proxy
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: java-coordinator
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
