apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-proxy
  namespace: ssl-proxy
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      containers:
        - name: ssl-proxy
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 1Gi
