apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssl-proxy-tidb
  namespace: ssl-proxy
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-tidb
  namespace: ssl-proxy
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-tidb-headless
  namespace: ssl-proxy
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-proxy-tidb-config
  namespace: ssl-proxy
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ssl-proxy-tidb-init
  namespace: ssl-proxy
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ssl-proxy-tidb-init-grants
  namespace: ssl-proxy
$patch: delete
