apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-schema-migrator-backend
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-schema-migrator-ui
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: ui
