apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-proxy-data-plane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ssl-proxy
  source:
    repoURL: https://github.com/zlovtnik/ssl-proxy.git
    targetRevision: main
    path: cyber-stack/matrix/prod
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-ssl-proxy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.replicas'
