apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-proxy-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ssl-proxy-image-updater
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 1.2.4
    helm:
      releaseName: argocd-image-updater
      valuesObject:
        crds:
          install: true
          keep: true
        createClusterRoles: false
        image:
          pullPolicy: IfNotPresent
        config:
          git.user: ssl-proxy-image-updater
          git.email: ssl-proxy-image-updater@users.noreply.github.com
          log.level: info
          registries:
            - name: ssl-proxy-lan
              api_url: http://192.168.1.221:5000
              prefix: 192.168.1.221:5000
              ping: true
              insecure: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
