apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ssl-proxy-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: Namespace-scoped Argo CD Image Updater controller
  sourceRepos:
    - https://argoproj.github.io/argo-helm
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
