apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject-ssl-proxy.yaml
  - applicationset-workloads.yaml
  - jenkins-production-gate-rbac.yaml
  - traefik-default-deny.yaml
