apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject-ssl-proxy.yaml
  - application-bootstrap.yaml
  - application-data-plane.yaml
  - application-app-stack.yaml
  - application-prod-bootstrap.yaml
  - application-prod-data-plane.yaml
  - application-prod-app-stack.yaml
  - image-updater-dev.yaml
