apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-proxy-tidb-config
  namespace: ssl-proxy
data:
  tidb.toml: |
    [log]
    level = "info"
    
    [performance]
    max-procs = 0
    txn-local-latches.enable = false
    
    [prepared_plan_cache]
    enabled = true
    
    [stmt_summary]
    enable = true
