apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-proxy-tidb-config
  namespace: ssl-proxy
data:
  tidb.toml: |
    [log]
    level = "info"

    [performance]
    max-procs = 0

    [security]
    ssl-cert = "/etc/tidb-tls-server/tls.crt"
    ssl-key = "/etc/tidb-tls-server/tls.key"
