apiVersion: v1
kind: Secret
metadata:
  name: tidb-client-ca
  namespace: default
type: Opaque
data:
  ca.crt: <GENERATED_BY_SCRIPT>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-server-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <GENERATED_BY_SCRIPT>
  tls.key: <GENERATED_BY_SCRIPT>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-octopus
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-atheros-search
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-schema-migrator
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-keycloak
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-schema-owner
  namespace: default
type: Opaque
data:
  dsn: <GENERATED>
