apiVersion: v1
kind: Secret
metadata:
  name: tidb-root
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-octopus
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-atheros-search
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-schema-migrator
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-keycloak
  namespace: default
type: Opaque
data:
  password: <GENERATED>
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-schema-owner
  namespace: default
type: Opaque
data:
  password: <GENERATED>
