apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-tidb
  namespace: default
  labels:
    app: ssl-proxy-tidb
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      name: mysql
    - port: 10080
      targetPort: 10080
      name: metrics
  selector:
    app: ssl-proxy-tidb
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-proxy-tidb-headless
  namespace: default
  labels:
    app: ssl-proxy-tidb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4000
      targetPort: 4000
      name: mysql
  selector:
    app: ssl-proxy-tidb
