apiVersion: v2
name: atheros-sensor
description: Linux wireless monitor-mode sensor
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: ssl-proxy-common
    version: 0.1.0
    repository: "file://../_common"
