{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy.integrationConsole.fullname" . }}-integration-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.integrationConsole.labels" . | nindent 4 }}
    app.kubernetes.io/component: integration-console-web
spec:
  type: {{ .Values.web.service.type }}
  {{- with .Values.web.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "ssl-proxy.integrationConsole.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: integration-console-web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
{{- end }}

