apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
- namespace.yaml
- ../../base
configMapGenerator:
- behavior: merge
  files:
  - external-service-catalog.yml=config/prometheus/external-service-catalog.yml
  name: ssl-proxy-telemetry-prometheus-catalog
  namespace: ssl-proxy
images:
- digest: sha256:7313414747940780243b966483e50dd25dc4d25aea78707c9dab622e6257a7bb
  name: atheros-search
  newName: 192.168.1.242:5000/atheros-search
- digest: sha256:6dc839a84ea9aa80b0cae52b4158dd79abff6364827e7689b257411dea130618
  name: atheros-search-ui
  newName: 192.168.1.242:5000/atheros-search-ui
- digest: sha256:d3bf1e3a262a9520407a15689b0c7a0242ceb3f07b898d17f9fc09db6ec0ec9e
  name: atheros-sensor
  newName: 192.168.1.242:5000/atheros-sensor
- digest: sha256:09747f5da48f27fee8a35205cb1a37953c0c5625f02f81b48667d15e78b1c9d3
  name: java-coordinator
  newName: 192.168.1.242:5000/java-coordinator
- digest: sha256:728639f1eea50da73e022f7647417cb208347ffcc32479d23789c7eb99dc571f
  name: postgres-runtime-schema
  newName: 192.168.1.242:5000/postgres-runtime-schema
- digest: sha256:9eda68bc458ae4532d00e4c6ec7fa1014f0f192862c3e1c3e70160dd258f33ba
  name: schema-migrator-backend
  newName: 192.168.1.242:5000/schema-migrator-backend
- digest: sha256:1dc8ff2dd1868dfc2c98997ca5b538f0ddc39088ac18b6f24f96ed70f3b87443
  name: schema-migrator-ui
  newName: 192.168.1.242:5000/schema-migrator-ui
- digest: sha256:a8b00eea911c67a4b4da509bd3516bcb0478c01eebeb4c9e24b08d9e2faa6797
  name: ssl-proxy
  newName: 192.168.1.242:5000/ssl-proxy
patches:
- path: patches/external-schema-executor.yaml
- path: patches/pgbouncer-external-postgres.yaml
- path: patches/identity-hostname.yaml
- path: patches/schema-migrator-identity.yaml
- path: patches/cloudflare-edge.yaml
- path: patches/proxy.yaml
- path: patches/java-coordinator.yaml
- path: patches/atheros-search.yaml
- path: patches/atheros-sensor.yaml
- path: patches/schema-migrator-images.yaml
- path: patches/jaeger-recovery.yaml
- path: patches/alloy-positions.yaml
- path: patches/octopus-runtime.yaml
- path: patches/keycloak-direct-postgres.yaml
- patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/ssl-proxy.io~1content-hash
      value: schema-migrator-001-c728bb26dce5f13ec782e924fa61d4f3fe7a981c4611fed0c7c5291d55c621df
  target:
    kind: Job
    name: ssl-proxy-postgres-schema-executor
replacements:
- source:
    kind: ConfigMap
    name: ssl-proxy-platform-config
    fieldPath: data.IDENTITY_PUBLIC_ORIGIN
  targets:
  - select:
      kind: Deployment
      name: ssl-proxy-schema-migrator-keycloak
    fieldPaths:
    - spec.template.spec.containers.[name=keycloak].args.2
    options:
      delimiter: "="
      index: 1
