apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
- namespace.yaml
- ../../base
configMapGenerator:
- behavior: merge
  files:
  - external-service-catalog.yml=config/prometheus/external-service-catalog.yml
  name: ssl-proxy-telemetry-prometheus-catalog
  namespace: ssl-proxy
images:
- digest: sha256:f906fa5b5b15f41734621b4aa1a8c5acdf457023dc5891115bbbead5b1bd7864
  name: atheros-search
  newName: 192.168.1.242:5000/atheros-search
- digest: sha256:6dc839a84ea9aa80b0cae52b4158dd79abff6364827e7689b257411dea130618
  name: atheros-search-ui
  newName: 192.168.1.242:5000/atheros-search-ui
- digest: sha256:d3bf1e3a262a9520407a15689b0c7a0242ceb3f07b898d17f9fc09db6ec0ec9e
  name: atheros-sensor
  newName: 192.168.1.242:5000/atheros-sensor
- digest: sha256:064289fdc13a8407ae939ea653a8474bb3dae27459340dd779c9be514429036a
  name: java-coordinator
  newName: 192.168.1.242:5000/java-coordinator
- digest: sha256:895c4db2cc5e2ab6632da43bd95913f53f06f4640f6fb175a033698c22cd1057
  name: postgres-runtime-schema
  newName: 192.168.1.242:5000/postgres-runtime-schema
- digest: sha256:b3a21ef09de93a96f4707860c5612ac9fcb1a17390ba16fa38e5ae1dc2aae69e
  name: schema-migrator-backend
  newName: 192.168.1.242:5000/schema-migrator-backend
- digest: sha256:1dc8ff2dd1868dfc2c98997ca5b538f0ddc39088ac18b6f24f96ed70f3b87443
  name: schema-migrator-ui
  newName: 192.168.1.242:5000/schema-migrator-ui
- digest: sha256:a8b00eea911c67a4b4da509bd3516bcb0478c01eebeb4c9e24b08d9e2faa6797
  name: ssl-proxy
  newName: 192.168.1.242:5000/ssl-proxy
patches:
- path: patches/external-schema-executor.yaml
- path: patches/identity-hostname.yaml
- path: patches/proxy-replicas.yaml
- path: patches/resources.yaml
- path: patches/jaeger-recovery.yaml
- path: patches/alloy-positions.yaml
- path: patches/octopus-runtime.yaml
- path: patches/keycloak-direct-postgres.yaml
- patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/ssl-proxy.io~1content-hash
      value: schema-migrator-001-c728bb26dce5f13ec782e924fa61d4f3fe7a981c4611fed0c7c5291d55c621df
  target:
    kind: Job
    name: ssl-proxy-postgres-schema-executor
