/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/worker-configuration.d.ts` (hash: 3570053852eff8fff54bab958e512754)
interface __BaseEnv_Env {
	METRICS_HISTORY: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}