-- object: oracle_ilm_table_compression_policies
-- folder: ilm_policies
-- depends_on: proxy_events, proxy_connection_sessions, wireless_audit_frames, wireless_bandwidth_windows
-- source: sql/oracle.sql lines 796-809

ALTER TABLE PROXY_EVENTS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;

ALTER TABLE PROXY_CONNECTION_SESSIONS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;

ALTER TABLE WIRELESS_AUDIT_FRAMES ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
ALTER TABLE WIRELESS_BANDWIDTH_WINDOWS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
