[package]
name = "db-migrator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
native-tls = "0.2"
postgres-native-tls = "0.5"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "2"
walkdir = "2"
dotenv = "0.15"

[dev-dependencies]
tempfile = "3"
