apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
  - prometheus-configmap.yaml
  - grafana.yaml
  - grafana-configmaps.yaml
  - loki.yaml
  - loki-configmap.yaml
  - promtail.yaml
  - promtail-configmap.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - otel-collector-configmap.yaml
  - node-exporter.yaml
  - cadvisor.yaml
  - pushgateway.yaml
