apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-proxy-telemetry-otel-collector-config
  namespace: ssl-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: telemetry-otel-collector
    app.kubernetes.io/managed-by: kustomize
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 8192

      memory_limiter:
        check_interval: 5s
        limit_mib: 400
        spike_limit_mib: 100

    exporters:
      otlp/jaeger:
        endpoint: ssl-proxy-telemetry-jaeger:4317
        tls:
          insecure: true

      prometheus:
        endpoint: "0.0.0.0:8889"

      debug:

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger, debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus, debug]
