-- object: seed_proxy_data_retention_policies
-- folder: seed_data
-- depends_on: proxy_data_retention_policies, proxy_events, proxy_payload_audit, proxy_connection_sessions, proxy_connection_session_close_dlq, proxy_wg_events, proxy_wg_peer_samples, proxy_bandwidth_samples, proxy_db_query_log, proxy_blocklist_audit, wireless_audit_frames, wireless_bandwidth_windows, wireless_alerts, wireless_sensor_health
-- source: sql/oracle.sql lines 356-383

INSERT ALL
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_EVENTS', 90, 'EVENT_TIMESTAMP_UTC')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_PAYLOAD_AUDIT', 365, 'CAPTURED_AT')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_CONNECTION_SESSIONS', 90, 'OPENED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_CONNECTION_SESSION_CLOSE_DLQ', 30, 'CAPTURED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_WG_EVENTS', 30, 'EVENT_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_WG_PEER_SAMPLES', 30, 'SAMPLED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_BANDWIDTH_SAMPLES', 30, 'SAMPLED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_DB_QUERY_LOG', 30, 'CAPTURED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_BLOCKLIST_AUDIT', 365, 'CAPTURED_AT')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_AUDIT_FRAMES', 90, 'OBSERVED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_BANDWIDTH_WINDOWS', 90, 'WINDOW_START_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_ALERTS', 365, 'DETECTED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_SENSOR_HEALTH', 30, 'REPORTED_UTC_DATE')
SELECT 1 FROM DUAL;
