-- object: seed_wireless_channels
-- folder: seed_data
-- depends_on: wireless_channels
-- source: sql/oracle.sql lines 434-444

INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (1, 2412, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (6, 2437, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (11, 2462, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (36, 5180, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (40, 5200, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (44, 5220, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (48, 5240, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (149, 5745, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (153, 5765, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (157, 5785, '5GHz');
INSERT INTO WIRELESS_CHANNELS (CHANNEL, FREQUENCY_MHZ, BAND) VALUES (161, 5805, '5GHz');
