{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy-common.fullname" (dict "root" . "component" "redpanda") }}-redpanda
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy-common.labels" (dict "root" . "component" "redpanda") | nindent 4 }}
    app.kubernetes.io/component: redpanda
spec:
  selector:
    {{- include "ssl-proxy-common.selectorLabels" (dict "root" . "component" "redpanda") | nindent 4 }}
    app.kubernetes.io/component: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: admin
      port: {{ .Values.adminPort }}
      targetPort: admin
{{- end }}
