global:
  image:
    registry: ""
    pullPolicy: IfNotPresent
  rolloutRevision: ""
  serviceAccount:
    name: ssl-proxy
  podSecurityContext:
    fsGroup: 1000
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

enabled: false
replicas: 1
image:
  repository: integration-console
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
  hostPort: null
databaseSecret:
  name: tidb-integration-console
  primaryUrlKey: database-url
  syncUrlKey: sync-database-url
schema:
  integrationConsoleVersion: "001"
  integrationConsoleChecksum: "3b9225ec60b1c2a298d4dc2f6c17a10486860c3f65d92627eb914e97c6f0804d"
  octopusCoreVersion: "2026072101"
  octopusCoreChecksum: "1d06e05446773d356c5ee559da3fa33407a61df9edf968d5647820f0fda3fd43"
  atherosSearchVersion: "001"
  atherosSearchChecksum: "f401a62542a49a2bd8d8869f824c8539dcfba10b512bfd38d346ce8d2ebf836b"
resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: "1"
    memory: 1Gi
