-- V015: production Oracle schema for atheros-sensor wireless audit events.

CREATE TABLE WL_SENSORS (
    SENSOR_PK         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SENSOR_ID         VARCHAR2(64)  NOT NULL,
    LOCATION_ID       VARCHAR2(128) NOT NULL,
    INTERFACE         VARCHAR2(32)  NOT NULL,
    REG_DOMAIN        VARCHAR2(8),
    FIRST_SEEN_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_SENSORS_ID UNIQUE (SENSOR_ID)
);

CREATE INDEX IDX_WL_SENSORS_LOCATION ON WL_SENSORS (LOCATION_ID);

CREATE TABLE WL_KNOWN_NETWORKS (
    NETWORK_PK        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOCATION_ID       VARCHAR2(128) NOT NULL,
    BSSID             VARCHAR2(17)  NOT NULL,
    SSID              VARCHAR2(256),
    AUTHORIZED        NUMBER(1,0) DEFAULT 1 NOT NULL
                          CHECK (AUTHORIZED IN (0,1)),
    VALID_FROM        TIMESTAMP WITH TIME ZONE NOT NULL,
    VALID_TO          TIMESTAMP WITH TIME ZONE,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_KNOWN_NETWORKS UNIQUE (LOCATION_ID, BSSID)
);

CREATE INDEX IDX_WL_KNOWN_NETS_LOC ON WL_KNOWN_NETWORKS (LOCATION_ID, AUTHORIZED);

CREATE TABLE WL_CHANNELS (
    CHANNEL           NUMBER(3,0) PRIMARY KEY,
    FREQUENCY_MHZ     NUMBER(6,0) NOT NULL,
    BAND              VARCHAR2(8)  NOT NULL
);

INSERT INTO WL_CHANNELS VALUES (1,  2412, '2.4GHz');
INSERT INTO WL_CHANNELS VALUES (6,  2437, '2.4GHz');
INSERT INTO WL_CHANNELS VALUES (11, 2462, '2.4GHz');
INSERT INTO WL_CHANNELS VALUES (36, 5180, '5GHz');
INSERT INTO WL_CHANNELS VALUES (40, 5200, '5GHz');
INSERT INTO WL_CHANNELS VALUES (44, 5220, '5GHz');
INSERT INTO WL_CHANNELS VALUES (48, 5240, '5GHz');
INSERT INTO WL_CHANNELS VALUES (149,5745, '5GHz');
INSERT INTO WL_CHANNELS VALUES (153,5765, '5GHz');
INSERT INTO WL_CHANNELS VALUES (157,5785, '5GHz');
INSERT INTO WL_CHANNELS VALUES (161,5805, '5GHz');

CREATE TABLE WL_AUDIT_FRAMES (
    FRAME_PK             NUMBER GENERATED ALWAYS AS IDENTITY,
    BATCH_ID             VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE         NUMBER(10,0)  NOT NULL,
    EVENT_TYPE           VARCHAR2(64)  NOT NULL,
    OBSERVED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID            VARCHAR2(64)  NOT NULL,
    LOCATION_ID          VARCHAR2(128) NOT NULL,
    INTERFACE            VARCHAR2(32)  NOT NULL,
    CHANNEL              NUMBER(3,0)   NOT NULL,
    FRAME_TYPE           VARCHAR2(32),
    FRAME_SUBTYPE        VARCHAR2(32)  NOT NULL,
    BSSID                VARCHAR2(17),
    SOURCE_MAC           VARCHAR2(17),
    DESTINATION_MAC      VARCHAR2(17),
    TRANSMITTER_MAC      VARCHAR2(17),
    RECEIVER_MAC         VARCHAR2(17),
    DESTINATION_BSSID    VARCHAR2(17),
    SSID                 VARCHAR2(256),
    SIGNAL_DBM           NUMBER(4,0),
    SEQUENCE_NUMBER      NUMBER(6,0),
    RAW_LEN              NUMBER(6,0)   NOT NULL,
    IS_RETRY             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_RETRY IN (0,1)),
    IS_MORE_DATA         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_MORE_DATA IN (0,1)),
    IS_POWER_SAVE        NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_POWER_SAVE IN (0,1)),
    IS_PROTECTED         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_PROTECTED IN (0,1)),
    IS_TO_DS             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_TO_DS IN (0,1)),
    IS_FROM_DS           NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_FROM_DS IN (0,1)),
    IS_HANDSHAKE         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_HANDSHAKE IN (0,1)),
    SECURITY_FLAGS       NUMBER(12,0) DEFAULT 0 NOT NULL,
    DEVICE_ID            VARCHAR2(128),
    USERNAME             VARCHAR2(256),
    IDENTITY_SOURCE      VARCHAR2(64) DEFAULT 'unknown' NOT NULL,
    TAGS                 VARCHAR2(2000),
    ANOMALY_REASONS      VARCHAR2(1000),
    RAW_JSON             CLOB,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WL_AUDIT_FRAMES PRIMARY KEY (FRAME_PK, OBSERVED_AT),
    CONSTRAINT UQ_WL_AUDIT_FRAMES_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
) PARTITION BY RANGE (OBSERVED_AT) INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
    PARTITION WL_AUDIT_FRAMES_INIT
        VALUES LESS THAN (TO_TIMESTAMP_TZ('2026-01-01 00:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'))
);

CREATE INDEX IDX_WL_FRAMES_SENSOR_TIME
    ON WL_AUDIT_FRAMES (SENSOR_ID, OBSERVED_AT) LOCAL;
CREATE INDEX IDX_WL_FRAMES_LOCATION_TIME
    ON WL_AUDIT_FRAMES (LOCATION_ID, OBSERVED_AT) LOCAL;
CREATE INDEX IDX_WL_FRAMES_SOURCE_MAC
    ON WL_AUDIT_FRAMES (SOURCE_MAC, OBSERVED_AT) LOCAL;
CREATE INDEX IDX_WL_FRAMES_BSSID
    ON WL_AUDIT_FRAMES (BSSID, OBSERVED_AT) LOCAL;
CREATE INDEX IDX_WL_FRAMES_SUBTYPE
    ON WL_AUDIT_FRAMES (FRAME_SUBTYPE, OBSERVED_AT) LOCAL;
CREATE SEARCH INDEX IDX_WL_FRAMES_TAGS_FT
    ON WL_AUDIT_FRAMES (TAGS)
    FOR JSON;

CREATE TABLE WL_PROBE_REQUESTS (
    PROBE_PK          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID          VARCHAR2(128) NOT NULL,
    CLIENT_MAC        VARCHAR2(17)  NOT NULL,
    SSID              VARCHAR2(256) NOT NULL,
    KNOWN_BSSID       VARCHAR2(17),
    FIRST_SEEN        TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN         TIMESTAMP WITH TIME ZONE NOT NULL,
    PROBE_COUNT       NUMBER(10,0)  DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_PROBE_BATCH UNIQUE (BATCH_ID, CLIENT_MAC, SSID)
);

CREATE INDEX IDX_WL_PROBES_CLIENT_MAC
    ON WL_PROBE_REQUESTS (CLIENT_MAC, LAST_SEEN);
CREATE INDEX IDX_WL_PROBES_SSID
    ON WL_PROBE_REQUESTS (SSID, LAST_SEEN);
CREATE INDEX IDX_WL_PROBES_KNOWN_BSSID
    ON WL_PROBE_REQUESTS (KNOWN_BSSID, LAST_SEEN);

CREATE TABLE WL_BW_WINDOWS (
    BW_PK                  NUMBER GENERATED ALWAYS AS IDENTITY,
    BATCH_ID               VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE           NUMBER(10,0)  NOT NULL,
    SCHEMA_VERSION         NUMBER(3,0)   DEFAULT 1 NOT NULL,
    WINDOW_START           TIMESTAMP WITH TIME ZONE NOT NULL,
    WINDOW_END             TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID              VARCHAR2(64)  NOT NULL,
    LOCATION_ID            VARCHAR2(128) NOT NULL,
    INTERFACE              VARCHAR2(32)  NOT NULL,
    CHANNEL                NUMBER(3,0)   NOT NULL,
    SOURCE_MAC             VARCHAR2(17)  NOT NULL,
    DESTINATION_BSSID      VARCHAR2(17)  NOT NULL,
    SSID                   VARCHAR2(256),
    BYTES                  NUMBER(20,0)  DEFAULT 0 NOT NULL,
    FRAME_COUNT            NUMBER(12,0)  DEFAULT 0 NOT NULL,
    RETRY_COUNT            NUMBER(12,0)  DEFAULT 0 NOT NULL,
    MORE_DATA_COUNT        NUMBER(12,0)  DEFAULT 0 NOT NULL,
    POWER_SAVE_COUNT       NUMBER(12,0)  DEFAULT 0 NOT NULL,
    STRONGEST_SIGNAL_DBM   NUMBER(4,0),
    HIST_UNDER_100         NUMBER(12,0)  DEFAULT 0 NOT NULL,
    HIST_100_500           NUMBER(12,0)  DEFAULT 0 NOT NULL,
    HIST_500_1000          NUMBER(12,0)  DEFAULT 0 NOT NULL,
    HIST_1000_1500         NUMBER(12,0)  DEFAULT 0 NOT NULL,
    INTER_ARRIVAL_P50_MS   NUMBER(10,0),
    EXTERNAL_BSSID         NUMBER(1,0) DEFAULT 0 NOT NULL
                               CHECK (EXTERNAL_BSSID IN (0,1)),
    THRESHOLD_EXCEEDED     NUMBER(1,0) DEFAULT 0 NOT NULL
                               CHECK (THRESHOLD_EXCEEDED IN (0,1)),
    WALL_CLOCK_DELTA_MS    NUMBER(12,0),
    WINDOW_IS_PARTIAL      NUMBER(1,0) DEFAULT 0 NOT NULL
                               CHECK (WINDOW_IS_PARTIAL IN (0,1)),
    PUBLISHED_AT           TIMESTAMP WITH TIME ZONE,
    CREATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WL_BW_WINDOWS PRIMARY KEY (BW_PK, WINDOW_START),
    CONSTRAINT UQ_WL_BW_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
) PARTITION BY RANGE (WINDOW_START) INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(
    PARTITION WL_BW_WINDOWS_INIT
        VALUES LESS THAN (TO_TIMESTAMP_TZ('2026-01-01 00:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'))
);

CREATE INDEX IDX_WL_BW_SENSOR_TIME
    ON WL_BW_WINDOWS (SENSOR_ID, WINDOW_START) LOCAL;
CREATE INDEX IDX_WL_BW_THRESHOLD
    ON WL_BW_WINDOWS (THRESHOLD_EXCEEDED, WINDOW_START) LOCAL;
CREATE INDEX IDX_WL_BW_EXTERNAL
    ON WL_BW_WINDOWS (EXTERNAL_BSSID, DESTINATION_BSSID, WINDOW_START) LOCAL;
CREATE INDEX IDX_WL_BW_SOURCE_MAC
    ON WL_BW_WINDOWS (SOURCE_MAC, WINDOW_START) LOCAL;
CREATE INDEX IDX_WL_BW_LOCATION
    ON WL_BW_WINDOWS (LOCATION_ID, WINDOW_START) LOCAL;

CREATE TABLE WL_BW_ALERTS (
    ALERT_PK             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SENSOR_ID            VARCHAR2(64)  NOT NULL,
    LOCATION_ID          VARCHAR2(128) NOT NULL,
    SOURCE_MAC           VARCHAR2(17)  NOT NULL,
    DESTINATION_BSSID    VARCHAR2(17)  NOT NULL,
    SSID                 VARCHAR2(256),
    ALERT_DATE           DATE          NOT NULL,
    FIRST_WINDOW_START   TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_WINDOW_START    TIMESTAMP WITH TIME ZONE NOT NULL,
    TOTAL_BYTES          NUMBER(20,0)  DEFAULT 0 NOT NULL,
    WINDOW_COUNT         NUMBER(6,0)   DEFAULT 1 NOT NULL,
    MAX_BYTES_PER_WINDOW NUMBER(20,0)  DEFAULT 0 NOT NULL,
    ACKNOWLEDGED         NUMBER(1,0) DEFAULT 0 NOT NULL
                             CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY      VARCHAR2(128),
    ACKNOWLEDGED_AT      TIMESTAMP WITH TIME ZONE,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_BW_ALERT_DAY
        UNIQUE (SENSOR_ID, SOURCE_MAC, DESTINATION_BSSID, ALERT_DATE)
);

CREATE INDEX IDX_WL_BW_ALERTS_DATE
    ON WL_BW_ALERTS (ALERT_DATE, ACKNOWLEDGED);
CREATE INDEX IDX_WL_BW_ALERTS_LOCATION
    ON WL_BW_ALERTS (LOCATION_ID, ALERT_DATE);

CREATE TABLE WL_ALERT_ROGUE_AP (
    ALERT_PK           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID           VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE       NUMBER(10,0)  NOT NULL,
    DETECTED_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID          VARCHAR2(64)  NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    INTERFACE          VARCHAR2(32)  NOT NULL,
    CHANNEL            NUMBER(3,0)   NOT NULL,
    ROGUE_BSSID        VARCHAR2(17)  NOT NULL,
    SSID               VARCHAR2(256),
    SIGNAL_DBM         NUMBER(4,0),
    SSID_IMPERSONATION NUMBER(1,0) DEFAULT 0 NOT NULL
                           CHECK (SSID_IMPERSONATION IN (0,1)),
    ACKNOWLEDGED       NUMBER(1,0) DEFAULT 0 NOT NULL
                           CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY    VARCHAR2(128),
    ACKNOWLEDGED_AT    TIMESTAMP WITH TIME ZONE,
    RAW_JSON           CLOB,
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_ROGUE_AP_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
);

CREATE INDEX IDX_WL_ROGUE_SENSOR
    ON WL_ALERT_ROGUE_AP (SENSOR_ID, DETECTED_AT);
CREATE INDEX IDX_WL_ROGUE_LOCATION
    ON WL_ALERT_ROGUE_AP (LOCATION_ID, DETECTED_AT);
CREATE INDEX IDX_WL_ROGUE_BSSID
    ON WL_ALERT_ROGUE_AP (ROGUE_BSSID, DETECTED_AT);
CREATE INDEX IDX_WL_ROGUE_UNACK
    ON WL_ALERT_ROGUE_AP (ACKNOWLEDGED, DETECTED_AT);

CREATE TABLE WL_ALERT_DEAUTH_FLOOD (
    ALERT_PK           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID           VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE       NUMBER(10,0)  NOT NULL,
    DETECTED_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID          VARCHAR2(64)  NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    INTERFACE          VARCHAR2(32)  NOT NULL,
    CHANNEL            NUMBER(3,0)   NOT NULL,
    ATTACKER_MAC       VARCHAR2(17),
    TARGET_BSSID       VARCHAR2(17),
    TARGET_SSID        VARCHAR2(256),
    DEAUTH_COUNT       NUMBER(10,0)  NOT NULL,
    WINDOW_SECS        NUMBER(6,0)   NOT NULL,
    THRESHOLD          NUMBER(10,0)  NOT NULL,
    SIGNAL_DBM         NUMBER(4,0),
    ACKNOWLEDGED       NUMBER(1,0) DEFAULT 0 NOT NULL
                           CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY    VARCHAR2(128),
    ACKNOWLEDGED_AT    TIMESTAMP WITH TIME ZONE,
    RAW_JSON           CLOB,
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_DEAUTH_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
);

CREATE INDEX IDX_WL_DEAUTH_SENSOR
    ON WL_ALERT_DEAUTH_FLOOD (SENSOR_ID, DETECTED_AT);
CREATE INDEX IDX_WL_DEAUTH_LOCATION
    ON WL_ALERT_DEAUTH_FLOOD (LOCATION_ID, DETECTED_AT);
CREATE INDEX IDX_WL_DEAUTH_ATTACKER
    ON WL_ALERT_DEAUTH_FLOOD (ATTACKER_MAC, DETECTED_AT);
CREATE INDEX IDX_WL_DEAUTH_UNACK
    ON WL_ALERT_DEAUTH_FLOOD (ACKNOWLEDGED, DETECTED_AT);

CREATE TABLE WL_ALERT_SIGNAL_ANOMALY (
    ALERT_PK           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID           VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE       NUMBER(10,0)  NOT NULL,
    DETECTED_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID          VARCHAR2(64)  NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    SOURCE_MAC         VARCHAR2(17)  NOT NULL,
    BSSID              VARCHAR2(17),
    SSID               VARCHAR2(256),
    CHANNEL            NUMBER(3,0)   NOT NULL,
    BASELINE_DBM       NUMBER(4,0)   NOT NULL,
    OBSERVED_DBM       NUMBER(4,0)   NOT NULL,
    DBM_DELTA          NUMBER(4,0)   NOT NULL CHECK (DBM_DELTA >= 0),
    CONFIGURED_DELTA   NUMBER(4,0)   NOT NULL,
    ACKNOWLEDGED       NUMBER(1,0) DEFAULT 0 NOT NULL
                           CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY    VARCHAR2(128),
    ACKNOWLEDGED_AT    TIMESTAMP WITH TIME ZONE,
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_SIGNAL_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
);

CREATE INDEX IDX_WL_SIGNAL_SENSOR
    ON WL_ALERT_SIGNAL_ANOMALY (SENSOR_ID, DETECTED_AT);
CREATE INDEX IDX_WL_SIGNAL_MAC
    ON WL_ALERT_SIGNAL_ANOMALY (SOURCE_MAC, DETECTED_AT);
CREATE INDEX IDX_WL_SIGNAL_UNACK
    ON WL_ALERT_SIGNAL_ANOMALY (ACKNOWLEDGED, DETECTED_AT);

CREATE TABLE WL_ALERT_PMF_ATTACK (
    ALERT_PK            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID            VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE        NUMBER(10,0)  NOT NULL,
    DETECTED_AT         TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID           VARCHAR2(64)  NOT NULL,
    LOCATION_ID         VARCHAR2(128) NOT NULL,
    TARGET_MAC          VARCHAR2(17)  NOT NULL,
    TARGET_BSSID        VARCHAR2(17),
    SSID                VARCHAR2(256),
    CHANNEL             NUMBER(3,0),
    ATTACK_TAG          VARCHAR2(128) NOT NULL,
    RECONNECT_WINDOW_MS NUMBER(10,0),
    ACKNOWLEDGED        NUMBER(1,0) DEFAULT 0 NOT NULL
                            CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY     VARCHAR2(128),
    ACKNOWLEDGED_AT     TIMESTAMP WITH TIME ZONE,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_PMF_BATCH UNIQUE (BATCH_ID, ROW_SEQUENCE)
);

CREATE INDEX IDX_WL_PMF_SENSOR
    ON WL_ALERT_PMF_ATTACK (SENSOR_ID, DETECTED_AT);
CREATE INDEX IDX_WL_PMF_TARGET
    ON WL_ALERT_PMF_ATTACK (TARGET_MAC, DETECTED_AT);

CREATE TABLE WL_CLIENT_INVENTORY (
    INVENTORY_PK       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SENSOR_ID          VARCHAR2(64)  NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    SNAPSHOT_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    CLIENT_MAC         VARCHAR2(17)  NOT NULL,
    BSSID              VARCHAR2(17),
    SSID               VARCHAR2(256),
    DEVICE_ID          VARCHAR2(128),
    USERNAME           VARCHAR2(256),
    IDENTITY_SOURCE    VARCHAR2(64),
    LAST_SEEN          TIMESTAMP WITH TIME ZONE NOT NULL,
    FIRST_SEEN         TIMESTAMP WITH TIME ZONE NOT NULL,
    SIGNAL_DBM         NUMBER(4,0),
    IS_AUTHORIZED      NUMBER(1,0) DEFAULT 0 NOT NULL
                           CHECK (IS_AUTHORIZED IN (0,1)),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_WL_INVENTORY UNIQUE (SENSOR_ID, SNAPSHOT_AT, CLIENT_MAC)
);

CREATE INDEX IDX_WL_INV_SENSOR_SNAP
    ON WL_CLIENT_INVENTORY (SENSOR_ID, SNAPSHOT_AT);
CREATE INDEX IDX_WL_INV_CLIENT_MAC
    ON WL_CLIENT_INVENTORY (CLIENT_MAC, SNAPSHOT_AT);
CREATE INDEX IDX_WL_INV_DEVICE
    ON WL_CLIENT_INVENTORY (DEVICE_ID, SNAPSHOT_AT);
CREATE INDEX IDX_WL_INV_LATEST
    ON WL_CLIENT_INVENTORY (SENSOR_ID, SNAPSHOT_AT DESC);

CREATE TABLE WL_AUDIT_WINDOWS (
    WINDOW_CFG_PK      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SENSOR_ID          VARCHAR2(64)   NOT NULL,
    LOCATION_ID        VARCHAR2(128)  NOT NULL,
    TIMEZONE           VARCHAR2(64),
    ACTIVE_DAYS        VARCHAR2(64),
    START_TIME         VARCHAR2(8),
    END_TIME           VARCHAR2(8),
    APPLIED_AT         TIMESTAMP WITH TIME ZONE NOT NULL,
    SUPERSEDED_AT      TIMESTAMP WITH TIME ZONE,
    PUSH_SOURCE        VARCHAR2(32)  DEFAULT 'env' NOT NULL,
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_WL_AUDIT_WIN_SENSOR
    ON WL_AUDIT_WINDOWS (SENSOR_ID, APPLIED_AT);

CREATE TABLE WL_SENSOR_HEALTH (
    HEALTH_PK              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SENSOR_ID              VARCHAR2(64)  NOT NULL,
    LOCATION_ID            VARCHAR2(128) NOT NULL,
    REPORTED_AT            TIMESTAMP WITH TIME ZONE NOT NULL,
    PACKETS_SEEN           NUMBER(20,0)  DEFAULT 0 NOT NULL,
    DECODED_FRAMES         NUMBER(20,0)  DEFAULT 0 NOT NULL,
    UNSUPPORTED_FRAMES     NUMBER(20,0)  DEFAULT 0 NOT NULL,
    PIPELINE_ERRORS        NUMBER(12,0)  DEFAULT 0 NOT NULL,
    CAPTURE_ERRORS         NUMBER(12,0)  DEFAULT 0 NOT NULL,
    AUDIT_WINDOW_DROPS     NUMBER(20,0)  DEFAULT 0 NOT NULL,
    MAC_LOOKUP_FAILURES    NUMBER(12,0)  DEFAULT 0 NOT NULL,
    CHANNEL_HOP_COUNT      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    LAG_TOTAL_MS           NUMBER(20,0),
    LAG_COUNT              NUMBER(12,0),
    AVG_LAG_MS             NUMBER(12,2)
                               GENERATED ALWAYS AS
                               (CASE WHEN LAG_COUNT > 0
                                    THEN LAG_TOTAL_MS / LAG_COUNT
                                    ELSE NULL END) VIRTUAL,
    BW_WINDOW_LAG_MS       NUMBER(12,0),
    MEMORY_BACKLOG_LEN     NUMBER(10,0),
    CREATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_WL_HEALTH_SENSOR_TIME
    ON WL_SENSOR_HEALTH (SENSOR_ID, REPORTED_AT);
CREATE INDEX IDX_WL_HEALTH_ERRORS
    ON WL_SENSOR_HEALTH (SENSOR_ID, PIPELINE_ERRORS, REPORTED_AT);

CREATE OR REPLACE PROCEDURE WL_BW_MERGE_ALERTS (
    p_batch_id IN VARCHAR2
)
AS
BEGIN
    MERGE INTO WL_BW_ALERTS tgt
    USING (
        WITH batch_keys AS (
            SELECT DISTINCT
                SENSOR_ID,
                SOURCE_MAC,
                DESTINATION_BSSID,
                TRUNC(CAST(WINDOW_START AS DATE)) AS ALERT_DATE
            FROM WL_BW_WINDOWS
            WHERE BATCH_ID = p_batch_id
              AND THRESHOLD_EXCEEDED = 1
        )
        SELECT
            w.SENSOR_ID,
            MAX(w.LOCATION_ID) KEEP (DENSE_RANK LAST ORDER BY w.WINDOW_START) AS LOCATION_ID,
            w.SOURCE_MAC,
            w.DESTINATION_BSSID,
            MAX(w.SSID) KEEP (DENSE_RANK LAST ORDER BY w.WINDOW_START) AS SSID,
            TRUNC(CAST(w.WINDOW_START AS DATE)) AS ALERT_DATE,
            MIN(w.WINDOW_START) AS FIRST_WINDOW_START,
            MAX(w.WINDOW_START) AS LAST_WINDOW_START,
            SUM(w.BYTES) AS TOTAL_BYTES,
            COUNT(*) AS WINDOW_COUNT,
            MAX(w.BYTES) AS MAX_BYTES_PER_WINDOW
        FROM WL_BW_WINDOWS w
        JOIN batch_keys k
          ON k.SENSOR_ID = w.SENSOR_ID
         AND k.SOURCE_MAC = w.SOURCE_MAC
         AND k.DESTINATION_BSSID = w.DESTINATION_BSSID
         AND k.ALERT_DATE = TRUNC(CAST(w.WINDOW_START AS DATE))
        WHERE w.THRESHOLD_EXCEEDED = 1
        GROUP BY
            w.SENSOR_ID,
            w.SOURCE_MAC,
            w.DESTINATION_BSSID,
            TRUNC(CAST(w.WINDOW_START AS DATE))
    ) src
    ON (
        tgt.SENSOR_ID = src.SENSOR_ID
        AND tgt.SOURCE_MAC = src.SOURCE_MAC
        AND tgt.DESTINATION_BSSID = src.DESTINATION_BSSID
        AND tgt.ALERT_DATE = src.ALERT_DATE
    )
    WHEN MATCHED THEN UPDATE SET
        tgt.LOCATION_ID = src.LOCATION_ID,
        tgt.SSID = src.SSID,
        tgt.FIRST_WINDOW_START = src.FIRST_WINDOW_START,
        tgt.LAST_WINDOW_START = src.LAST_WINDOW_START,
        tgt.TOTAL_BYTES = src.TOTAL_BYTES,
        tgt.WINDOW_COUNT = src.WINDOW_COUNT,
        tgt.MAX_BYTES_PER_WINDOW = src.MAX_BYTES_PER_WINDOW,
        tgt.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
        SENSOR_ID, LOCATION_ID, SOURCE_MAC, DESTINATION_BSSID, SSID,
        ALERT_DATE, FIRST_WINDOW_START, LAST_WINDOW_START,
        TOTAL_BYTES, WINDOW_COUNT, MAX_BYTES_PER_WINDOW
    ) VALUES (
        src.SENSOR_ID, src.LOCATION_ID, src.SOURCE_MAC, src.DESTINATION_BSSID,
        src.SSID, src.ALERT_DATE, src.FIRST_WINDOW_START, src.LAST_WINDOW_START,
        src.TOTAL_BYTES, src.WINDOW_COUNT, src.MAX_BYTES_PER_WINDOW
    );
    COMMIT;
END WL_BW_MERGE_ALERTS;
/

CREATE OR REPLACE PROCEDURE WL_UPSERT_SENSOR (
    p_sensor_id    IN VARCHAR2,
    p_location_id  IN VARCHAR2,
    p_interface    IN VARCHAR2,
    p_reg_domain   IN VARCHAR2,
    p_observed_at  IN TIMESTAMP WITH TIME ZONE
)
AS
BEGIN
    MERGE INTO WL_SENSORS tgt
    USING (SELECT 1 FROM DUAL) dummy
    ON (tgt.SENSOR_ID = p_sensor_id)
    WHEN MATCHED THEN UPDATE SET
        tgt.LOCATION_ID = p_location_id,
        tgt.INTERFACE = p_interface,
        tgt.LAST_SEEN_AT = p_observed_at
    WHEN NOT MATCHED THEN INSERT (
        SENSOR_ID, LOCATION_ID, INTERFACE, REG_DOMAIN,
        FIRST_SEEN_AT, LAST_SEEN_AT
    ) VALUES (
        p_sensor_id, p_location_id, p_interface, p_reg_domain,
        p_observed_at, p_observed_at
    );
    COMMIT;
END WL_UPSERT_SENSOR;
/

CREATE OR REPLACE PROCEDURE WL_PURGE_OLD_PARTITIONS (
    p_retain_months IN NUMBER DEFAULT 24
)
AS
    v_cutoff DATE := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -p_retain_months);
    v_should_drop NUMBER(1,0);
BEGIN
    FOR rec IN (
        SELECT table_name, partition_name, high_value
        FROM   user_tab_partitions
        WHERE  table_name IN ('WL_AUDIT_FRAMES', 'WL_BW_WINDOWS')
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE
                'SELECT CASE WHEN ' || rec.high_value ||
                ' <= TO_TIMESTAMP_TZ(''' || TO_CHAR(v_cutoff, 'YYYY-MM-DD') ||
                ' 00:00:00 UTC'', ''YYYY-MM-DD HH24:MI:SS TZR'') THEN 1 ELSE 0 END FROM DUAL'
            INTO v_should_drop;
            IF v_should_drop = 1 THEN
                EXECUTE IMMEDIATE 'ALTER TABLE ' || rec.table_name ||
                    ' DROP PARTITION ' || rec.partition_name ||
                    ' UPDATE GLOBAL INDEXES';
            END IF;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    COMMIT;
END WL_PURGE_OLD_PARTITIONS;
/

CREATE OR REPLACE VIEW VW_WL_ACTIVE_THREATS AS
SELECT
    THREAT_TYPE,
    SEVERITY,
    EVENT_AT,
    SENSOR_ID,
    LOCATION_ID,
    PRIMARY_MAC,
    SSID,
    BYTES,
    ALERT_PK,
    ACKNOWLEDGED
FROM (
    SELECT
        'rogue_ap' AS THREAT_TYPE,
        'HIGH' AS SEVERITY,
        DETECTED_AT AS EVENT_AT,
        SENSOR_ID,
        LOCATION_ID,
        ROGUE_BSSID AS PRIMARY_MAC,
        SSID,
        CAST(NULL AS NUMBER(20,0)) AS BYTES,
        ALERT_PK,
        ACKNOWLEDGED
    FROM WL_ALERT_ROGUE_AP
    WHERE ACKNOWLEDGED = 0
    UNION ALL
    SELECT
        'deauth_flood',
        'HIGH',
        DETECTED_AT,
        SENSOR_ID,
        LOCATION_ID,
        ATTACKER_MAC,
        TARGET_SSID,
        CAST(NULL AS NUMBER(20,0)),
        ALERT_PK,
        ACKNOWLEDGED
    FROM WL_ALERT_DEAUTH_FLOOD
    WHERE ACKNOWLEDGED = 0
    UNION ALL
    SELECT
        'bandwidth_threshold',
        'CRITICAL',
        FIRST_WINDOW_START,
        SENSOR_ID,
        LOCATION_ID,
        SOURCE_MAC,
        SSID,
        TOTAL_BYTES,
        ALERT_PK,
        ACKNOWLEDGED
    FROM WL_BW_ALERTS
    WHERE ACKNOWLEDGED = 0
    UNION ALL
    SELECT
        'signal_anomaly',
        'MEDIUM',
        DETECTED_AT,
        SENSOR_ID,
        LOCATION_ID,
        SOURCE_MAC,
        SSID,
        CAST(NULL AS NUMBER(20,0)),
        ALERT_PK,
        ACKNOWLEDGED
    FROM WL_ALERT_SIGNAL_ANOMALY
    WHERE ACKNOWLEDGED = 0
    UNION ALL
    SELECT
        'pmf_attack',
        'MEDIUM',
        DETECTED_AT,
        SENSOR_ID,
        LOCATION_ID,
        TARGET_MAC,
        SSID,
        CAST(NULL AS NUMBER(20,0)),
        ALERT_PK,
        ACKNOWLEDGED
    FROM WL_ALERT_PMF_ATTACK
    WHERE ACKNOWLEDGED = 0
)
ORDER BY
    CASE SEVERITY WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 ELSE 3 END,
    EVENT_AT DESC;

CREATE OR REPLACE VIEW VW_WL_BW_DAILY_SUMMARY AS
SELECT
    TRUNC(CAST(WINDOW_START AS DATE)) AS TRAFFIC_DATE,
    SENSOR_ID,
    LOCATION_ID,
    SOURCE_MAC,
    DESTINATION_BSSID,
    SSID,
    EXTERNAL_BSSID,
    SUM(BYTES) AS TOTAL_BYTES,
    SUM(FRAME_COUNT) AS TOTAL_FRAMES,
    SUM(RETRY_COUNT) AS TOTAL_RETRIES,
    MAX(STRONGEST_SIGNAL_DBM) AS MAX_SIGNAL_DBM,
    MIN(STRONGEST_SIGNAL_DBM) AS MIN_SIGNAL_DBM,
    COUNT(*) AS WINDOW_COUNT,
    SUM(CASE WHEN THRESHOLD_EXCEEDED = 1 THEN 1 ELSE 0 END)
        AS THRESHOLD_EXCEEDED_COUNT,
    AVG(WALL_CLOCK_DELTA_MS) AS AVG_SENSOR_LAG_MS
FROM WL_BW_WINDOWS
GROUP BY
    TRUNC(CAST(WINDOW_START AS DATE)),
    SENSOR_ID, LOCATION_ID, SOURCE_MAC,
    DESTINATION_BSSID, SSID, EXTERNAL_BSSID;

CREATE OR REPLACE VIEW VW_WL_CURRENT_CLIENTS AS
SELECT inv.*
FROM WL_CLIENT_INVENTORY inv
JOIN (
    SELECT SENSOR_ID, MAX(SNAPSHOT_AT) AS LATEST_SNAP
    FROM   WL_CLIENT_INVENTORY
    GROUP BY SENSOR_ID
) latest
    ON inv.SENSOR_ID = latest.SENSOR_ID
    AND inv.SNAPSHOT_AT = latest.LATEST_SNAP;

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'WL_PURGE_PARTITIONS_MONTHLY',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'WL_PURGE_OLD_PARTITIONS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=2;BYMINUTE=0',
        enabled         => TRUE,
        comments        => 'Drop WL_AUDIT_FRAMES and WL_BW_WINDOWS partitions older than 24 months'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'WL_GATHER_STATS_NIGHTLY',
        job_type        => 'PLSQL_BLOCK',
        job_action      => '
            BEGIN
                DBMS_STATS.GATHER_TABLE_STATS(USER, ''WL_AUDIT_FRAMES'',
                    granularity=>''AUTO'', degree=>4);
                DBMS_STATS.GATHER_TABLE_STATS(USER, ''WL_BW_WINDOWS'',
                    granularity=>''AUTO'', degree=>4);
                DBMS_STATS.GATHER_TABLE_STATS(USER, ''WL_CLIENT_INVENTORY'',
                    granularity=>''AUTO'', degree=>2);
            END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY;BYHOUR=3;BYMINUTE=0',
        enabled         => TRUE,
        comments        => 'Nightly CBO stats refresh for wireless audit tables'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN
            RAISE;
        END IF;
END;
/
