apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-proxy-schema-migrator-keycloak-data
  labels:
    app.kubernetes.io/component: schema-migrator-keycloak
    app.kubernetes.io/instance: ssl-proxy
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/ssl-proxy/schema-migrator/keycloak-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - wiretrap
