{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy.postgres.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "ssl-proxy.postgres.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: postgres
{{- end }}
