apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-telemetry-jaeger
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: jaeger
          env:
            - name: SPAN_STORAGE_TYPE
              value: "memory"
            - name: MEMORY_MAX_TRACES
              value: "10000"
            - $patch: delete
              name: BADGER_EPHEMERAL
            - $patch: delete
              name: BADGER_DIRECTORY_KEY
            - $patch: delete
              name: BADGER_DIRECTORY_VALUE
          volumeMounts:
            - $patch: delete
              name: data
      volumes:
        - $patch: delete
          name: data
