apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-proxy-java-coordinator
  namespace: ssl-proxy
spec:
  template:
    spec:
      containers:
        - name: java-coordinator
          env:
            - name: OCTOPUS_ENVIRONMENT
              value: "development"
            - name: OCTOPUS_CUTOVER_DEV_BYPASS
              value: "true"
