-- object: vw_wireless_bw_daily_summary
-- folder: views
-- depends_on: wireless_bandwidth_windows
-- source: sql/oracle.sql lines 934-951

CREATE OR REPLACE VIEW VW_WIRELESS_BW_DAILY_SUMMARY AS
SELECT TRUNC(CAST(WINDOW_START AS DATE)) AS TRAFFIC_DATE,
       SENSOR_ID,
       LOCATION_ID,
       SOURCE_MAC,
       DESTINATION_BSSID,
       SSID,
       EXTERNAL_BSSID,
       SUM(BYTES) AS TOTAL_BYTES,
       SUM(FRAME_COUNT) AS TOTAL_FRAMES,
       SUM(RETRY_COUNT) AS TOTAL_RETRIES,
       MAX(STRONGEST_SIGNAL_DBM) AS MAX_SIGNAL_DBM,
       MIN(STRONGEST_SIGNAL_DBM) AS MIN_SIGNAL_DBM,
       COUNT(*) AS WINDOW_COUNT,
       SUM(CASE WHEN THRESHOLD_EXCEEDED = 1 THEN 1 ELSE 0 END) AS THRESHOLD_EXCEEDED_COUNT,
       AVG(WALL_CLOCK_DELTA_MS) AS AVG_SENSOR_LAG_MS
FROM WIRELESS_BANDWIDTH_WINDOWS
GROUP BY TRUNC(CAST(WINDOW_START AS DATE)), SENSOR_ID, LOCATION_ID, SOURCE_MAC, DESTINATION_BSSID, SSID, EXTERNAL_BSSID;
