apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-ssl-proxy
resources:
  - namespace.yaml
  - ../../base
images:
  - name: ssl-proxy
    newName: 192.168.1.221:5000/ssl-proxy
    newTag: d7f190b
  - name: java-coordinator
    newName: 192.168.1.221:5000/java-coordinator
    newTag: d7f190b
  - name: atheros-sensor
    newName: 192.168.1.221:5000/atheros-sensor
    newTag: d7f190b
  - name: atheros-search
    newName: 192.168.1.221:5000/atheros-search
    newTag: d7f190b
  - name: atheros-search-ui
    newName: 192.168.1.221:5000/atheros-search-ui
    newTag: d7f190b
  - name: schema-migrator-backend
    newName: 192.168.1.221:5000/schema-migrator-backend
    newTag: d7f190b
  - name: schema-migrator-ui
    newName: 192.168.1.221:5000/schema-migrator-ui
    newTag: d7f190b
  - name: tidb-runtime-schema
    newName: 192.168.1.221:5000/tidb-runtime-schema
    newTag: d7f190b
patches:
  - path: patches/proxy-replicas.yaml
  - path: patches/tidb-replicas.yaml
  - path: patches/octopus-environment.yaml
