{{- if not .Values.external }}
{{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ssl-proxy.tidb.fullname" . }}-tidb-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.tidb.labels" . | nindent 4 }}
    app.kubernetes.io/component: tidb
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }}
