{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy.tidb.fullname" . }}-tidb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.tidb.labels" . | nindent 4 }}
    app.kubernetes.io/component: tidb
spec:
  selector:
    {{- include "ssl-proxy.tidb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tidb
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
    - name: status
      port: {{ .Values.service.statusPort }}
      targetPort: status
{{- end }}
