{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy-common.fullname" (dict "root" . "component" "tidb") }}-tidb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy-common.labels" (dict "root" . "component" "tidb") | nindent 4 }}
    app.kubernetes.io/component: tidb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4000
      targetPort: 4000
      name: mysql
    - port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      name: metrics
  selector:
    {{- include "ssl-proxy-common.selectorLabels" (dict "root" . "component" "tidb") | nindent 4 }}
    app.kubernetes.io/component: tidb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy-common.fullname" (dict "root" . "component" "tidb") }}-tidb-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy-common.labels" (dict "root" . "component" "tidb") | nindent 4 }}
    app.kubernetes.io/component: tidb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4000
      targetPort: 4000
      name: mysql
  selector:
    {{- include "ssl-proxy-common.selectorLabels" (dict "root" . "component" "tidb") | nindent 4 }}
    app.kubernetes.io/component: tidb
{{- end }}
