apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssl-proxy-postgres-schema-executor
  namespace: ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: postgres-schema-executor
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres-schema-executor
      app.kubernetes.io/component: postgres-schema-executor
  policyTypes:
    - Ingress
  ingress: []
