apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
- ../../../base/platform-config/configmap.yaml
- ../../../base/proxy/deployment.yaml
- ../../../base/proxy/service.yaml
- ../../../base/java-coordinator/deployment.yaml
- ../../../base/schema-migrator
- ../../../base/atheros-sensor/daemonset.yaml
- ../../../base/atheros-search
images:
- digest: sha256:0de2212e682b3500f72e9fc8f62a154ed8737823ad22b9b933f8c117b98ce618
  name: atheros-search
  newName: 192.168.1.242:5000/atheros-search
- digest: sha256:e0f87044a0ae83c03fcf7fe82e191e058c08b0dc6ccb7ac12b94b4a4a086f0f3
  name: atheros-search-ui
  newName: 192.168.1.242:5000/atheros-search-ui
- digest: sha256:2b74bf2217b16b68f1bfba0f3529d5c0a1527e6830e8e98ccf758fec8966dc55
  name: atheros-sensor
  newName: 192.168.1.242:5000/atheros-sensor
- digest: sha256:ad485a0fa9046811fc4edcb5d5e7a192633722e3c36cb7cdfa890f63ffdfe976
  name: java-coordinator
  newName: 192.168.1.242:5000/java-coordinator
- digest: sha256:cb133fd3c2c60840381b5d521055fd4741c66b1fdb3cf60d1e93fdf885e4546f
  name: schema-migrator-backend
  newName: 192.168.1.242:5000/schema-migrator-backend
- digest: sha256:1dc8ff2dd1868dfc2c98997ca5b538f0ddc39088ac18b6f24f96ed70f3b87443
  name: schema-migrator-ui
  newName: 192.168.1.242:5000/schema-migrator-ui
- digest: sha256:ad323800e92a3ecd07ff4e394ed8e6370f60852e1abf0ab53878e13f0d6d5b6b
  name: ssl-proxy
  newName: 192.168.1.242:5000/ssl-proxy
patches:
- path: ../patches/identity-hostname.yaml
- path: ../patches/local-config-annotation.yaml
  target:
    kind: ConfigMap
    labelSelector: app.kubernetes.io/component=platform-config
- path: ../patches/proxy-replicas.yaml
- path: ../patches/resources.yaml
- path: ../patches/external-tidb.yaml
- path: ../patches/octopus-staged.yaml
configurations:
- ../../../base/schema-migrator/kustomizeconfig.yaml
vars:
- fieldref:
    fieldPath: data.IDENTITY_HOSTNAME
  name: IDENTITY_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: ssl-proxy-platform-config
