apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
- ../../../base/platform-config/configmap.yaml
- ../../../base/proxy/deployment.yaml
- ../../../base/proxy/service.yaml
- ../../../base/proxy/networkpolicy.yaml
- ../../../base/java-coordinator/deployment.yaml
- ../../../base/java-coordinator/networkpolicy.yaml
- ../../../base/schema-migrator
- ../../../base/atheros-sensor/daemonset.yaml
- ../../../base/atheros-sensor/networkpolicy.yaml
- ../../../base/atheros-search
- ../../../base/cloudflared
- ../../../base/public-gateway
images:
- digest: sha256:d7208d2b6a44eb3c7582c342784abfc1b296d0bca31e843bc040bc96f09c2790
  name: atheros-search
  newName: 192.168.1.242:5000/atheros-search
- digest: sha256:2568f0ff0b0004393477d54068d5844be3b8125e1328df915067d4d7cf2c96a7
  name: atheros-search-ui
  newName: 192.168.1.242:5000/atheros-search-ui
- digest: sha256:a3a4f2cb2223c42328b45f11b19b6d9fe99c8a51f4b946e02e3c86fe1be40b72
  name: atheros-sensor
  newName: 192.168.1.242:5000/atheros-sensor
- digest: sha256:f8f310d8820d53f18357ebfd102328e9d21342d1a0d37f231a59dc13fd362529
  name: java-coordinator
  newName: 192.168.1.242:5000/java-coordinator
- digest: sha256:5522211f7bf0570cb3a2030dfc8bb1be7a2e6c0f8533afe0e74bf4ec3de6135c
  name: schema-migrator-backend
  newName: 192.168.1.242:5000/schema-migrator-backend
- digest: sha256:3a537e228653b150c0217496cf1a73cdafb6dbef61d0f448e9382441c17c2629
  name: schema-migrator-ui
  newName: 192.168.1.242:5000/schema-migrator-ui
- digest: sha256:b3152ce07c8dc246fc387d17c2ff2b5f1c7689db53794f7d7f423a2201ce1fea
  name: ssl-proxy
  newName: 192.168.1.242:5000/ssl-proxy
patches:
- path: ../patches/identity-hostname.yaml
- path: ../patches/schema-migrator-identity.yaml
- path: ../patches/cloudflare-edge.yaml
- path: ../patches/local-config-annotation.yaml
  target:
    kind: ConfigMap
    labelSelector: app.kubernetes.io/component=platform-config
- path: ../patches/proxy.yaml
- path: ../patches/java-coordinator.yaml
- path: ../patches/atheros-search.yaml
- path: ../patches/atheros-sensor.yaml
- path: ../patches/schema-migrator-images.yaml
- path: ../patches/octopus-runtime.yaml
- path: ../patches/keycloak-direct-postgres.yaml
- path: ../patches/postgres-schema-maintenance.yaml
replacements:
- source:
    fieldPath: data.IDENTITY_PUBLIC_ORIGIN
    kind: ConfigMap
    name: ssl-proxy-platform-config
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=keycloak].args.2
    options:
      delimiter: "="
      index: 1
    select:
      kind: Deployment
      name: ssl-proxy-schema-migrator-keycloak
