apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
- ../../../base/platform-config/configmap.yaml
- ../../../base/proxy/deployment.yaml
- ../../../base/proxy/service.yaml
- ../../../base/proxy/networkpolicy.yaml
- ../../../base/java-coordinator/deployment.yaml
- ../../../base/java-coordinator/networkpolicy.yaml
- ../../../base/schema-migrator
- ../../../base/atheros-sensor/daemonset.yaml
- ../../../base/atheros-sensor/networkpolicy.yaml
- ../../../base/atheros-search
- ../../../base/cloudflared
- ../../../base/public-gateway
images:
- digest: sha256:cf6e6b7a5c7d75584f1b845130ad4dfbe829ad2c379ca5480954717089afe47a
  name: atheros-search
  newName: 192.168.1.242:5000/atheros-search
- digest: sha256:ba65517815cfe2fec4de0cc557809d20373e0b6e3813293aeeb7670bf1fa67ef
  name: atheros-search-ui
  newName: 192.168.1.242:5000/atheros-search-ui
- digest: sha256:edff623ee4ff620cca7585a645e33fc7e3b2b663b303641b9570a600cb1237b1
  name: atheros-sensor
  newName: 192.168.1.242:5000/atheros-sensor
- digest: sha256:f92d7cabe55b63e39274c8142fec873976d776bd5196668db0f86223ea371a30
  name: java-coordinator
  newName: 192.168.1.242:5000/java-coordinator
- digest: sha256:d5541dfe1e5451157cd65c6d0a35c6e6dd2ec820e5301d92869486b97d701850
  name: schema-migrator-backend
  newName: 192.168.1.242:5000/schema-migrator-backend
- digest: sha256:641a82d646cdcfbeb88aa01e9b14c38bd1075bd1fdfc74dd21f3d47eb9fb0b6d
  name: schema-migrator-ui
  newName: 192.168.1.242:5000/schema-migrator-ui
- digest: sha256:512c95c195e0c1e63147ec7de5a67ec574828ebec6830da1b84388a21af9f619
  name: ssl-proxy
  newName: 192.168.1.242:5000/ssl-proxy
patches:
- path: ../patches/identity-hostname.yaml
- path: ../patches/schema-migrator-identity.yaml
- path: ../patches/cloudflare-edge.yaml
- path: ../patches/local-config-annotation.yaml
  target:
    kind: ConfigMap
    labelSelector: app.kubernetes.io/component=platform-config
- path: ../patches/proxy.yaml
- path: ../patches/java-coordinator.yaml
- path: ../patches/atheros-search.yaml
- path: ../patches/atheros-sensor.yaml
- path: ../patches/schema-migrator-images.yaml
- path: ../patches/octopus-runtime.yaml
- path: ../patches/keycloak-direct-postgres.yaml
replacements:
- source:
    fieldPath: data.IDENTITY_PUBLIC_ORIGIN
    kind: ConfigMap
    name: ssl-proxy-platform-config
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=keycloak].args.2
    options:
      delimiter: "="
      index: 1
    select:
      kind: Deployment
      name: ssl-proxy-schema-migrator-keycloak
