-- object: octopus_core_ingestion_evidence
-- depends_on: octopus_core_sync_state

USE octopus_core;

CREATE TABLE IF NOT EXISTS ingestion_evidence (
  topic             VARCHAR(255) NOT NULL,
  partition_id      INT NOT NULL,
  record_offset     BIGINT NOT NULL,
  group_id          VARCHAR(128) NOT NULL,
  group_version     VARCHAR(64) NOT NULL,
  artifact_sha256   CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  message_key       VARCHAR(512) DEFAULT NULL,
  payload_sha256    CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  disposition       VARCHAR(32) NOT NULL DEFAULT 'received',
  dedupe_key        VARCHAR(255) DEFAULT NULL,
  first_seen_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (group_id, topic, partition_id, record_offset),
  KEY ingestion_evidence_dedupe_idx (dedupe_key),
  KEY ingestion_evidence_disposition_idx (disposition, updated_at),
  CONSTRAINT ingestion_evidence_disposition_ck CHECK (
    disposition IN ('received', 'duplicate', 'accepted', 'processed', 'rejected', 'failed')
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sync_events (
  dedupe_key     VARCHAR(255) NOT NULL,
  stream_name    VARCHAR(255) NOT NULL,
  observed_at    DATETIME(6) NOT NULL,
  payload_ref    TEXT NOT NULL,
  payload        JSON DEFAULT NULL,
  payload_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  status         VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count  INT NOT NULL DEFAULT 0,
  last_error     TEXT DEFAULT NULL,
  producer       VARCHAR(128) NOT NULL DEFAULT 'unknown',
  event_kind     VARCHAR(64) DEFAULT NULL,
  payload_archive_uri VARCHAR(2048) DEFAULT NULL,
  archived_payload_bytes BIGINT DEFAULT NULL,
  payload_archived_at DATETIME(6) DEFAULT NULL,
  payload_archived TINYINT(1) NOT NULL DEFAULT 0,
  sensor_id      VARCHAR(64) DEFAULT NULL,
  location_id    VARCHAR(128) DEFAULT NULL,
  username       VARCHAR(255) DEFAULT NULL,
  event_type     VARCHAR(64) DEFAULT NULL,
  schema_version INT DEFAULT NULL,
  frame_type     VARCHAR(32) DEFAULT NULL,
  frame_subtype  VARCHAR(64) DEFAULT NULL,
  source_mac     VARCHAR(17) DEFAULT NULL,
  transmitter_mac VARCHAR(17) DEFAULT NULL,
  receiver_mac   VARCHAR(17) DEFAULT NULL,
  bssid          VARCHAR(17) DEFAULT NULL,
  destination_bssid VARCHAR(17) DEFAULT NULL,
  ssid           VARCHAR(256) DEFAULT NULL,
  signal_dbm     INT DEFAULT NULL,
  noise_dbm      INT DEFAULT NULL,
  frequency_mhz  INT DEFAULT NULL,
  channel_flags  INT DEFAULT NULL,
  data_rate_kbps INT DEFAULT NULL,
  antenna_id     INT DEFAULT NULL,
  tsft           BIGINT DEFAULT NULL,
  fragment_number INT DEFAULT NULL,
  channel_number INT DEFAULT NULL,
  signal_status  VARCHAR(64) DEFAULT NULL,
  adjacent_mac_hint VARCHAR(17) DEFAULT NULL,
  qos_tid        INT DEFAULT NULL,
  qos_eosp       TINYINT(1) DEFAULT NULL,
  qos_ack_policy INT DEFAULT NULL,
  qos_ack_policy_label VARCHAR(64) DEFAULT NULL,
  qos_amsdu      TINYINT(1) DEFAULT NULL,
  llc_oui        VARCHAR(16) DEFAULT NULL,
  ethertype      INT DEFAULT NULL,
  ethertype_name VARCHAR(64) DEFAULT NULL,
  src_ip         VARCHAR(45) DEFAULT NULL,
  dst_ip         VARCHAR(45) DEFAULT NULL,
  ip_ttl         INT DEFAULT NULL,
  ip_protocol    INT DEFAULT NULL,
  ip_protocol_name VARCHAR(64) DEFAULT NULL,
  src_port       INT DEFAULT NULL,
  dst_port       INT DEFAULT NULL,
  transport_protocol VARCHAR(32) DEFAULT NULL,
  transport_length INT DEFAULT NULL,
  transport_checksum INT DEFAULT NULL,
  app_protocol   VARCHAR(64) DEFAULT NULL,
  ssdp_message_type VARCHAR(64) DEFAULT NULL,
  ssdp_st        VARCHAR(512) DEFAULT NULL,
  ssdp_mx        VARCHAR(64) DEFAULT NULL,
  ssdp_usn       VARCHAR(512) DEFAULT NULL,
  dhcp_requested_ip VARCHAR(45) DEFAULT NULL,
  dhcp_hostname  VARCHAR(253) DEFAULT NULL,
  dhcp_vendor_class VARCHAR(255) DEFAULT NULL,
  dns_query_name VARCHAR(253) DEFAULT NULL,
  mdns_name      VARCHAR(253) DEFAULT NULL,
  session_key    VARCHAR(255) DEFAULT NULL,
  retransmit_key VARCHAR(255) DEFAULT NULL,
  frame_fingerprint VARCHAR(255) DEFAULT NULL,
  payload_visibility VARCHAR(64) DEFAULT NULL,
  tsft_delta_us  BIGINT DEFAULT NULL,
  wall_clock_delta_ms BIGINT DEFAULT NULL,
  large_frame    TINYINT(1) NOT NULL DEFAULT 0,
  mixed_encryption TINYINT(1) DEFAULT NULL,
  dedupe_or_replay_suspect TINYINT(1) NOT NULL DEFAULT 0,
  raw_len        INT NOT NULL DEFAULT 0,
  frame_control_flags INT NOT NULL DEFAULT 0,
  more_data      TINYINT(1) NOT NULL DEFAULT 0,
  retry          TINYINT(1) NOT NULL DEFAULT 0,
  power_save     TINYINT(1) NOT NULL DEFAULT 0,
  protected      TINYINT(1) NOT NULL DEFAULT 0,
  security_flags INT NOT NULL DEFAULT 0,
  risk_score     DOUBLE DEFAULT NULL,
  identity_source VARCHAR(64) DEFAULT NULL,
  tags           JSON DEFAULT NULL,
  wps_device_name VARCHAR(255) DEFAULT NULL,
  wps_manufacturer VARCHAR(255) DEFAULT NULL,
  wps_model_name VARCHAR(255) DEFAULT NULL,
  device_fingerprint VARCHAR(255) DEFAULT NULL,
  handshake_captured TINYINT(1) NOT NULL DEFAULT 0,
  wireless_search_text TEXT DEFAULT NULL,
  created_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (dedupe_key, stream_name),
  KEY sync_events_status_idx (status, updated_at),
  KEY sync_events_stream_status_idx (stream_name, status, observed_at),
  KEY sync_events_observed_idx (observed_at),
  KEY sync_events_sensor_observed_idx (sensor_id, observed_at),
  KEY sync_events_source_observed_idx (source_mac, observed_at),
  KEY sync_events_bssid_observed_idx (bssid, observed_at),
  KEY sync_events_location_observed_idx (location_id, observed_at),
  CONSTRAINT sync_events_status_ck CHECK (
    status IN ('pending', 'processing', 'batched', 'completed', 'failed')
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sync_event_payload_archives (
  dedupe_key     VARCHAR(255) NOT NULL,
  stream_name    VARCHAR(255) NOT NULL,
  observed_at    DATETIME(6) NOT NULL,
  payload_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  archive_uri    VARCHAR(2048) NOT NULL,
  payload_bytes  BIGINT NOT NULL DEFAULT 0,
  archived_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (dedupe_key, stream_name),
  KEY sync_event_archives_age_idx (archived_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sync_event_tombstones (
  dedupe_key     VARCHAR(255) NOT NULL,
  stream_name    VARCHAR(255) NOT NULL,
  payload_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  observed_at    DATETIME(6) NOT NULL,
  expires_at     DATETIME(6) NOT NULL,
  created_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (dedupe_key, stream_name),
  KEY sync_event_tombstones_expiry_idx (expires_at)
) ENGINE=InnoDB;
