-- object: octopus_core_wireless_sink
-- depends_on: octopus_core_ingestion_evidence
-- These columns preserve the current Octopus sink contract.
-- High-volume facts deliberately have no foreign keys.

USE octopus_core;

CREATE TABLE IF NOT EXISTS wireless_sensors (
  sensor_pk     BIGINT NOT NULL AUTO_INCREMENT,
  sensor_id     VARCHAR(64) NOT NULL,
  location_id   VARCHAR(128) NOT NULL,
  interface     VARCHAR(32) NOT NULL,
  reg_domain    VARCHAR(8) DEFAULT NULL,
  first_seen_at DATETIME(6) NOT NULL,
  last_seen_at  DATETIME(6) NOT NULL,
  created_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (sensor_pk),
  UNIQUE KEY wireless_sensors_id_uq (sensor_id),
  KEY wireless_sensors_location_idx (location_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_audit_frames (
  frame_pk          BIGINT NOT NULL AUTO_INCREMENT,
  batch_id          VARCHAR(128) NOT NULL,
  row_sequence      INT NOT NULL,
  event_type        VARCHAR(64) NOT NULL,
  observed_at       DATETIME(6) NOT NULL,
  sensor_id         VARCHAR(64) NOT NULL,
  location_id       VARCHAR(128) NOT NULL,
  interface         VARCHAR(32) NOT NULL,
  channel           SMALLINT NOT NULL,
  band              VARCHAR(8) NOT NULL,
  frame_type        VARCHAR(32) DEFAULT NULL,
  frame_subtype     VARCHAR(32) NOT NULL,
  bssid             VARCHAR(17) DEFAULT NULL,
  source_mac        VARCHAR(17) DEFAULT NULL,
  destination_mac   VARCHAR(17) DEFAULT NULL,
  transmitter_mac   VARCHAR(17) DEFAULT NULL,
  receiver_mac      VARCHAR(17) DEFAULT NULL,
  destination_bssid VARCHAR(17) DEFAULT NULL,
  ssid              VARCHAR(256) DEFAULT NULL,
  signal_dbm        SMALLINT DEFAULT NULL,
  sequence_number   INT DEFAULT NULL,
  raw_len           INT NOT NULL,
  is_retry          TINYINT(1) NOT NULL DEFAULT 0,
  is_more_data      TINYINT(1) NOT NULL DEFAULT 0,
  is_power_save     TINYINT(1) NOT NULL DEFAULT 0,
  is_protected      TINYINT(1) NOT NULL DEFAULT 0,
  is_to_ds          TINYINT(1) NOT NULL DEFAULT 0,
  is_from_ds        TINYINT(1) NOT NULL DEFAULT 0,
  is_handshake      TINYINT(1) NOT NULL DEFAULT 0,
  security_flags    INT NOT NULL DEFAULT 0,
  device_id         VARCHAR(128) DEFAULT NULL,
  username          VARCHAR(256) DEFAULT NULL,
  identity_source   VARCHAR(64) NOT NULL DEFAULT 'unknown',
  tags              VARCHAR(2000) DEFAULT NULL,
  anomaly_reasons   VARCHAR(1000) DEFAULT NULL,
  raw_json          JSON DEFAULT NULL,
  created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (frame_pk),
  UNIQUE KEY wireless_audit_frames_batch_uq (batch_id, row_sequence),
  KEY wireless_audit_frames_sensor_idx (sensor_id, observed_at),
  KEY wireless_audit_frames_location_idx (location_id, observed_at),
  KEY wireless_audit_frames_source_idx (source_mac, observed_at),
  KEY wireless_audit_frames_bssid_idx (bssid, observed_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_bandwidth_windows (
  bw_pk                BIGINT NOT NULL AUTO_INCREMENT,
  batch_id             VARCHAR(128) NOT NULL,
  row_sequence         INT NOT NULL,
  schema_version       SMALLINT NOT NULL DEFAULT 1,
  window_start         DATETIME(6) NOT NULL,
  window_end           DATETIME(6) NOT NULL,
  sensor_id            VARCHAR(64) NOT NULL,
  location_id          VARCHAR(128) NOT NULL,
  interface            VARCHAR(32) NOT NULL,
  channel              SMALLINT NOT NULL,
  band                 VARCHAR(8) NOT NULL,
  source_mac           VARCHAR(17) NOT NULL,
  destination_bssid    VARCHAR(17) NOT NULL,
  ssid                 VARCHAR(256) DEFAULT NULL,
  bytes                BIGINT NOT NULL DEFAULT 0,
  frame_count          BIGINT NOT NULL DEFAULT 0,
  retry_count          BIGINT NOT NULL DEFAULT 0,
  more_data_count      BIGINT NOT NULL DEFAULT 0,
  power_save_count     BIGINT NOT NULL DEFAULT 0,
  strongest_signal_dbm SMALLINT DEFAULT NULL,
  hist_under_100       BIGINT NOT NULL DEFAULT 0,
  hist_100_500         BIGINT NOT NULL DEFAULT 0,
  hist_500_1000        BIGINT NOT NULL DEFAULT 0,
  hist_1000_1500       BIGINT NOT NULL DEFAULT 0,
  inter_arrival_p50_ms INT DEFAULT NULL,
  external_bssid       TINYINT(1) NOT NULL DEFAULT 0,
  threshold_exceeded   TINYINT(1) NOT NULL DEFAULT 0,
  wall_clock_delta_ms  BIGINT DEFAULT NULL,
  window_is_partial    TINYINT(1) NOT NULL DEFAULT 0,
  published_at         DATETIME(6) DEFAULT NULL,
  created_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (bw_pk),
  UNIQUE KEY wireless_bandwidth_windows_batch_uq (batch_id, row_sequence),
  KEY wireless_bandwidth_windows_sensor_idx (sensor_id, window_start),
  KEY wireless_bandwidth_windows_threshold_idx (threshold_exceeded, window_start),
  KEY wireless_bandwidth_windows_source_idx (source_mac, window_start),
  CONSTRAINT wireless_bandwidth_windows_range_ck CHECK (window_end >= window_start)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_alerts (
  alert_pk        BIGINT NOT NULL AUTO_INCREMENT,
  alert_type      VARCHAR(64) NOT NULL,
  batch_id        VARCHAR(128) DEFAULT NULL,
  row_sequence    INT DEFAULT NULL,
  alert_date      DATE DEFAULT NULL,
  detected_at     DATETIME(6) NOT NULL,
  sensor_id       VARCHAR(64) NOT NULL,
  location_id     VARCHAR(128) NOT NULL,
  interface       VARCHAR(32) DEFAULT NULL,
  channel         SMALLINT DEFAULT NULL,
  primary_mac     VARCHAR(17) DEFAULT NULL,
  secondary_mac   VARCHAR(17) DEFAULT NULL,
  ssid            VARCHAR(256) DEFAULT NULL,
  signal_dbm      SMALLINT DEFAULT NULL,
  bytes           BIGINT DEFAULT NULL,
  details_json    JSON DEFAULT NULL,
  raw_json        JSON DEFAULT NULL,
  acknowledged    TINYINT(1) NOT NULL DEFAULT 0,
  acknowledged_by VARCHAR(128) DEFAULT NULL,
  acknowledged_at DATETIME(6) DEFAULT NULL,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (alert_pk),
  UNIQUE KEY wireless_alerts_batch_uq (alert_type, batch_id, row_sequence),
  KEY wireless_alerts_type_idx (alert_type, detected_at),
  KEY wireless_alerts_sensor_idx (sensor_id, detected_at),
  KEY wireless_alerts_unack_idx (acknowledged, detected_at),
  KEY wireless_alerts_day_idx (
    alert_type, sensor_id, primary_mac, secondary_mac, alert_date
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_alerts_ledger (
  ledger_id      BIGINT NOT NULL AUTO_INCREMENT,
  alert_pk       BIGINT NOT NULL,
  alert_type     VARCHAR(64) NOT NULL,
  batch_id       VARCHAR(128) DEFAULT NULL,
  row_sequence   INT DEFAULT NULL,
  alert_date     DATE DEFAULT NULL,
  detected_at    DATETIME(6) NOT NULL,
  sensor_id      VARCHAR(64) NOT NULL,
  location_id    VARCHAR(128) NOT NULL,
  interface      VARCHAR(32) DEFAULT NULL,
  channel        SMALLINT DEFAULT NULL,
  primary_mac    VARCHAR(17) DEFAULT NULL,
  secondary_mac  VARCHAR(17) DEFAULT NULL,
  ssid           VARCHAR(256) DEFAULT NULL,
  signal_dbm     SMALLINT DEFAULT NULL,
  bytes          BIGINT DEFAULT NULL,
  details_json   JSON DEFAULT NULL,
  raw_json       JSON DEFAULT NULL,
  acknowledged   TINYINT(1) NOT NULL,
  ledger_action  VARCHAR(16) NOT NULL,
  captured_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ledger_id),
  KEY wireless_alerts_ledger_alert_idx (alert_pk, captured_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_client_inventory (
  inventory_pk    BIGINT NOT NULL AUTO_INCREMENT,
  sensor_id       VARCHAR(64) NOT NULL,
  location_id     VARCHAR(128) NOT NULL,
  snapshot_at     DATETIME(6) NOT NULL,
  client_mac      VARCHAR(17) NOT NULL,
  bssid           VARCHAR(17) DEFAULT NULL,
  ssid            VARCHAR(256) DEFAULT NULL,
  device_id       VARCHAR(128) DEFAULT NULL,
  username        VARCHAR(256) DEFAULT NULL,
  identity_source VARCHAR(64) DEFAULT NULL,
  last_seen       DATETIME(6) NOT NULL,
  first_seen      DATETIME(6) NOT NULL,
  signal_dbm      SMALLINT DEFAULT NULL,
  is_authorized   TINYINT(1) NOT NULL DEFAULT 0,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (inventory_pk),
  UNIQUE KEY wireless_client_inventory_snapshot_uq (
    sensor_id, snapshot_at, client_mac
  ),
  KEY wireless_client_inventory_mac_idx (client_mac, snapshot_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wireless_probe_requests (
  probe_pk     BIGINT NOT NULL AUTO_INCREMENT,
  batch_id     VARCHAR(128) NOT NULL,
  row_sequence INT NOT NULL,
  client_mac   VARCHAR(17) NOT NULL,
  ssid         VARCHAR(256) NOT NULL,
  known_bssid  VARCHAR(17) DEFAULT NULL,
  first_seen   DATETIME(6) NOT NULL,
  last_seen    DATETIME(6) NOT NULL,
  probe_count  INT NOT NULL DEFAULT 1,
  created_at   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (probe_pk),
  UNIQUE KEY wireless_probe_requests_batch_uq (batch_id, row_sequence),
  KEY wireless_probe_requests_mac_idx (client_mac, last_seen),
  KEY wireless_probe_requests_ssid_idx (ssid, last_seen)
) ENGINE=InnoDB;
