{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy-common.fullname" (dict "root" . "component" "minio") }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy-common.labels" (dict "root" . "component" "minio") | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  selector:
    {{- include "ssl-proxy-common.selectorLabels" (dict "root" . "component" "minio") | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
{{- end }}
