apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-ssl-proxy
resources:
  - ../../../base/redpanda/statefulset.yaml
  - ../../../base/minio/statefulset.yaml
  - ../../../base/redis-runtime/deployment.yaml
  - ../../../base/tidb-schema-executor
  - ../../../base/telemetry/prometheus.yaml
  - ../../../base/telemetry/prometheus-configmap.yaml
  - ../../../base/telemetry/grafana.yaml
  - ../../../base/telemetry/grafana-configmaps.yaml
  - ../../../base/telemetry/loki.yaml
  - ../../../base/telemetry/loki-configmap.yaml
  - ../../../base/telemetry/promtail.yaml
  - ../../../base/telemetry/promtail-configmap.yaml
  - ../../../base/telemetry/jaeger.yaml
  - ../../../base/telemetry/otel-collector.yaml
  - ../../../base/telemetry/otel-collector-configmap.yaml
  - ../../../base/telemetry/node-exporter.yaml
  - ../../../base/telemetry/cadvisor.yaml
  - ../../../base/telemetry/pushgateway.yaml
images:
  - name: tidb-runtime-schema
    newName: 192.168.1.221:5000/tidb-runtime-schema
    digest: sha256:6d0352c5505a8bfae3da326c4024417c08a5a17f5e16c07ee9e461757aac77a8
patches:
  - path: ../patches/alloy-positions.yaml
  - path: ../patches/jaeger-recovery.yaml
  - target:
      kind: Job
      name: ssl-proxy-tidb-schema-executor
    patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/ssl-proxy.io~1content-hash
        value: schema-migrator-001-10abd5b1ef8462fe4f521e064fc16193e50dec2cf508db34a4b32a9acc59f703
