apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssl-proxy
resources:
  - deployment.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: ssl-proxy-atheros-search-ui-nginx
    files:
      - default.conf=nginx-default
    options:
      labels:
        app.kubernetes.io/name: ssl-proxy
        app.kubernetes.io/component: atheros-search-ui
        app.kubernetes.io/managed-by: kustomize
