apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssl-proxy-atheros-search
  namespace: ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: atheros-search
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ssl-proxy
      app.kubernetes.io/component: atheros-search
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: atheros-search-ui
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: telemetry-prometheus
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: telemetry-blackbox-exporter
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: telemetry-prometheus
      ports:
        - protocol: TCP
          port: 9090
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 50051
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssl-proxy-atheros-search-ui
  namespace: ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: atheros-search-ui
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ssl-proxy
      app.kubernetes.io/component: atheros-search-ui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: telemetry-prometheus
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: telemetry-blackbox-exporter
      ports:
        - protocol: TCP
          port: 8080
