apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: ssl-proxy
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
resources:
  # Platform config
  - platform-config/serviceaccount.yaml
  - platform-config/configmap.yaml
  # Proxy
  - proxy/deployment.yaml
  - proxy/service.yaml
  # Java coordinator
  - java-coordinator/deployment.yaml
  # Schema migrator
  - schema-migrator
  # Atheros sensor
  - atheros-sensor/daemonset.yaml
  # Atheros search
  - atheros-search
  # Redis
  - redis-runtime/deployment.yaml
  # PostgreSQL
  # Redpanda
  - redpanda/statefulset.yaml
  # MinIO
  - minio/statefulset.yaml
  # PostgreSQL schema executor
  - pgbouncer
  - postgres-schema-executor
  # Telemetry
  - telemetry
configurations:
  - schema-migrator/kustomizeconfig.yaml
vars:
  - name: IDENTITY_HOSTNAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: ssl-proxy-platform-config
    fieldref:
      fieldpath: data.IDENTITY_HOSTNAME
