apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://ssl-proxy-telemetry-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://ssl-proxy-telemetry-loki:3100
    basicAuth: true
    basicAuthUser: $LOKI_USERNAME
    editable: false
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      derivedFields:
        - name: trace_id
          matcherRegex: '(?:trace_id|traceId)[=:" ]+([a-fA-F0-9]{32})'
          datasourceUid: jaeger
          url: '$${__value.raw}'
    secureJsonData:
      basicAuthPassword: $LOKI_PASSWORD
      httpHeaderValue1: ssl-proxy
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://ssl-proxy-telemetry-jaeger:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        tags: [service.name, deployment.environment]
        filterByTraceID: true
        filterBySpanID: true
