apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssl-proxy-platform-sync
  namespace: prod-ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: platform-sync
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
