package com.sslproxy.schema.db.oracle

object OracleStatements:
  val tableSchemaObjects: String =
    """
    create table schema_control.schema_objects (
      id number generated by default as identity,
      kind varchar2(64) not null,
      object_name varchar2(256) not null,
      source_file varchar2(512) not null,
      depends_on clob,
      rollback_file varchar2(512),
      canonical_sql clob not null,
      content_sha256 varchar2(64) not null,
      applied_at timestamp with time zone,
      apply_status varchar2(16) default 'pending' not null,
      last_error clob,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint schema_objects_pk primary key (id),
      constraint schema_objects_unique unique (kind, object_name),
      constraint schema_objects_status_chk check (apply_status in ('pending', 'applied', 'failed', 'skipped'))
    )
    """

  val tableApplyLog: String =
    """
    create table schema_control.schema_apply_log (
      log_id number generated by default as identity,
      kind varchar2(64) not null,
      object_name varchar2(256) not null,
      source_file varchar2(512) not null,
      action varchar2(32) not null,
      old_sha256 varchar2(64),
      new_sha256 varchar2(64),
      duration_ms number(10),
      error_text clob,
      applied_by varchar2(128),
      applied_at timestamp with time zone default systimestamp not null,
      constraint schema_apply_log_pk primary key (log_id)
    )
    """

  val tableMigrationLocks: String =
    """
    create table schema_control.migration_locks (
      lock_name varchar2(128) primary key,
      locked_at timestamp with time zone not null,
      locked_by varchar2(128) not null
    )
    """

  val viewSchemaReady: String =
    """
    create or replace view schema_control.schema_ready as
    select
      systimestamp as measured_at,
      count(*) as total_count,
      sum(case when apply_status = 'pending' then 1 else 0 end) as pending_count,
      sum(case when apply_status = 'failed' then 1 else 0 end) as failed_count,
      sum(case when apply_status in ('applied', 'skipped') then 1 else 0 end) as applied_count,
      case
        when count(*) > 0
         and sum(case when apply_status not in ('applied', 'skipped') then 1 else 0 end) = 0
         and sum(case when apply_status = 'failed' then 1 else 0 end) = 0
        then '1' else '0'
      end as ready,
      listagg(case when apply_status = 'failed' then kind || ':' || object_name end, ',' on overflow truncate '...')
        within group (order by kind, object_name) as failed_objects,
      max(updated_at) as last_updated_at,
      max(applied_at) as last_applied_at
    from schema_control.schema_objects
    """

  val bootstrapBlocks: List[String] =
    List(tableSchemaObjects, tableApplyLog, tableMigrationLocks, viewSchemaReady)

  val prepareSql: String =
    """
    merge into schema_control.schema_objects target
    using (
      select ? kind, ? object_name, ? source_file, ? depends_on, ? rollback_file,
             ? canonical_sql, ? content_sha256, ? apply_status
      from dual
    ) source
    on (target.kind = source.kind and target.object_name = source.object_name)
    when matched then update set
      target.source_file = source.source_file,
      target.depends_on = source.depends_on,
      target.rollback_file = source.rollback_file,
      target.canonical_sql = source.canonical_sql,
      target.content_sha256 = source.content_sha256,
      target.applied_at = case when source.apply_status = 'pending' then null else coalesce(target.applied_at, systimestamp) end,
      target.apply_status = source.apply_status,
      target.last_error = null,
      target.updated_at = systimestamp
    when not matched then insert (
      kind, object_name, source_file, depends_on, rollback_file, canonical_sql, content_sha256,
      applied_at, apply_status, last_error, updated_at
    ) values (
      source.kind, source.object_name, source.source_file, source.depends_on, source.rollback_file,
      source.canonical_sql, source.content_sha256,
      case when source.apply_status = 'pending' then null else systimestamp end,
      source.apply_status, null, systimestamp
    )
    """

  val applyLogSql: String =
    """
    insert into schema_control.schema_apply_log (
      kind, object_name, source_file, action, old_sha256, new_sha256,
      duration_ms, error_text, applied_by
    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """

  val updateStatusSql: String =
    """
    update schema_control.schema_objects
       set apply_status = ?,
           applied_at = systimestamp,
           last_error = ?,
           updated_at = systimestamp
     where kind = ? and object_name = ?
    """

  val rollbackStatusSql: String =
    """
    update schema_control.schema_objects
       set apply_status = 'pending',
           applied_at = null,
           last_error = null,
           updated_at = systimestamp
     where kind = ? and object_name = ?
    """

  val fetchStatusSql: String =
    """
    select kind, object_name, source_file, apply_status,
           content_sha256,
           to_char(applied_at, 'YYYY-MM-DD HH24:MI:SS') as applied_at,
           dbms_lob.substr(last_error, 4000, 1) as last_error
      from schema_control.schema_objects
     order by kind, object_name
    """

  val fetchReadySql: String =
    """
    select total_count, pending_count, failed_count, applied_count, ready,
           failed_objects,
           to_char(last_updated_at, 'YYYY-MM-DD HH24:MI:SS') as last_updated_at,
           to_char(last_applied_at, 'YYYY-MM-DD HH24:MI:SS') as last_applied_at
      from schema_control.schema_ready
    """

  val fetchRollbackTargetSql: String =
    """
    select kind, object_name, source_file, content_sha256, rollback_file
      from schema_control.schema_objects
     where object_name = ?
     order by kind, object_name
    """

  val lockAcquireSql: String =
    """
    insert into schema_control.migration_locks (lock_name, locked_at, locked_by)
    values ('schema_migrate', systimestamp, ?)
    """

  val lockDeleteSql: String =
    "delete from schema_control.migration_locks where lock_name = 'schema_migrate'"

  val lockQueryStaleSql: String =
    """
    select case when locked_at < systimestamp - numtodsinterval(10, 'MINUTE') then 1 else 0 end as stale
      from schema_control.migration_locks
     where lock_name = 'schema_migrate'
    """

  val lockQueryInfoSql: String =
    """
    select locked_by, to_char(locked_at, 'YYYY-MM-DD HH24:MI:SS TZR') as locked_at_char
      from schema_control.migration_locks
     where lock_name = 'schema_migrate'
    """