-- object: proxy_blocked_host_rollups
-- depends_on:

CREATE TABLE IF NOT EXISTS PROXY_BLOCKED_HOST_ROLLUPS (
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    HOST               VARCHAR(253) NOT NULL,
    BLOCKED_ATTEMPTS   BIGINT       DEFAULT 0 NOT NULL,
    BLOCKED_BYTES      BIGINT       DEFAULT 0 NOT NULL,
    FREQUENCY_HZ       DECIMAL(10,4) DEFAULT 0 NOT NULL,
    VERDICT            VARCHAR(32)  NOT NULL,
    CATEGORY           VARCHAR(64)  DEFAULT NULL,
    RISK_SCORE         DECIMAL(10,4) DEFAULT 0,
    TARPIT_HELD_MS     BIGINT       DEFAULT 0,
    IAT_MS             BIGINT       DEFAULT NULL,
    CONSECUTIVE_BLOCKS INT          DEFAULT 0,
    LAST_VERDICT       VARCHAR(32)  DEFAULT NULL,
    TLS_VER            VARCHAR(16)  DEFAULT NULL,
    ALPN               VARCHAR(64)  DEFAULT NULL,
    JA3_LITE           VARCHAR(512) DEFAULT NULL,
    RESOLVED_IP        VARCHAR(45)  DEFAULT NULL,
    ASN_ORG            VARCHAR(128) DEFAULT NULL,
    UPDATED_AT         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    FIRST_SEEN         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE KEY PROXY_BLOCKED_HOST_UQ (HOST),
    KEY PROXY_BLOCKED_UPDATED_IDX (UPDATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
