-- object: proxy_payload_audit
-- depends_on:

CREATE TABLE IF NOT EXISTS PROXY_PAYLOAD_AUDIT (
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    CORRELATION_ID     BINARY(16)   NOT NULL,
    HOST               VARCHAR(253) NOT NULL,
    DIRECTION          VARCHAR(4)   NOT NULL COMMENT 'UP or DOWN',
    CAPTURED_AT        DATETIME(6)  NOT NULL,
    BYTE_OFFSET        INT          DEFAULT 0 NOT NULL,
    PAYLOAD_OBJECT_KEY VARCHAR(512) DEFAULT NULL,
    CONTENT_TYPE       VARCHAR(128) DEFAULT NULL,
    HTTP_METHOD        VARCHAR(16)  DEFAULT NULL,
    HTTP_STATUS        INT          DEFAULT NULL,
    HTTP_PATH          VARCHAR(1024) DEFAULT NULL,
    IS_ENCRYPTED       TINYINT(1)   DEFAULT 0 NOT NULL,
    TRUNCATED          TINYINT(1)   DEFAULT 0 NOT NULL,
    PEER_IP            VARCHAR(45)  DEFAULT NULL,
    NOTES              VARCHAR(512) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY PROXY_PAYLOAD_AUDIT_UQ (CORRELATION_ID, HOST, DIRECTION, CAPTURED_AT, BYTE_OFFSET),
    KEY PROXY_PAYLOAD_CORR_IDX (CORRELATION_ID),
    KEY PROXY_PAYLOAD_HOST_IDX (HOST, CAPTURED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
