-- object: wireless_sensors
-- depends_on:

CREATE TABLE IF NOT EXISTS WIRELESS_SENSORS (
    SENSOR_PK     BIGINT       NOT NULL AUTO_INCREMENT,
    SENSOR_ID     VARCHAR(64)  NOT NULL,
    LOCATION_ID   VARCHAR(128) NOT NULL,
    INTERFACE     VARCHAR(32)  NOT NULL,
    REG_DOMAIN    VARCHAR(8)   DEFAULT NULL,
    FIRST_SEEN_AT TIMESTAMP(6) NOT NULL,
    LAST_SEEN_AT  TIMESTAMP(6) NOT NULL,
    CREATED_AT    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (SENSOR_PK),
    UNIQUE KEY WIRELESS_SENSORS_ID_UQ (SENSOR_ID),
    KEY WIRELESS_SENSORS_LOCATION_IDX (LOCATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
