-- object: wireless_alerts
-- depends_on:

CREATE TABLE IF NOT EXISTS WIRELESS_ALERTS (
    ALERT_PK        BIGINT       NOT NULL AUTO_INCREMENT,
    ALERT_TYPE      VARCHAR(64)  NOT NULL,
    BATCH_ID        VARCHAR(128) DEFAULT NULL,
    ROW_SEQUENCE    INT          DEFAULT NULL,
    ALERT_DATE      DATE         DEFAULT NULL,
    DETECTED_AT     TIMESTAMP(6) NOT NULL,
    SENSOR_ID       VARCHAR(64)  NOT NULL,
    LOCATION_ID     VARCHAR(128) NOT NULL,
    INTERFACE       VARCHAR(32)  DEFAULT NULL,
    CHANNEL         SMALLINT     DEFAULT NULL,
    PRIMARY_MAC     VARCHAR(17)  DEFAULT NULL,
    SECONDARY_MAC   VARCHAR(17)  DEFAULT NULL,
    SSID            VARCHAR(256) DEFAULT NULL,
    SIGNAL_DBM      SMALLINT     DEFAULT NULL,
    BYTES           BIGINT       DEFAULT NULL,
    DETAILS_JSON    JSON         DEFAULT NULL,
    RAW_JSON        JSON         DEFAULT NULL,
    ACKNOWLEDGED    TINYINT(1)   DEFAULT 0 NOT NULL,
    ACKNOWLEDGED_BY VARCHAR(128) DEFAULT NULL,
    ACKNOWLEDGED_AT TIMESTAMP(6) DEFAULT NULL,
    CREATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ALERT_PK),
    UNIQUE KEY WIRELESS_ALERTS_BATCH_UQ (ALERT_TYPE, BATCH_ID, ROW_SEQUENCE),
    KEY WIRELESS_ALERTS_TYPE_TIME_IDX (ALERT_TYPE, DETECTED_AT DESC),
    KEY WIRELESS_ALERTS_SENSOR_TIME_IDX (SENSOR_ID, DETECTED_AT DESC),
    KEY WIRELESS_ALERTS_UNACK_IDX (ACKNOWLEDGED, DETECTED_AT DESC),
    KEY WIRELESS_BW_ALERT_DAY_IDX (ALERT_TYPE, SENSOR_ID, PRIMARY_MAC, SECONDARY_MAC, ALERT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
