-- object: wireless_alerts_ledger
-- depends_on:

CREATE TABLE IF NOT EXISTS WIRELESS_ALERTS_LEDGER (
    LEDGER_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    ALERT_PK       BIGINT       NOT NULL,
    ALERT_TYPE     VARCHAR(64)  NOT NULL,
    BATCH_ID       VARCHAR(128) DEFAULT NULL,
    ROW_SEQUENCE   INT          DEFAULT NULL,
    ALERT_DATE     DATE         DEFAULT NULL,
    DETECTED_AT    TIMESTAMP(6) NOT NULL,
    SENSOR_ID      VARCHAR(64)  NOT NULL,
    LOCATION_ID    VARCHAR(128) NOT NULL,
    INTERFACE      VARCHAR(32)  DEFAULT NULL,
    CHANNEL        SMALLINT     DEFAULT NULL,
    PRIMARY_MAC    VARCHAR(17)  DEFAULT NULL,
    SECONDARY_MAC  VARCHAR(17)  DEFAULT NULL,
    SSID           VARCHAR(256) DEFAULT NULL,
    SIGNAL_DBM     SMALLINT     DEFAULT NULL,
    BYTES          BIGINT       DEFAULT NULL,
    DETAILS_JSON   JSON         DEFAULT NULL,
    RAW_JSON       JSON         DEFAULT NULL,
    ACKNOWLEDGED   TINYINT(1)   NOT NULL,
    LEDGER_ACTION  VARCHAR(16)  NOT NULL,
    CAPTURED_AT    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (LEDGER_ID),
    KEY WIRELESS_ALERTS_LEDGER_ALERT_IDX (ALERT_PK, CAPTURED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
