-- object: wireless_client_inventory
-- depends_on:

CREATE TABLE IF NOT EXISTS WIRELESS_CLIENT_INVENTORY (
    INVENTORY_PK    BIGINT       NOT NULL AUTO_INCREMENT,
    SENSOR_ID       VARCHAR(64)  NOT NULL,
    LOCATION_ID     VARCHAR(128) NOT NULL,
    SNAPSHOT_AT     TIMESTAMP(6) NOT NULL,
    CLIENT_MAC      VARCHAR(17)  NOT NULL,
    BSSID           VARCHAR(17)  DEFAULT NULL,
    SSID            VARCHAR(256) DEFAULT NULL,
    DEVICE_ID       VARCHAR(128) DEFAULT NULL,
    USERNAME        VARCHAR(256) DEFAULT NULL,
    IDENTITY_SOURCE VARCHAR(64)  DEFAULT NULL,
    LAST_SEEN       TIMESTAMP(6) NOT NULL,
    FIRST_SEEN      TIMESTAMP(6) NOT NULL,
    SIGNAL_DBM      SMALLINT     DEFAULT NULL,
    IS_AUTHORIZED   TINYINT(1)   DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (INVENTORY_PK),
    UNIQUE KEY WIRELESS_CLIENT_INV_UQ (SENSOR_ID, SNAPSHOT_AT, CLIENT_MAC),
    KEY WIRELESS_INV_SENSOR_SNAP_IDX (SENSOR_ID, SNAPSHOT_AT),
    KEY WIRELESS_INV_CLIENT_MAC_IDX (CLIENT_MAC, SNAPSHOT_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
