-- object: wireless_probe_requests
-- depends_on:

CREATE TABLE IF NOT EXISTS WIRELESS_PROBE_REQUESTS (
    PROBE_PK    BIGINT       NOT NULL AUTO_INCREMENT,
    BATCH_ID    VARCHAR(128) NOT NULL,
    CLIENT_MAC  VARCHAR(17)  NOT NULL,
    SSID        VARCHAR(256) NOT NULL,
    KNOWN_BSSID VARCHAR(17)  DEFAULT NULL,
    FIRST_SEEN  TIMESTAMP(6) NOT NULL,
    LAST_SEEN   TIMESTAMP(6) NOT NULL,
    PROBE_COUNT INT          DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (PROBE_PK),
    UNIQUE KEY WIRELESS_PROBE_BATCH_UQ (BATCH_ID, CLIENT_MAC, SSID),
    KEY WIRELESS_PROBES_CLIENT_MAC_IDX (CLIENT_MAC, LAST_SEEN),
    KEY WIRELESS_PROBES_SSID_IDX (SSID, LAST_SEEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
