{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy-common.fullname" (dict "root" . "component" "atherosSensor") }}-atheros-sensor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy-common.labels" (dict "root" . "component" "atherosSensor") | nindent 4 }}
    app.kubernetes.io/component: atheros-sensor
spec:
  clusterIP: None
  selector:
    {{- include "ssl-proxy-common.selectorLabels" (dict "root" . "component" "atherosSensor") | nindent 4 }}
    app.kubernetes.io/component: atheros-sensor
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
{{- end }}

