-- object: wireless_frames_expanded
-- folder: views
-- depends_on: wireless_frames, wireless_frame_radio, wireless_frame_qos, wireless_frame_network, wireless_frame_app_signals, wireless_frame_identity, wireless_frame_security
create or replace view wireless_frames_expanded as
select
  core.dedupe_key,
  core.sensor_id,
  core.location_id,
  identity.username,
  identity.event_type,
  core.schema_version,
  core.frame_type,
  core.frame_subtype,
  core.source_mac,
  core.transmitter_mac,
  core.receiver_mac,
  core.bssid,
  core.destination_bssid,
  core.bssid_oui,
  core.ssid,
  radio.signal_dbm,
  radio.noise_dbm,
  radio.frequency_mhz,
  radio.channel_flags,
  radio.data_rate_kbps,
  radio.antenna_id,
  radio.tsft,
  radio.fragment_number,
  radio.channel_number,
  security.signal_status,
  security.adjacent_mac_hint,
  qos.qos_tid,
  qos.qos_eosp,
  qos.qos_ack_policy,
  qos.qos_ack_policy_label,
  qos.qos_amsdu,
  network.llc_oui,
  network.ethertype,
  network.ethertype_name,
  network.src_ip,
  network.dst_ip,
  network.ip_ttl,
  network.ip_protocol,
  network.ip_protocol_name,
  network.src_port,
  network.dst_port,
  network.transport_protocol,
  network.transport_length,
  network.transport_checksum,
  network.app_protocol,
  app.ssdp_message_type,
  app.ssdp_st,
  app.ssdp_mx,
  app.ssdp_usn,
  app.dhcp_requested_ip,
  app.dhcp_hostname,
  app.dhcp_vendor_class,
  app.dns_query_name,
  app.mdns_name,
  identity.session_key,
  identity.retransmit_key,
  identity.frame_fingerprint,
  identity.payload_visibility,
  radio.tsft_delta_us,
  radio.wall_clock_delta_ms,
  security.large_frame,
  security.mixed_encryption,
  security.dedupe_or_replay_suspect,
  security.raw_len,
  qos.frame_control_flags,
  qos.more_data,
  qos.retry,
  qos.power_save,
  qos.protected,
  security.security_flags,
  security.risk_score,
  identity.identity_source,
  security.tags,
  identity.wps_device_name,
  identity.wps_manufacturer,
  identity.wps_model_name,
  identity.device_fingerprint,
  identity.handshake_captured,
  identity.search_tsv,
  core.created_at,
  core.updated_at
from wireless_frames core
left join wireless_frame_radio radio using (dedupe_key)
left join wireless_frame_qos qos using (dedupe_key)
left join wireless_frame_network network using (dedupe_key)
left join wireless_frame_app_signals app using (dedupe_key)
left join wireless_frame_identity identity using (dedupe_key)
left join wireless_frame_security security using (dedupe_key);
