-- object: sync_events_expanded
-- folder: views
-- depends_on: sync_events, wireless_frames, sync_event_payload_archives
-- CREATE OR REPLACE cannot insert columns mid-list; dependents are recreated below.
drop view if exists sync_events_expanded cascade;

create view sync_events_expanded as
select
  e.dedupe_key,
  e.stream_name,
  e.observed_at,
  e.payload_ref,
  e.payload,
  e.payload_sha256,
  archive.archive_uri as payload_archive_uri,
  archive.payload_bytes as archived_payload_bytes,
  archive.archived_at as payload_archived_at,
  (archive.dedupe_key is not null and e.payload is null) as payload_archived,
  e.status,
  e.attempt_count,
  e.last_error,
  e.producer,
  e.event_kind,
  f.sensor_id,
  f.location_id,
  f.username,
  f.event_type,
  f.schema_version,
  f.frame_type,
  f.frame_subtype,
  f.source_mac,
  f.transmitter_mac,
  f.receiver_mac,
  f.bssid,
  f.destination_bssid,
  f.ssid,
  f.signal_dbm,
  f.noise_dbm,
  f.frequency_mhz,
  f.channel_flags,
  f.data_rate_kbps,
  f.antenna_id,
  f.tsft,
  f.fragment_number,
  f.channel_number,
  f.signal_status,
  f.adjacent_mac_hint,
  f.qos_tid,
  f.qos_eosp,
  f.qos_ack_policy,
  f.qos_ack_policy_label,
  f.qos_amsdu,
  f.llc_oui,
  f.ethertype,
  f.ethertype_name,
  f.src_ip,
  f.dst_ip,
  f.ip_ttl,
  f.ip_protocol,
  f.ip_protocol_name,
  f.src_port,
  f.dst_port,
  f.transport_protocol,
  f.transport_length,
  f.transport_checksum,
  f.app_protocol,
  f.ssdp_message_type,
  f.ssdp_st,
  f.ssdp_mx,
  f.ssdp_usn,
  f.dhcp_requested_ip,
  f.dhcp_hostname,
  f.dhcp_vendor_class,
  f.dns_query_name,
  f.mdns_name,
  f.session_key,
  f.retransmit_key,
  f.frame_fingerprint,
  f.payload_visibility,
  f.tsft_delta_us,
  f.wall_clock_delta_ms,
  f.large_frame,
  f.mixed_encryption,
  f.dedupe_or_replay_suspect,
  f.raw_len,
  f.frame_control_flags,
  f.more_data,
  f.retry,
  f.power_save,
  f.protected,
  f.security_flags,
  f.risk_score,
  f.identity_source,
  f.tags,
  f.wps_device_name,
  f.wps_manufacturer,
  f.wps_model_name,
  f.device_fingerprint,
  f.handshake_captured,
  f.search_tsv as wireless_search_tsv,
  e.created_at,
  greatest(e.updated_at, coalesce(f.updated_at, e.updated_at)) as updated_at
from sync_events e
left join wireless_frames f on f.dedupe_key = e.dedupe_key
left join sync_event_payload_archives archive on archive.dedupe_key = e.dedupe_key;
