apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssl-proxy
  namespace: ssl-proxy
  labels:
    app.kubernetes.io/name: ssl-proxy
    app.kubernetes.io/component: platform-config
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
