PROMPT [ssl-proxy] starting nuclear drop

DECLARE
  v_db_name VARCHAR2(128);
BEGIN
  v_db_name := UPPER(SYS_CONTEXT('USERENV', 'DB_NAME'));
  IF v_db_name NOT LIKE '%DEV%'
     AND v_db_name NOT LIKE '%TEST%'
     AND v_db_name NOT LIKE '%LOCAL%'
     AND v_db_name NOT LIKE '%XE%'
     AND v_db_name NOT LIKE '%FREE%' THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'Refusing nuclear drop outside a non-production environment. DB_NAME=' || v_db_name
    );
  END IF;
  DBMS_OUTPUT.PUT_LINE('Environment safety check passed for DB_NAME=' || v_db_name);
END;
/

PROMPT [1/8] dropping scheduler jobs
BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_REFRESH_MVS', TRUE);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-27475, -27476) THEN
      DBMS_OUTPUT.PUT_LINE('JOB_REFRESH_MVS already absent: ' || SQLERRM);
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop JOB_REFRESH_MVS: ' || SQLERRM);
      RAISE;
    END IF;
END;
/
BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_PURGE_OLD_EVENTS', TRUE);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-27475, -27476) THEN
      DBMS_OUTPUT.PUT_LINE('JOB_PURGE_OLD_EVENTS already absent: ' || SQLERRM);
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop JOB_PURGE_OLD_EVENTS: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

PROMPT [2/8] dropping materialized views
BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_daily_peer_stats';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -12003 THEN
      NULL;
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop mv_daily_peer_stats: ' || SQLERRM);
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_hourly_bandwidth';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -12003 THEN
      NULL;
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop mv_hourly_bandwidth: ' || SQLERRM);
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_peer_ip_summary';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -12003 THEN
      NULL;
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop mv_peer_ip_summary: ' || SQLERRM);
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_daily_blocked';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -12003 THEN
      NULL;
    ELSE
      DBMS_OUTPUT.PUT_LINE('Failed to drop mv_daily_blocked: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

PROMPT [3/8] dropping views
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_bandwidth_trend'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_peer_identity'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_payload_audit_readable'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_session_timeline'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_fox_traffic'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_pipeline_health'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_slow_queries'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_correlated_activity'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_wg_peer_timeline'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_tunnel_throughput'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_blocked_hosts_24h'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_malicious_actors'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_host_threat_score'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT [4/8] dropping procedures and packages
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_proxy_bulk'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE purge_old_events'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT [5/8] dropping tables
BEGIN EXECUTE IMMEDIATE 'DROP TABLE bandwidth_samples CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE wg_peer_samples CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE payload_audit CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE connection_sessions CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE proxy_events CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE blocked_events CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE wg_events CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tls_fingerprints CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE blocklist_audit CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE db_query_log CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE shipper_heartbeats CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE data_retention_policy CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE devices CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE dlq_errors CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT [6/8] dropping standalone indexes if present
BEGIN EXECUTE IMMEDIATE 'DROP INDEX devices_claim_token_uq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT [7/8] dropping leftover sequences
BEGIN
  FOR rec IN (
    SELECT sequence_name
    FROM user_sequences
    WHERE sequence_name LIKE 'ISEQ$$_%'
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE "' || rec.sequence_name || '"';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

PROMPT [8/8] purging recycle bin
PURGE RECYCLEBIN;

PROMPT [ssl-proxy] nuclear drop complete
