-- =============================================================================
-- ssl-proxy canonical Oracle schema
-- Fresh baseline. Do not append migration-style ALTER blocks here.
-- =============================================================================

ALTER SESSION SET DDL_LOCK_TIMEOUT = 300;

CREATE OR REPLACE TYPE obj_network_endpoint AS OBJECT (
    ip_address VARCHAR2(45),
    port       NUMBER(5,0),
    hostname   VARCHAR2(253)
);
/

CREATE OR REPLACE TYPE obj_wireguard_identity AS OBJECT (
    wg_pubkey       VARCHAR2(64),
    device_id       RAW(16),
    username        VARCHAR2(128),
    identity_source VARCHAR2(16)
);
/

CREATE OR REPLACE TYPE obj_traffic_metrics AS OBJECT (
    bytes_up    NUMBER(20,0),
    bytes_down  NUMBER(20,0),
    duration_ms NUMBER(12,0)
);
/

CREATE TABLE DEVICES (
    DEVICE_ID         RAW(16) DEFAULT SYS_GUID(),
    WG_PUBKEY         VARCHAR2(64),
    CLAIM_TOKEN_HASH  VARCHAR2(128),
    DISPLAY_NAME      VARCHAR2(128),
    USERNAME          VARCHAR2(128),
    HOSTNAME          VARCHAR2(253),
    OS_HINT           VARCHAR2(64),
    MAC_HINT          VARCHAR2(17),
    FIRST_SEEN        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    LAST_SEEN         TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    NOTES             VARCHAR2(512),
    CONSTRAINT DEVICES_PK PRIMARY KEY (DEVICE_ID) RELY
);
CREATE INDEX DEVICES_WG_PUBKEY_IDX ON DEVICES (WG_PUBKEY);
CREATE INDEX DEVICES_USERNAME_IDX ON DEVICES (USERNAME, LAST_SEEN DESC);
CREATE UNIQUE INDEX DEVICES_CLAIM_TOKEN_UQ ON DEVICES (CLAIM_TOKEN_HASH);

CREATE TABLE PROXY_EVENTS (
    ID                   NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID             VARCHAR2(36) NOT NULL,
    ROW_SEQUENCE         NUMBER(10,0) NOT NULL,
    EVENT_TIME           TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    EVENT_TIMESTAMP_UTC  TIMESTAMP(3) DEFAULT CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP(3)) NOT NULL,
    EVENT_TYPE           VARCHAR2(32) NOT NULL,
    HOST                 VARCHAR2(253) NOT NULL,
    PEER_IP              VARCHAR2(45),
    WG_PUBKEY            VARCHAR2(64),
    DEVICE_ID            RAW(16),
    IDENTITY_SOURCE      VARCHAR2(16) DEFAULT 'unknown',
    PEER_HOSTNAME        VARCHAR2(253),
    CLIENT_UA            VARCHAR2(512),
    BYTES_UP             NUMBER(20) DEFAULT 0,
    BYTES_DOWN           NUMBER(20) DEFAULT 0,
    STATUS_CODE          NUMBER(5),
    BLOCKED              NUMBER(1) DEFAULT 0 CHECK (BLOCKED IN (0,1)),
    OBFUSCATION_PROFILE  VARCHAR2(32),
    CORRELATION_ID       RAW(16),
    PARENT_EVENT_ID      RAW(16),
    EVENT_SEQUENCE       NUMBER(10,0),
    DURATION_MS          NUMBER(12,0),
    REASON               VARCHAR2(64),
    RAW_JSON             JSON,
    CONSTRAINT PROXY_EVENTS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (EVENT_TIMESTAMP_UTC)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_EVENTS_INIT VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00')
);
CREATE UNIQUE INDEX PROXY_EVENTS_BATCH_ROW_IDX ON PROXY_EVENTS (BATCH_ID, ROW_SEQUENCE);
CREATE INDEX PROXY_EVENTS_EVENT_UTC_IDX ON PROXY_EVENTS (EVENT_TIMESTAMP_UTC) LOCAL;
CREATE INDEX PROXY_EVENTS_TIME_IDX ON PROXY_EVENTS (EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_HOST_IDX ON PROXY_EVENTS (HOST, EVENT_TIME) LOCAL;
CREATE INDEX PROXY_EVENTS_BLOCKED_IDX ON PROXY_EVENTS (BLOCKED, EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_DEVICE_TIME_IDX ON PROXY_EVENTS (DEVICE_ID, EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_EVENTS_WG_PUBKEY_TIME_IDX ON PROXY_EVENTS (WG_PUBKEY, EVENT_TIME DESC) LOCAL;

CREATE TABLE PROXY_BLOCKED_HOST_ROLLUPS (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    HOST               VARCHAR2(253) NOT NULL,
    BLOCKED_ATTEMPTS   NUMBER(20) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES      NUMBER(20) DEFAULT 0 NOT NULL,
    FREQUENCY_HZ       NUMBER(10,4) DEFAULT 0 NOT NULL,
    VERDICT            VARCHAR2(32) NOT NULL,
    CATEGORY           VARCHAR2(64),
    RISK_SCORE         NUMBER(10,4) DEFAULT 0,
    TARPIT_HELD_MS     NUMBER(20) DEFAULT 0,
    IAT_MS             NUMBER(20),
    CONSECUTIVE_BLOCKS NUMBER(10) DEFAULT 0,
    LAST_VERDICT       VARCHAR2(32),
    TLS_VER            VARCHAR2(16),
    ALPN               VARCHAR2(64),
    JA3_LITE           VARCHAR2(512),
    RESOLVED_IP        VARCHAR2(45),
    ASN_ORG            VARCHAR2(128),
    UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    FIRST_SEEN         TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CONSTRAINT PROXY_BLOCKED_HOST_ROLLUPS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PROXY_BLOCKED_HOST_UQ ON PROXY_BLOCKED_HOST_ROLLUPS (HOST);
CREATE INDEX PROXY_BLOCKED_UPDATED_IDX ON PROXY_BLOCKED_HOST_ROLLUPS (UPDATED_AT DESC);

CREATE BLOCKCHAIN TABLE PROXY_PAYLOAD_AUDIT (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CORRELATION_ID     RAW(16) NOT NULL,
    HOST               VARCHAR2(253) NOT NULL,
    DIRECTION          VARCHAR2(4) NOT NULL CHECK (DIRECTION IN ('UP','DOWN')),
    CAPTURED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    BYTE_OFFSET        NUMBER(10,0) DEFAULT 0 NOT NULL,
    PAYLOAD_OBJECT_KEY VARCHAR2(512),
    CONTENT_TYPE       VARCHAR2(128),
    HTTP_METHOD        VARCHAR2(16),
    HTTP_STATUS        NUMBER(5,0),
    HTTP_PATH          VARCHAR2(1024),
    IS_ENCRYPTED       NUMBER(1,0) DEFAULT 0 NOT NULL,
    TRUNCATED          NUMBER(1,0) DEFAULT 0 NOT NULL,
    PEER_IP            VARCHAR2(45),
    NOTES              VARCHAR2(512),
    CONSTRAINT PROXY_PAYLOAD_AUDIT_PK PRIMARY KEY (ID)
)
NO DROP UNTIL 365 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;
CREATE INDEX PROXY_PAYLOAD_CORR_IDX ON PROXY_PAYLOAD_AUDIT(CORRELATION_ID);
CREATE UNIQUE INDEX PROXY_PAYLOAD_AUDIT_UQ ON PROXY_PAYLOAD_AUDIT(CORRELATION_ID, HOST, DIRECTION, CAPTURED_AT, BYTE_OFFSET);
CREATE INDEX PROXY_PAYLOAD_HOST_IDX ON PROXY_PAYLOAD_AUDIT(HOST, CAPTURED_AT);

CREATE TABLE PROXY_TLS_FINGERPRINTS (
    JA3_LITE         VARCHAR2(512),
    FIRST_SEEN       TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    LAST_SEEN        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    SEEN_COUNT       NUMBER(10,0) DEFAULT 1 NOT NULL,
    TLS_VER          VARCHAR2(16),
    ALPN             VARCHAR2(64),
    CIPHER_COUNT     NUMBER(3,0),
    VERDICT_HINT     VARCHAR2(32),
    CONSTRAINT PROXY_TLS_FINGERPRINTS_PK PRIMARY KEY (JA3_LITE)
);

CREATE TABLE PROXY_CONNECTION_SESSIONS (
    SESSION_ID       RAW(16) DEFAULT SYS_GUID(),
    CORRELATION_ID   RAW(16),
    HOST             VARCHAR2(253) NOT NULL,
    PEER_IP          VARCHAR2(45),
    WG_PUBKEY        VARCHAR2(64),
    DEVICE_ID        RAW(16),
    IDENTITY_SOURCE  VARCHAR2(16) DEFAULT 'unknown',
    PEER_HOSTNAME    VARCHAR2(253),
    CLIENT_UA        VARCHAR2(512),
    TUNNEL_KIND      VARCHAR2(16) NOT NULL,
    OPENED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    OPENED_DATE      DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(OPENED_AT) AS DATE)) VIRTUAL,
    CLOSED_AT        TIMESTAMP,
    DURATION_MS      NUMBER(12,0),
    BYTES_UP         NUMBER(18,0) DEFAULT 0,
    BYTES_DOWN       NUMBER(18,0) DEFAULT 0,
    BLOCKED          NUMBER(1,0) DEFAULT 0 NOT NULL,
    TARPITTED        NUMBER(1,0) DEFAULT 0 NOT NULL,
    TARPIT_HELD_MS   NUMBER(10,0),
    VERDICT          VARCHAR2(32),
    CATEGORY         VARCHAR2(64),
    OBFUSCATION_PROFILE VARCHAR2(32),
    TLS_VER          VARCHAR2(16),
    ALPN             VARCHAR2(64),
    JA3_LITE         VARCHAR2(512),
    RESOLVED_IP      VARCHAR2(45),
    ASN_ORG          VARCHAR2(128),
    REASON           VARCHAR2(64),
    CREATED_AT       TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_CONNECTION_SESSIONS_PK PRIMARY KEY (SESSION_ID)
        USING INDEX (CREATE UNIQUE INDEX PROXY_CONN_SESS_PK_REV ON PROXY_CONNECTION_SESSIONS (SESSION_ID) REVERSE),
    CONSTRAINT PROXY_CONNECTION_SESSIONS_DEVICES_FK FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID) RELY DISABLE NOVALIDATE
)
PARTITION BY RANGE (OPENED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_CONNECTION_SESSIONS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_CONN_HOST_IDX ON PROXY_CONNECTION_SESSIONS(HOST, OPENED_AT) LOCAL;
CREATE INDEX PROXY_CONN_PEER_IDX ON PROXY_CONNECTION_SESSIONS(PEER_IP, OPENED_AT) LOCAL;
CREATE INDEX PROXY_CONN_CORR_IDX ON PROXY_CONNECTION_SESSIONS(CORRELATION_ID) LOCAL;
CREATE INDEX PROXY_CONN_DEVICE_IDX ON PROXY_CONNECTION_SESSIONS(DEVICE_ID, OPENED_AT DESC) LOCAL;
CREATE INDEX PROXY_CONN_WG_PUBKEY_IDX ON PROXY_CONNECTION_SESSIONS(WG_PUBKEY, OPENED_AT DESC) LOCAL;

CREATE TABLE PROXY_CONNECTION_SESSION_CLOSE_DLQ (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT       TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CAPTURED_DATE     DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    SESSION_ID        RAW(16) NOT NULL,
    REASON            VARCHAR2(64) NOT NULL,
    DURATION_MS       NUMBER(12,0),
    BYTES_UP          NUMBER(18,0),
    BYTES_DOWN        NUMBER(18,0),
    BLOCKED           NUMBER(1,0),
    TARPITTED         NUMBER(1,0),
    TARPIT_HELD_MS    NUMBER(10,0),
    VERDICT           VARCHAR2(32),
    CATEGORY          VARCHAR2(64),
    OBFUSCATION_PROFILE VARCHAR2(32),
    TLS_VER           VARCHAR2(16),
    ALPN              VARCHAR2(64),
    JA3_LITE          VARCHAR2(512),
    RESOLVED_IP       VARCHAR2(45),
    ASN_ORG           VARCHAR2(128),
    WG_PUBKEY         VARCHAR2(64),
    DEVICE_ID         RAW(16),
    IDENTITY_SOURCE   VARCHAR2(16),
    PEER_HOSTNAME     VARCHAR2(253),
    RAW_JSON          JSON,
    CONSTRAINT PROXY_CONNECTION_SESSION_CLOSE_DLQ_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_CONNECTION_SESSION_CLOSE_DLQ_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_CONN_CLOSE_DLQ_SESSION_IDX ON PROXY_CONNECTION_SESSION_CLOSE_DLQ(SESSION_ID, CAPTURED_AT DESC) LOCAL;

CREATE TABLE PROXY_WG_EVENTS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    EVENT_TIME    TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    EVENT_UTC_DATE     DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(EVENT_TIME) AS DATE)) VIRTUAL,
    EVENT_TYPE    VARCHAR2(32) NOT NULL,
    INTERFACE     VARCHAR2(16) NOT NULL,
    PEER_PUBKEY   VARCHAR2(64) NOT NULL,
    ENDPOINT_IP   VARCHAR2(45),
    ENDPOINT_PORT NUMBER(5),
    RX_BYTES      NUMBER(20) DEFAULT 0,
    TX_BYTES      NUMBER(20) DEFAULT 0,
    LATENCY_MS    NUMBER(10,3),
    RAW_JSON      JSON,
    CONSTRAINT PROXY_WG_EVENTS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (EVENT_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_WG_EVENTS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_WG_EVENTS_TIME_IDX ON PROXY_WG_EVENTS (EVENT_TIME DESC) LOCAL;
CREATE INDEX PROXY_WG_EVENTS_PEER_IDX ON PROXY_WG_EVENTS (PEER_PUBKEY, EVENT_TIME DESC) LOCAL;

CREATE TABLE PROXY_WG_PEER_SAMPLES (
    SAMPLE_ID         NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SAMPLED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    SAMPLED_DATE      DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(SAMPLED_AT) AS DATE)) VIRTUAL,
    INTERFACE         VARCHAR2(16) NOT NULL,
    WG_PUBKEY         VARCHAR2(64) NOT NULL,
    DEVICE_ID         RAW(16),
    PEER_IP           VARCHAR2(45),
    PEER_HOSTNAME     VARCHAR2(253),
    LAST_HANDSHAKE_AT TIMESTAMP,
    RX_BYTES_TOTAL    NUMBER(20,0) DEFAULT 0 NOT NULL,
    TX_BYTES_TOTAL    NUMBER(20,0) DEFAULT 0 NOT NULL,
    RX_BYTES_DELTA    NUMBER(20,0) DEFAULT 0 NOT NULL,
    TX_BYTES_DELTA    NUMBER(20,0) DEFAULT 0 NOT NULL,
    SESSIONS_ACTIVE   NUMBER(10,0) DEFAULT 0 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_WG_PEER_SAMPLES_PK PRIMARY KEY (SAMPLE_ID)
)
PARTITION BY RANGE (SAMPLED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_WG_PEER_SAMPLES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_WG_PEER_SAMPLES_WG_PUBKEY_IDX ON PROXY_WG_PEER_SAMPLES (WG_PUBKEY, SAMPLED_AT DESC) LOCAL;
CREATE INDEX PROXY_WG_PEER_SAMPLES_DEVICE_ID_IDX ON PROXY_WG_PEER_SAMPLES (DEVICE_ID, SAMPLED_AT DESC) LOCAL;

CREATE TABLE PROXY_BANDWIDTH_SAMPLES (
    SAMPLE_ID               NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SAMPLED_AT              TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    SAMPLED_DATE            DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(SAMPLED_AT) AS DATE)) VIRTUAL,
    WG_PUBKEY               VARCHAR2(64) NOT NULL,
    DEVICE_ID               RAW(16),
    BYTES_UP_DELTA          NUMBER(20,0) DEFAULT 0 NOT NULL,
    BYTES_DOWN_DELTA        NUMBER(20,0) DEFAULT 0 NOT NULL,
    SESSIONS_ACTIVE         NUMBER(10,0) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    ALLOWED_BYTES_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    BLOCKED_COUNT_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    ALLOWED_COUNT_DELTA     NUMBER(20,0) DEFAULT 0 NOT NULL,
    BLOCKED_BYTES_IS_APPROX NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CONSTRAINT PROXY_BANDWIDTH_SAMPLES_PK PRIMARY KEY (SAMPLE_ID)
)
PARTITION BY RANGE (SAMPLED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_BANDWIDTH_SAMPLES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX PROXY_BANDWIDTH_SAMPLES_WG_PUBKEY_IDX ON PROXY_BANDWIDTH_SAMPLES (WG_PUBKEY, SAMPLED_AT DESC) LOCAL;
CREATE INDEX PROXY_BANDWIDTH_SAMPLES_DEVICE_ID_IDX ON PROXY_BANDWIDTH_SAMPLES (DEVICE_ID, SAMPLED_AT DESC) LOCAL;

CREATE TABLE PROXY_DB_QUERY_LOG (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT   TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CAPTURED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    SESSION_ID    VARCHAR2(64),
    CLIENT_IP     VARCHAR2(45),
    DB_USER       VARCHAR2(128),
    SQL_TEXT      CLOB NOT NULL,
    ELAPSED_MS    NUMBER(12,3),
    ROWS_EXAMINED NUMBER(20),
    ROWS_RETURNED NUMBER(20),
    PLAN_HASH     VARCHAR2(64),
    RAW_JSON      JSON,
    CONSTRAINT PROXY_DB_QUERY_LOG_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_DB_QUERY_LOG_INIT VALUES LESS THAN (DATE '2026-01-01')
);

CREATE BLOCKCHAIN TABLE PROXY_BLOCKLIST_AUDIT (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    HOST          VARCHAR2(253) NOT NULL,
    ACTION        VARCHAR2(32) NOT NULL,
    REASON        VARCHAR2(256),
    CAPTURED_AT   TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    RAW_JSON      JSON,
    CONSTRAINT PROXY_BLOCKLIST_AUDIT_PK PRIMARY KEY (ID)
)
NO DROP UNTIL 365 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;

CREATE TABLE PROXY_SHIPPER_HEARTBEATS (
    SHIPPER_NAME VARCHAR2(64),
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    STATUS       VARCHAR2(32) NOT NULL,
    DETAILS_JSON JSON,
    CONSTRAINT PROXY_SHIPPER_HEARTBEATS_PK PRIMARY KEY (SHIPPER_NAME)
);

CREATE TABLE PROXY_DATA_RETENTION_POLICIES (
    TABLE_NAME            VARCHAR2(128),
    RETAIN_DAYS           NUMBER(8,0) NOT NULL,
    PARTITION_KEY_COLUMN  VARCHAR2(128) NOT NULL,
    ENABLED               NUMBER(1,0) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    LAST_RETENTION_AT     TIMESTAMP WITH TIME ZONE,
    LAST_RETENTION_DETAIL VARCHAR2(512),
    UPDATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'America/New_York') NOT NULL,
    CONSTRAINT PROXY_DATA_RETENTION_POLICIES_PK PRIMARY KEY (TABLE_NAME)
);

INSERT ALL
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_EVENTS', 90, 'EVENT_TIMESTAMP_UTC')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_PAYLOAD_AUDIT', 365, 'CAPTURED_AT')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_CONNECTION_SESSIONS', 90, 'OPENED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_CONNECTION_SESSION_CLOSE_DLQ', 30, 'CAPTURED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_WG_EVENTS', 30, 'EVENT_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_WG_PEER_SAMPLES', 30, 'SAMPLED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_BANDWIDTH_SAMPLES', 30, 'SAMPLED_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_DB_QUERY_LOG', 30, 'CAPTURED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('PROXY_BLOCKLIST_AUDIT', 365, 'CAPTURED_AT')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_AUDIT_FRAMES', 90, 'OBSERVED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_BANDWIDTH_WINDOWS', 90, 'WINDOW_START_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_ALERTS', 365, 'DETECTED_UTC_DATE')
    INTO PROXY_DATA_RETENTION_POLICIES (TABLE_NAME, RETAIN_DAYS, PARTITION_KEY_COLUMN)
        VALUES ('WIRELESS_SENSOR_HEALTH', 30, 'REPORTED_UTC_DATE')
SELECT 1 FROM DUAL;

CREATE TABLE PROXY_DLQ_ERRORS (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    CAPTURED_AT    TIMESTAMP DEFAULT (CAST(SYSTIMESTAMP AT TIME ZONE 'America/New_York' AS TIMESTAMP)) NOT NULL,
    CAPTURED_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(CAPTURED_AT) AS DATE)) VIRTUAL,
    PROCEDURE_NAME VARCHAR2(64) NOT NULL,
    ERROR_CODE     NUMBER,
    ERROR_MSG      VARCHAR2(512),
    ROW_DATA       CLOB,
    CONSTRAINT PROXY_DLQ_ERRORS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CAPTURED_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PROXY_DLQ_ERRORS_INIT VALUES LESS THAN (DATE '2026-01-01')
);

CREATE TABLE WIRELESS_SENSORS (
    SENSOR_PK     NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID     VARCHAR2(64) NOT NULL,
    LOCATION_ID   VARCHAR2(128) NOT NULL,
    INTERFACE     VARCHAR2(32) NOT NULL,
    REG_DOMAIN    VARCHAR2(8),
    FIRST_SEEN_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_SENSORS_PK PRIMARY KEY (SENSOR_PK),
    CONSTRAINT WIRELESS_SENSORS_ID_UQ UNIQUE (SENSOR_ID)
);
CREATE INDEX WIRELESS_SENSORS_LOCATION_IDX ON WIRELESS_SENSORS (LOCATION_ID);

CREATE TABLE WIRELESS_KNOWN_NETWORKS (
    NETWORK_PK  NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    LOCATION_ID VARCHAR2(128) NOT NULL,
    BSSID       VARCHAR2(17) NOT NULL,
    SSID        VARCHAR2(256),
    AUTHORIZED  NUMBER(1,0) DEFAULT 1 NOT NULL CHECK (AUTHORIZED IN (0,1)),
    VALID_FROM  TIMESTAMP WITH TIME ZONE NOT NULL,
    VALID_TO    TIMESTAMP WITH TIME ZONE,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_KNOWN_NETWORKS_PK PRIMARY KEY (NETWORK_PK),
    CONSTRAINT WIRELESS_KNOWN_NETWORKS_UQ UNIQUE (LOCATION_ID, BSSID)
);

CREATE TABLE WIRELESS_CHANNELS (
    CHANNEL       NUMBER(3,0),
    FREQUENCY_MHZ NUMBER(6,0) NOT NULL,
    BAND          VARCHAR2(8) NOT NULL,
    CONSTRAINT WIRELESS_CHANNELS_PK PRIMARY KEY (CHANNEL)
);
INSERT INTO WIRELESS_CHANNELS VALUES (1, 2412, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (6, 2437, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (11, 2462, '2.4GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (36, 5180, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (40, 5200, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (44, 5220, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (48, 5240, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (149,5745, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (153,5765, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (157,5785, '5GHz');
INSERT INTO WIRELESS_CHANNELS VALUES (161,5805, '5GHz');

CREATE TABLE WIRELESS_AUDIT_FRAMES (
    FRAME_PK             NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID             VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE         NUMBER(10,0) NOT NULL,
    EVENT_TYPE           VARCHAR2(64) NOT NULL,
    OBSERVED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    OBSERVED_UTC_DATE    DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(OBSERVED_AT) AS DATE)) VIRTUAL,
    SENSOR_ID            VARCHAR2(64) NOT NULL,
    LOCATION_ID          VARCHAR2(128) NOT NULL,
    INTERFACE            VARCHAR2(32) NOT NULL,
    CHANNEL              NUMBER(3,0) NOT NULL,
    FRAME_TYPE           VARCHAR2(32),
    FRAME_SUBTYPE        VARCHAR2(32) NOT NULL,
    BSSID                VARCHAR2(17),
    SOURCE_MAC           VARCHAR2(17),
    DESTINATION_MAC      VARCHAR2(17),
    TRANSMITTER_MAC      VARCHAR2(17),
    RECEIVER_MAC         VARCHAR2(17),
    DESTINATION_BSSID    VARCHAR2(17),
    SSID                 VARCHAR2(256),
    SIGNAL_DBM           NUMBER(4,0),
    SEQUENCE_NUMBER      NUMBER(6,0),
    RAW_LEN              NUMBER(6,0) NOT NULL,
    IS_RETRY             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_RETRY IN (0,1)),
    IS_MORE_DATA         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_MORE_DATA IN (0,1)),
    IS_POWER_SAVE        NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_POWER_SAVE IN (0,1)),
    IS_PROTECTED         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_PROTECTED IN (0,1)),
    IS_TO_DS             NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_TO_DS IN (0,1)),
    IS_FROM_DS           NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_FROM_DS IN (0,1)),
    IS_HANDSHAKE         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_HANDSHAKE IN (0,1)),
    SECURITY_FLAGS       NUMBER(12,0) DEFAULT 0 NOT NULL,
    DEVICE_ID            VARCHAR2(128),
    USERNAME             VARCHAR2(256),
    IDENTITY_SOURCE      VARCHAR2(64) DEFAULT 'unknown' NOT NULL,
    TAGS                 VARCHAR2(2000),
    ANOMALY_REASONS      VARCHAR2(1000),
    RAW_JSON             JSON,
    CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_AUDIT_FRAMES_PK PRIMARY KEY (FRAME_PK),
    CONSTRAINT WIRELESS_AUDIT_FRAMES_BATCH_UQ UNIQUE (BATCH_ID, ROW_SEQUENCE)
)
PARTITION BY RANGE (OBSERVED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_AUDIT_FRAMES_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX WIRELESS_FRAMES_SENSOR_TIME_IDX ON WIRELESS_AUDIT_FRAMES (SENSOR_ID, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_LOCATION_TIME_IDX ON WIRELESS_AUDIT_FRAMES (LOCATION_ID, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_SOURCE_MAC_IDX ON WIRELESS_AUDIT_FRAMES (SOURCE_MAC, OBSERVED_AT) LOCAL;
CREATE INDEX WIRELESS_FRAMES_BSSID_IDX ON WIRELESS_AUDIT_FRAMES (BSSID, OBSERVED_AT) LOCAL;

CREATE TABLE WIRELESS_BANDWIDTH_WINDOWS (
    BW_PK                  NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID               VARCHAR2(128) NOT NULL,
    ROW_SEQUENCE           NUMBER(10,0) NOT NULL,
    SCHEMA_VERSION         NUMBER(3,0) DEFAULT 1 NOT NULL,
    WINDOW_START           TIMESTAMP WITH TIME ZONE NOT NULL,
    WINDOW_START_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(WINDOW_START) AS DATE)) VIRTUAL,
    WINDOW_END             TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID              VARCHAR2(64) NOT NULL,
    LOCATION_ID            VARCHAR2(128) NOT NULL,
    INTERFACE              VARCHAR2(32) NOT NULL,
    CHANNEL                NUMBER(3,0) NOT NULL,
    SOURCE_MAC             VARCHAR2(17) NOT NULL,
    DESTINATION_BSSID      VARCHAR2(17) NOT NULL,
    SSID                   VARCHAR2(256),
    BYTES                  NUMBER(20,0) DEFAULT 0 NOT NULL,
    FRAME_COUNT            NUMBER(12,0) DEFAULT 0 NOT NULL,
    RETRY_COUNT            NUMBER(12,0) DEFAULT 0 NOT NULL,
    MORE_DATA_COUNT        NUMBER(12,0) DEFAULT 0 NOT NULL,
    POWER_SAVE_COUNT       NUMBER(12,0) DEFAULT 0 NOT NULL,
    STRONGEST_SIGNAL_DBM   NUMBER(4,0),
    HIST_UNDER_100         NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_100_500           NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_500_1000          NUMBER(12,0) DEFAULT 0 NOT NULL,
    HIST_1000_1500         NUMBER(12,0) DEFAULT 0 NOT NULL,
    INTER_ARRIVAL_P50_MS   NUMBER(10,0),
    EXTERNAL_BSSID         NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (EXTERNAL_BSSID IN (0,1)),
    THRESHOLD_EXCEEDED     NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (THRESHOLD_EXCEEDED IN (0,1)),
    WALL_CLOCK_DELTA_MS    NUMBER(12,0),
    WINDOW_IS_PARTIAL      NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (WINDOW_IS_PARTIAL IN (0,1)),
    PUBLISHED_AT           TIMESTAMP WITH TIME ZONE,
    CREATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_BW_WINDOWS_PK PRIMARY KEY (BW_PK),
    CONSTRAINT WIRELESS_BW_WINDOWS_BATCH_UQ UNIQUE (BATCH_ID, ROW_SEQUENCE)
)
PARTITION BY RANGE (WINDOW_START_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_BANDWIDTH_WINDOWS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX WIRELESS_BW_SENSOR_TIME_IDX ON WIRELESS_BANDWIDTH_WINDOWS (SENSOR_ID, WINDOW_START) LOCAL;
CREATE INDEX WIRELESS_BW_THRESHOLD_IDX ON WIRELESS_BANDWIDTH_WINDOWS (THRESHOLD_EXCEEDED, WINDOW_START) LOCAL;
CREATE INDEX WIRELESS_BW_SOURCE_MAC_IDX ON WIRELESS_BANDWIDTH_WINDOWS (SOURCE_MAC, WINDOW_START) LOCAL;

CREATE TABLE WIRELESS_ALERTS (
    ALERT_PK        NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    ALERT_TYPE      VARCHAR2(64) NOT NULL,
    BATCH_ID        VARCHAR2(128),
    ROW_SEQUENCE    NUMBER(10,0),
    ALERT_DATE      DATE,
    DETECTED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    DETECTED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(DETECTED_AT) AS DATE)) VIRTUAL,
    SENSOR_ID       VARCHAR2(64) NOT NULL,
    LOCATION_ID     VARCHAR2(128) NOT NULL,
    INTERFACE       VARCHAR2(32),
    CHANNEL         NUMBER(3,0),
    PRIMARY_MAC     VARCHAR2(17),
    SECONDARY_MAC   VARCHAR2(17),
    SSID            VARCHAR2(256),
    SIGNAL_DBM      NUMBER(4,0),
    BYTES           NUMBER(20,0),
    DETAILS_JSON    JSON,
    RAW_JSON        JSON,
    ACKNOWLEDGED    NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (ACKNOWLEDGED IN (0,1)),
    ACKNOWLEDGED_BY VARCHAR2(128),
    ACKNOWLEDGED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_ALERTS_PK PRIMARY KEY (ALERT_PK),
    CONSTRAINT WIRELESS_ALERTS_BATCH_UQ UNIQUE (ALERT_TYPE, BATCH_ID, ROW_SEQUENCE)
)
PARTITION BY RANGE (DETECTED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_ALERTS_INIT VALUES LESS THAN (DATE '2026-01-01')
);
CREATE INDEX WIRELESS_ALERTS_TYPE_TIME_IDX ON WIRELESS_ALERTS (ALERT_TYPE, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_ALERTS_SENSOR_TIME_IDX ON WIRELESS_ALERTS (SENSOR_ID, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_ALERTS_UNACK_IDX ON WIRELESS_ALERTS (ACKNOWLEDGED, DETECTED_AT DESC) LOCAL;
CREATE INDEX WIRELESS_BW_ALERT_DAY_IDX ON WIRELESS_ALERTS (ALERT_TYPE, SENSOR_ID, PRIMARY_MAC, SECONDARY_MAC, ALERT_DATE) LOCAL;

CREATE BLOCKCHAIN TABLE WIRELESS_ALERTS_LEDGER (
    LEDGER_ID      NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    ALERT_PK       NUMBER NOT NULL,
    ALERT_TYPE     VARCHAR2(64) NOT NULL,
    BATCH_ID       VARCHAR2(128),
    ROW_SEQUENCE   NUMBER(10,0),
    ALERT_DATE     DATE,
    DETECTED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    SENSOR_ID      VARCHAR2(64) NOT NULL,
    LOCATION_ID    VARCHAR2(128) NOT NULL,
    INTERFACE      VARCHAR2(32),
    CHANNEL        NUMBER(3,0),
    PRIMARY_MAC    VARCHAR2(17),
    SECONDARY_MAC  VARCHAR2(17),
    SSID           VARCHAR2(256),
    SIGNAL_DBM     NUMBER(4,0),
    BYTES          NUMBER(20,0),
    DETAILS_JSON   JSON,
    RAW_JSON       JSON,
    ACKNOWLEDGED   NUMBER(1,0) NOT NULL,
    LEDGER_ACTION  VARCHAR2(16) NOT NULL,
    CAPTURED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_ALERTS_LEDGER_PK PRIMARY KEY (LEDGER_ID)
)
NO DROP UNTIL 365 DAYS IDLE
NO DELETE LOCKED
HASHING USING SHA2_512 VERSION V1;
CREATE INDEX WIRELESS_ALERTS_LEDGER_ALERT_IDX ON WIRELESS_ALERTS_LEDGER (ALERT_PK, CAPTURED_AT);

CREATE OR REPLACE TRIGGER WIRELESS_ALERTS_LEDGER_TRG
AFTER INSERT OR UPDATE ON WIRELESS_ALERTS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(16);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSE
        v_action := 'UPDATE';
    END IF;

    INSERT INTO WIRELESS_ALERTS_LEDGER (
        ALERT_PK, ALERT_TYPE, BATCH_ID, ROW_SEQUENCE, ALERT_DATE, DETECTED_AT,
        SENSOR_ID, LOCATION_ID, INTERFACE, CHANNEL, PRIMARY_MAC, SECONDARY_MAC,
        SSID, SIGNAL_DBM, BYTES, DETAILS_JSON, RAW_JSON, ACKNOWLEDGED, LEDGER_ACTION
    ) VALUES (
        :NEW.ALERT_PK, :NEW.ALERT_TYPE, :NEW.BATCH_ID, :NEW.ROW_SEQUENCE, :NEW.ALERT_DATE,
        :NEW.DETECTED_AT, :NEW.SENSOR_ID, :NEW.LOCATION_ID, :NEW.INTERFACE, :NEW.CHANNEL,
        :NEW.PRIMARY_MAC, :NEW.SECONDARY_MAC, :NEW.SSID, :NEW.SIGNAL_DBM, :NEW.BYTES,
        :NEW.DETAILS_JSON, :NEW.RAW_JSON, :NEW.ACKNOWLEDGED, v_action
    );
END;
/

CREATE TABLE WIRELESS_CLIENT_INVENTORY (
    INVENTORY_PK    NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID       VARCHAR2(64) NOT NULL,
    LOCATION_ID     VARCHAR2(128) NOT NULL,
    SNAPSHOT_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    CLIENT_MAC      VARCHAR2(17) NOT NULL,
    BSSID           VARCHAR2(17),
    SSID            VARCHAR2(256),
    DEVICE_ID       VARCHAR2(128),
    USERNAME        VARCHAR2(256),
    IDENTITY_SOURCE VARCHAR2(64),
    LAST_SEEN       TIMESTAMP WITH TIME ZONE NOT NULL,
    FIRST_SEEN      TIMESTAMP WITH TIME ZONE NOT NULL,
    SIGNAL_DBM      NUMBER(4,0),
    IS_AUTHORIZED   NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_AUTHORIZED IN (0,1)),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_CLIENT_INVENTORY_PK PRIMARY KEY (INVENTORY_PK)
);
CREATE UNIQUE INDEX WIRELESS_CLIENT_INV_UQ ON WIRELESS_CLIENT_INVENTORY (SENSOR_ID, SYS_EXTRACT_UTC(SNAPSHOT_AT), CLIENT_MAC);
CREATE INDEX WIRELESS_INV_SENSOR_SNAP_IDX ON WIRELESS_CLIENT_INVENTORY (SENSOR_ID, SNAPSHOT_AT);
CREATE INDEX WIRELESS_INV_CLIENT_MAC_IDX ON WIRELESS_CLIENT_INVENTORY (CLIENT_MAC, SNAPSHOT_AT);

CREATE TABLE WIRELESS_PROBE_REQUESTS (
    PROBE_PK    NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    BATCH_ID    VARCHAR2(128) NOT NULL,
    CLIENT_MAC  VARCHAR2(17) NOT NULL,
    SSID        VARCHAR2(256) NOT NULL,
    KNOWN_BSSID VARCHAR2(17),
    FIRST_SEEN  TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN   TIMESTAMP WITH TIME ZONE NOT NULL,
    PROBE_COUNT NUMBER(10,0) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_PROBE_REQUESTS_PK PRIMARY KEY (PROBE_PK),
    CONSTRAINT WIRELESS_PROBE_BATCH_UQ UNIQUE (BATCH_ID, CLIENT_MAC, SSID)
);
CREATE INDEX WIRELESS_PROBES_CLIENT_MAC_IDX ON WIRELESS_PROBE_REQUESTS (CLIENT_MAC, LAST_SEEN);
CREATE INDEX WIRELESS_PROBES_SSID_IDX ON WIRELESS_PROBE_REQUESTS (SSID, LAST_SEEN);

CREATE TABLE WIRELESS_AUDIT_WINDOWS (
    WINDOW_CFG_PK NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID     VARCHAR2(64) NOT NULL,
    LOCATION_ID   VARCHAR2(128) NOT NULL,
    TIMEZONE      VARCHAR2(64),
    ACTIVE_DAYS   VARCHAR2(64),
    START_TIME    VARCHAR2(8),
    END_TIME      VARCHAR2(8),
    APPLIED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    SUPERSEDED_AT TIMESTAMP WITH TIME ZONE,
    PUSH_SOURCE   VARCHAR2(32) DEFAULT 'env' NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_AUDIT_WINDOWS_PK PRIMARY KEY (WINDOW_CFG_PK)
);

CREATE TABLE WIRELESS_SENSOR_HEALTH (
    HEALTH_PK          NUMBER GENERATED ALWAYS AS IDENTITY (CACHE 50000 ORDER),
    SENSOR_ID          VARCHAR2(64) NOT NULL,
    LOCATION_ID        VARCHAR2(128) NOT NULL,
    REPORTED_AT        TIMESTAMP WITH TIME ZONE NOT NULL,
    REPORTED_UTC_DATE  DATE GENERATED ALWAYS AS (CAST(SYS_EXTRACT_UTC(REPORTED_AT) AS DATE)) VIRTUAL,
    PACKETS_SEEN       NUMBER(20,0) DEFAULT 0 NOT NULL,
    DECODED_FRAMES     NUMBER(20,0) DEFAULT 0 NOT NULL,
    UNSUPPORTED_FRAMES NUMBER(20,0) DEFAULT 0 NOT NULL,
    PIPELINE_ERRORS    NUMBER(12,0) DEFAULT 0 NOT NULL,
    CAPTURE_ERRORS     NUMBER(12,0) DEFAULT 0 NOT NULL,
    AUDIT_WINDOW_DROPS NUMBER(20,0) DEFAULT 0 NOT NULL,
    MAC_LOOKUP_FAILURES NUMBER(12,0) DEFAULT 0 NOT NULL,
    CHANNEL_HOP_COUNT  NUMBER(12,0) DEFAULT 0 NOT NULL,
    LAG_TOTAL_MS       NUMBER(20,0),
    LAG_COUNT          NUMBER(12,0),
    AVG_LAG_MS         NUMBER(12,2) GENERATED ALWAYS AS (CASE WHEN LAG_COUNT > 0 THEN LAG_TOTAL_MS / LAG_COUNT ELSE NULL END) VIRTUAL,
    BW_WINDOW_LAG_MS   NUMBER(12,0),
    MEMORY_BACKLOG_LEN NUMBER(10,0),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT WIRELESS_SENSOR_HEALTH_PK PRIMARY KEY (HEALTH_PK)
)
PARTITION BY RANGE (REPORTED_UTC_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION WIRELESS_SENSOR_HEALTH_INIT VALUES LESS THAN (DATE '2026-01-01')
);

CREATE OR REPLACE PROCEDURE WIRELESS_MERGE_BANDWIDTH_ALERTS (p_batch_id IN VARCHAR2) AS
    v_lock_handle VARCHAR2(128);
    v_lock_result NUMBER;
BEGIN
    DBMS_LOCK.ALLOCATE_UNIQUE('BW_MERGE_' || RAWTOHEX(STANDARD_HASH(p_batch_id, 'SHA256')), v_lock_handle);
    v_lock_result := DBMS_LOCK.REQUEST(v_lock_handle, DBMS_LOCK.X_MODE, 10, FALSE);
    IF v_lock_result <> 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Batch merge concurrency collision.');
    END IF;

    MERGE INTO WIRELESS_ALERTS tgt
    USING (
        WITH batch_keys AS (
            SELECT DISTINCT SENSOR_ID, SOURCE_MAC, DESTINATION_BSSID, TRUNC(CAST(WINDOW_START AS DATE)) AS ALERT_DATE
            FROM WIRELESS_BANDWIDTH_WINDOWS
            WHERE BATCH_ID = p_batch_id AND THRESHOLD_EXCEEDED = 1
        )
        SELECT
            'bandwidth_threshold' AS ALERT_TYPE,
            p_batch_id AS BATCH_ID,
            MIN(w.ROW_SEQUENCE) AS ROW_SEQUENCE,
            TRUNC(CAST(w.WINDOW_START AS DATE)) AS ALERT_DATE,
            MIN(w.WINDOW_START) AS DETECTED_AT,
            w.SENSOR_ID,
            MAX(w.LOCATION_ID) KEEP (DENSE_RANK LAST ORDER BY w.WINDOW_START) AS LOCATION_ID,
            w.SOURCE_MAC AS PRIMARY_MAC,
            w.DESTINATION_BSSID AS SECONDARY_MAC,
            MAX(w.SSID) KEEP (DENSE_RANK LAST ORDER BY w.WINDOW_START) AS SSID,
            SUM(w.BYTES) AS BYTES,
            JSON_OBJECT(
              'first_window_start' VALUE TO_CHAR(MIN(w.WINDOW_START), 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'),
              'last_window_start' VALUE TO_CHAR(MAX(w.WINDOW_START), 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'),
              'window_count' VALUE COUNT(*),
              'max_bytes_per_window' VALUE MAX(w.BYTES)
              RETURNING JSON
            ) AS DETAILS_JSON
        FROM WIRELESS_BANDWIDTH_WINDOWS w
        JOIN batch_keys k ON k.SENSOR_ID = w.SENSOR_ID
          AND k.SOURCE_MAC = w.SOURCE_MAC
          AND k.DESTINATION_BSSID = w.DESTINATION_BSSID
          AND k.ALERT_DATE = TRUNC(CAST(w.WINDOW_START AS DATE))
        WHERE w.THRESHOLD_EXCEEDED = 1
        GROUP BY w.SENSOR_ID, w.SOURCE_MAC, w.DESTINATION_BSSID, TRUNC(CAST(w.WINDOW_START AS DATE))
    ) src
    ON (tgt.ALERT_TYPE = src.ALERT_TYPE AND tgt.SENSOR_ID = src.SENSOR_ID AND tgt.PRIMARY_MAC = src.PRIMARY_MAC AND tgt.SECONDARY_MAC = src.SECONDARY_MAC AND tgt.ALERT_DATE = src.ALERT_DATE)
    WHEN MATCHED THEN UPDATE SET
        tgt.BATCH_ID = src.BATCH_ID,
        tgt.ROW_SEQUENCE = src.ROW_SEQUENCE,
        tgt.DETECTED_AT = src.DETECTED_AT,
        tgt.LOCATION_ID = src.LOCATION_ID,
        tgt.SSID = src.SSID,
        tgt.BYTES = src.BYTES,
        tgt.DETAILS_JSON = src.DETAILS_JSON,
        tgt.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
        ALERT_TYPE, BATCH_ID, ROW_SEQUENCE, ALERT_DATE, DETECTED_AT, SENSOR_ID,
        LOCATION_ID, PRIMARY_MAC, SECONDARY_MAC, SSID, BYTES, DETAILS_JSON
    ) VALUES (
        src.ALERT_TYPE, src.BATCH_ID, src.ROW_SEQUENCE, src.ALERT_DATE, src.DETECTED_AT,
        src.SENSOR_ID, src.LOCATION_ID, src.PRIMARY_MAC, src.SECONDARY_MAC,
        src.SSID, src.BYTES, src.DETAILS_JSON
    );
    COMMIT;
    v_lock_result := DBMS_LOCK.RELEASE(v_lock_handle);
EXCEPTION
    WHEN OTHERS THEN
        IF v_lock_handle IS NOT NULL THEN
            BEGIN
                v_lock_result := DBMS_LOCK.RELEASE(v_lock_handle);
            EXCEPTION
                WHEN OTHERS THEN
                    NULL;
            END;
        END IF;
        RAISE;
END WIRELESS_MERGE_BANDWIDTH_ALERTS;
/

CREATE OR REPLACE PROCEDURE WIRELESS_UPSERT_SENSOR (
    p_sensor_id IN VARCHAR2,
    p_location_id IN VARCHAR2,
    p_interface IN VARCHAR2,
    p_reg_domain IN VARCHAR2,
    p_observed_at IN TIMESTAMP WITH TIME ZONE
) AS
BEGIN
    MERGE INTO WIRELESS_SENSORS tgt
    USING (SELECT 1 FROM DUAL) dummy
    ON (tgt.SENSOR_ID = p_sensor_id)
    WHEN MATCHED THEN UPDATE SET
        tgt.LOCATION_ID = p_location_id,
        tgt.INTERFACE = p_interface,
        tgt.LAST_SEEN_AT = p_observed_at
    WHEN NOT MATCHED THEN INSERT (
        SENSOR_ID, LOCATION_ID, INTERFACE, REG_DOMAIN, FIRST_SEEN_AT, LAST_SEEN_AT
    ) VALUES (
        p_sensor_id, p_location_id, p_interface, p_reg_domain, p_observed_at, p_observed_at
    );
    COMMIT;
END WIRELESS_UPSERT_SENSOR;
/

ALTER TABLE PROXY_EVENTS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
ALTER TABLE PROXY_EVENTS ILM ADD POLICY
    DROP PARTITION
    AFTER 90 DAYS OF NO ACCESS;

ALTER TABLE PROXY_CONNECTION_SESSIONS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
ALTER TABLE PROXY_CONNECTION_SESSIONS ILM ADD POLICY
    DROP PARTITION
    AFTER 90 DAYS OF NO ACCESS;

ALTER TABLE PROXY_CONNECTION_SESSION_CLOSE_DLQ ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE PROXY_WG_EVENTS ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE PROXY_WG_PEER_SAMPLES ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE PROXY_BANDWIDTH_SAMPLES ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE PROXY_DB_QUERY_LOG ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE PROXY_DLQ_ERRORS ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;
ALTER TABLE WIRELESS_AUDIT_FRAMES ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
ALTER TABLE WIRELESS_AUDIT_FRAMES ILM ADD POLICY
    DROP PARTITION
    AFTER 90 DAYS OF NO ACCESS;
ALTER TABLE WIRELESS_BANDWIDTH_WINDOWS ILM ADD POLICY
    ROW STORE COMPRESS ADVANCED ROW
    AFTER 30 DAYS OF NO MODIFICATION;
ALTER TABLE WIRELESS_BANDWIDTH_WINDOWS ILM ADD POLICY
    DROP PARTITION
    AFTER 90 DAYS OF NO ACCESS;
ALTER TABLE WIRELESS_ALERTS ILM ADD POLICY
    DROP PARTITION
    AFTER 365 DAYS OF NO ACCESS;
ALTER TABLE WIRELESS_SENSOR_HEALTH ILM ADD POLICY
    DROP PARTITION
    AFTER 30 DAYS OF NO ACCESS;

CREATE OR REPLACE PACKAGE PROXY_SECURITY_CTX_PKG AS
    PROCEDURE SET_APPEND_ONLY_WRITER;
END PROXY_SECURITY_CTX_PKG;
/

CREATE OR REPLACE CONTEXT PROXY_SECURITY_CTX USING PROXY_SECURITY_CTX_PKG;

CREATE OR REPLACE PACKAGE BODY PROXY_SECURITY_CTX_PKG AS
    PROCEDURE SET_APPEND_ONLY_WRITER AS
    BEGIN
        IF SYS_CONTEXT('USERENV', 'SESSION_USER') IN ('PROXY_INGEST', 'PROXY_INGEST_ROLE')
           OR SYS_CONTEXT('SYS_SESSION_ROLES', 'PROXY_INGEST_ROLE') = 'TRUE' THEN
            DBMS_SESSION.SET_CONTEXT('PROXY_SECURITY_CTX', 'APPEND_ONLY_WRITER', '1');
        ELSE
            DBMS_SESSION.SET_CONTEXT('PROXY_SECURITY_CTX', 'APPEND_ONLY_WRITER', '0');
        END IF;
    END SET_APPEND_ONLY_WRITER;
END PROXY_SECURITY_CTX_PKG;
/

CREATE OR REPLACE TRIGGER PROXY_SECURITY_LOGON_CTX
AFTER LOGON ON SCHEMA
BEGIN
    PROXY_SECURITY_CTX_PKG.SET_APPEND_ONLY_WRITER;
END;
/

CREATE OR REPLACE FUNCTION PROXY_APPEND_ONLY_POLICY (
    schema_name IN VARCHAR2,
    object_name IN VARCHAR2
) RETURN VARCHAR2 AS
BEGIN
    IF SYS_CONTEXT('PROXY_SECURITY_CTX', 'APPEND_ONLY_WRITER') = '1'
       OR SYS_CONTEXT('USERENV', 'SESSION_USER') IN ('PROXY_INGEST', 'PROXY_INGEST_ROLE')
       OR SYS_CONTEXT('SYS_SESSION_ROLES', 'PROXY_INGEST_ROLE') = 'TRUE' THEN
        RETURN '1=2';
    END IF;

    RETURN NULL;
END PROXY_APPEND_ONLY_POLICY;
/

BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => USER,
        object_name     => 'PROXY_DATA_RETENTION_POLICIES',
        policy_name     => 'AUDIT_RETENTION_TAMPERING',
        audit_condition => 'ENABLED = 0 OR RETAIN_DAYS < 30',
        statement_types => 'INSERT,UPDATE,DELETE'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28101 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    PROCEDURE add_append_only_policy(p_table_name IN VARCHAR2) AS
    BEGIN
        DBMS_RLS.ADD_POLICY(
            object_schema   => USER,
            object_name     => p_table_name,
            policy_name     => 'VPD_APPEND_ONLY',
            function_schema => USER,
            policy_function => 'PROXY_APPEND_ONLY_POLICY',
            statement_types => 'SELECT,UPDATE,DELETE',
            update_check    => FALSE,
            enable          => TRUE
        );
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -28101 THEN
                RAISE;
            END IF;
    END;
BEGIN
    add_append_only_policy('PROXY_EVENTS');
    add_append_only_policy('PROXY_PAYLOAD_AUDIT');
    add_append_only_policy('PROXY_BLOCKLIST_AUDIT');
    add_append_only_policy('PROXY_DB_QUERY_LOG');
    add_append_only_policy('WIRELESS_AUDIT_FRAMES');
    add_append_only_policy('WIRELESS_ALERTS');
    add_append_only_policy('WIRELESS_ALERTS_LEDGER');
END;
/

CREATE OR REPLACE VIEW V_OBJ_PROXY_EVENTS AS
SELECT
    ID,
    BATCH_ID,
    EVENT_TIME,
    EVENT_TIMESTAMP_UTC,
    EVENT_TYPE,
    HOST,
    obj_wireguard_identity(WG_PUBKEY, DEVICE_ID, NULL, IDENTITY_SOURCE) AS client_identity,
    obj_network_endpoint(PEER_IP, NULL, PEER_HOSTNAME) AS destination,
    obj_traffic_metrics(BYTES_UP, BYTES_DOWN, DURATION_MS) AS traffic,
    STATUS_CODE,
    BLOCKED,
    OBFUSCATION_PROFILE,
    CORRELATION_ID,
    PARENT_EVENT_ID,
    EVENT_SEQUENCE,
    REASON,
    RAW_JSON
FROM PROXY_EVENTS;

CREATE OR REPLACE VIEW VW_WIRELESS_ACTIVE_THREATS AS
SELECT ALERT_TYPE AS THREAT_TYPE,
       CASE ALERT_TYPE WHEN 'bandwidth_threshold' THEN 'CRITICAL' WHEN 'rogue_ap' THEN 'HIGH' WHEN 'deauth_flood' THEN 'HIGH' ELSE 'MEDIUM' END AS SEVERITY,
       DETECTED_AT AS EVENT_AT,
       SENSOR_ID,
       LOCATION_ID,
       PRIMARY_MAC,
       SSID,
       BYTES,
       ALERT_PK,
       ACKNOWLEDGED
FROM WIRELESS_ALERTS
WHERE ACKNOWLEDGED = 0
ORDER BY CASE ALERT_TYPE WHEN 'bandwidth_threshold' THEN 1 WHEN 'rogue_ap' THEN 2 WHEN 'deauth_flood' THEN 2 ELSE 3 END, DETECTED_AT DESC;

CREATE OR REPLACE VIEW VW_WIRELESS_BW_DAILY_SUMMARY AS
SELECT TRUNC(CAST(WINDOW_START AS DATE)) AS TRAFFIC_DATE,
       SENSOR_ID,
       LOCATION_ID,
       SOURCE_MAC,
       DESTINATION_BSSID,
       SSID,
       EXTERNAL_BSSID,
       SUM(BYTES) AS TOTAL_BYTES,
       SUM(FRAME_COUNT) AS TOTAL_FRAMES,
       SUM(RETRY_COUNT) AS TOTAL_RETRIES,
       MAX(STRONGEST_SIGNAL_DBM) AS MAX_SIGNAL_DBM,
       MIN(STRONGEST_SIGNAL_DBM) AS MIN_SIGNAL_DBM,
       COUNT(*) AS WINDOW_COUNT,
       SUM(CASE WHEN THRESHOLD_EXCEEDED = 1 THEN 1 ELSE 0 END) AS THRESHOLD_EXCEEDED_COUNT,
       AVG(WALL_CLOCK_DELTA_MS) AS AVG_SENSOR_LAG_MS
FROM WIRELESS_BANDWIDTH_WINDOWS
GROUP BY TRUNC(CAST(WINDOW_START AS DATE)), SENSOR_ID, LOCATION_ID, SOURCE_MAC, DESTINATION_BSSID, SSID, EXTERNAL_BSSID;

CREATE OR REPLACE VIEW VW_WIRELESS_CURRENT_CLIENTS AS
SELECT inv.*
FROM WIRELESS_CLIENT_INVENTORY inv
JOIN (
    SELECT SENSOR_ID, MAX(SNAPSHOT_AT) AS LATEST_SNAP
    FROM WIRELESS_CLIENT_INVENTORY
    GROUP BY SENSOR_ID
) latest ON inv.SENSOR_ID = latest.SENSOR_ID AND inv.SNAPSHOT_AT = latest.LATEST_SNAP;

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name => 'WIRELESS_GATHER_STATS_NIGHTLY',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, ''WIRELESS_AUDIT_FRAMES'', granularity=>''AUTO'', degree=>4); DBMS_STATS.GATHER_TABLE_STATS(USER, ''WIRELESS_BANDWIDTH_WINDOWS'', granularity=>''AUTO'', degree=>4); DBMS_STATS.GATHER_TABLE_STATS(USER, ''WIRELESS_CLIENT_INVENTORY'', granularity=>''AUTO'', degree=>2); END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY;BYHOUR=3;BYMINUTE=0',
        enabled => TRUE,
        comments => 'Nightly CBO stats refresh for wireless tables'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN
            RAISE;
        END IF;
END;
/
