-- Postgres schema bootstrap shim.
-- Auto-generated by scripts/split_postgres_schema.py.
-- Source of truth: sql/postgres.source.sql and split sql/* folders.

-- extensions
\ir extensions/001_extensions.sql

-- schemas
\ir schemas/001_coordinator.sql

-- types

-- tables
\ir tables/001_sync_cursors.sql
\ir tables/002_sync_events.sql
\ir tables/003_wireless_frames.sql
\ir tables/004_sync_jobs.sql
\ir tables/005_sync_batches.sql
\ir tables/006_sync_errors.sql
\ir tables/007_sync_backlog.sql
\ir tables/008_wireless_authorized_networks.sql
\ir tables/009_wireless_clients.sql
\ir tables/010_wireless_shadow_alerts.sql
\ir tables/011_devices.sql
\ir tables/012_device_identity_clusters.sql
\ir tables/013_vec_embeddings.sql
\ir tables/014_vec_behaviour_snapshots.sql
\ir tables/015_vec_baseline_profiles.sql
\ir tables/016_vec_frame_sequences.sql
\ir tables/017_vec_transition_model.sql
\ir tables/018_vec_infrastructure_graph.sql
\ir tables/019_vec_similarity_pairs.sql
\ir tables/020_vec_embedding_jobs.sql
\ir tables/021_vec_worker_state.sql
\ir tables/022_vec_alerts.sql
\ir tables/023_vec_job_locks.sql
\ir tables/024_vec_timing_profiles.sql
\ir tables/025_vec_rf_sensor_locations.sql
\ir tables/026_vec_dns_policy.sql
\ir tables/027_vec_dns_resolver_ledger.sql

-- indexes
\ir indexes/001_sync_events_indexes.sql
\ir indexes/002_wireless_frames_indexes.sql
\ir indexes/003_vec_embeddings_indexes.sql
\ir indexes/004_vec_behaviour_snapshots_indexes.sql
\ir indexes/005_vec_frame_sequences_indexes.sql
\ir indexes/006_vec_transition_model_indexes.sql
\ir indexes/007_vec_infrastructure_graph_indexes.sql
\ir indexes/008_vec_similarity_pairs_indexes.sql
\ir indexes/009_vec_embedding_jobs_indexes.sql
\ir indexes/010_vec_alerts_indexes.sql
\ir indexes/011_device_identity_clusters_indexes.sql
\ir indexes/012_vec_timing_profiles_indexes.sql
\ir indexes/014_vec_detector_support_indexes.sql

-- functions
\ir functions/001_sync_stable_uuid.sql
\ir functions/002_coordinator_safe_helpers.sql
\ir functions/003_vec_job_lock_helpers.sql
\ir functions/003_upsert_wireless_frame.sql
\ir functions/004_vec_update_transition_model.sql
\ir functions/005_vec_score_sequence.sql
\ir functions/006_vec_build_infrastructure_graph.sql
\ir functions/007_vec_detect_rogue_clusters.sql
\ir functions/008_vec_build_frame_sequences.sql
\ir functions/009_vec_build_baseline_profiles.sql
\ir functions/010_vec_build_behaviour_snapshots.sql
\ir functions/011_vec_enqueue_embedding_jobs.sql
\ir functions/012_vec_lease_embedding_jobs.sql
\ir functions/013_vec_complete_embedding_batch.sql
\ir functions/045_vec_complete_one_embedding.sql
\ir functions/014_vec_materialize_similarity_pairs.sql
\ir functions/015_vec_reembed_changed_jobs.sql
\ir functions/040_vec_apply_similarity_flags.sql
\ir functions/016_vec_release_expired_leases.sql
\ir functions/017_vec_reap_stale_workers.sql
\ir functions/018_vec_assign_device_cluster.sql
\ir functions/019_check_high_risk_aps.sql
\ir functions/020_coordinator_ensure_cursor.sql
\ir functions/021_coordinator_record_scan_request.sql
\ir functions/022_coordinator_record_scan_request_batch.sql
\ir functions/023_coordinator_process_ingest_ledger.sql
\ir functions/024_coordinator_recover_stale_dispatched_batches.sql
\ir functions/025_coordinator_release_batch_dispatch.sql
\ir functions/026_coordinator_mark_batch_dispatch_failed.sql
\ir functions/027_coordinator_get_next_batch.sql
\ir functions/028_coordinator_generate_shadow_alerts.sql
\ir functions/029_coordinator_process_batch_result.sql
\ir functions/030_coordinator_process_batch_results.sql
\ir functions/031_coordinator_save_backlog_entry.sql
\ir functions/032_coordinator_list_pending_backlog.sql
\ir functions/033_coordinator_mark_backlog_synced.sql
\ir functions/034_coordinator_prune_backlog.sql
\ir functions/035_coordinator_lookup_device_by_mac.sql
\ir functions/036_coordinator_list_authorized_networks.sql
\ir functions/037_coordinator_flush_probe_batch.sql
\ir functions/038_coordinator_pending_ledger_count.sql
\ir functions/039_vec_build_timing_profiles.sql
\ir functions/041_vec_update_device_centroids.sql
\ir functions/042_vec_fuse_device_identities.sql
\ir functions/043_vec_reembed_on_alert.sql

-- views
\ir views/001_sync_events_expanded.sql
\ir views/002_v_wireless_audit_with_devices.sql
\ir views/003_v_wireless_threats.sql
\ir views/004_v_wireless_session_timeline.sql
\ir views/005_v_wireless_device_inventory.sql
\ir views/006_v_wireless_anomalies.sql
\ir views/007_v_sync_plane_health.sql
\ir views/008_v_wireless_shadow_alerts.sql
\ir views/009_v_bssid_anomaly_score.sql
\ir views/010_v_wireless_session_timeline.sql
\ir views/011_v_ap_risk_score.sql
\ir views/012_v_vec_similarity_audit.sql
\ir views/013_v_wireless_device_inventory.sql

-- unschedule stale cron jobs before materialized view DDL
\ir cron/000_unschedule_cron_jobs.sql

-- materialized_views
\ir materialized_views/001_mv_ap_risk_score.sql
\ir materialized_views/002_v_device_repetition_score.sql

-- cron
\ir cron/001_vec_install_cron_jobs.sql
