from __future__ import annotations

import configparser
import re
from pathlib import Path
from urllib.parse import quote


def trim_spaces(value: str) -> str:
    return value.strip()


def trim_key_value(value: str) -> str:
    return re.sub(r"[\r\n\s]+", "", value)


def contains_unresolved_placeholder(value: str) -> bool:
    return "<" in value or ">" in value or "generated by scripts/gen-secrets env" in value


def is_placeholder_value(value: str | None) -> bool:
    return value is None or value == "" or value.startswith("<")


def uri_encode(value: str) -> str:
    return quote(value, safe="")


def validate_peer_name(peer_id: str) -> None:
    if not peer_id or re.search(r"[^A-Za-z0-9_-]", peer_id):
        raise ValueError(f"Invalid peer id in WG_PEERS: {peer_id}")


def peer_names(raw: str) -> list[str]:
    peers: list[str] = []
    for item in raw.split(","):
        peer_id = trim_spaces(item)
        if not peer_id:
            continue
        validate_peer_name(peer_id)
        peers.append(peer_id)
    return peers


def read_dotenv_value(path: Path, key: str) -> str | None:
    if not path.is_file():
        return None
    selected: str | None = None
    prefix = f"{key}="
    for raw_line in path.read_text().splitlines():
        if not raw_line.startswith(prefix):
            continue
        selected = raw_line[len(prefix) :].rstrip("\r")
    if selected is None:
        return None
    if selected.startswith('"') and selected.endswith('"') and len(selected) >= 2:
        selected = selected[1:-1]
    return selected


def read_ini_value(path: Path, section: str, key: str) -> str | None:
    if not path.is_file():
        return None
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    parser.read(path)
    if not parser.has_section(section):
        return None
    for option, value in parser.items(section):
        if option.strip() == key:
            return value.strip()
    return None

