{{- if not .Values.external }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssl-proxy.redis.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ssl-proxy.redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "ssl-proxy.redis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ include "ssl-proxy.redis.image" (dict "root" . "image" .Values.image) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
