{{- if not .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-proxy.redis.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-proxy.redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "ssl-proxy.redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
